use super::*;

#[test]
fn callable_bodies_covers_functions_and_methods() {
    let a = PhpAdapter::new();
    let src = "<?php\nfunction slugify($s) {\n    $t = strtolower($s);\n    return trim($t);\n}\nclass C {\n    public function run($x) {\n        return $x * 2;\n    }\n}\n";
    let names: Vec<String> = a
        .callable_bodies(src)
        .into_iter()
        .map(|b| b.symbol)
        .collect();
    assert!(names.contains(&"slugify".to_string()), "{names:?}");
    assert!(names.contains(&"run".to_string()), "{names:?}");
}

const SRC: &str = r#"<?php
namespace App\Service;

use Symfony\Component\HttpFoundation\Response;
use GuzzleHttp\Client as HttpClient;
use App\Model\{User, Account};

// header comment
class UserService
{
private int $count = 0;

public function __construct(private HttpClient $client, string $name)
{
    $this->name = $name;
    $total = 0;
}

public function fetch(int $id): ?Response
{
    try {
        $resp = $this->client->get($id);
        return Response::fromArray($resp);
    } catch (\Throwable $e) {
        throw new RuntimeException("fail");
    }
}
}

function helper($a, $b)
{
return $a + $b;
}
"#;

#[test]
fn imports_reduce_to_leading_namespace_segment() {
    let adapter = PhpAdapter::new();
    let imports = adapter.extract_imports(SRC);
    assert!(imports.contains("Symfony"));
    assert!(imports.contains("GuzzleHttp"));
    assert!(imports.contains("App")); // grouped use App\Model\{...}
                                      // The file's own `namespace App\Service;` is not an import; only the
                                      // `use App\Model\{...}` contributes "App".
    assert!(!imports.contains("Response"));
    assert!(!imports.contains("HttpClient"));
}

#[test]
fn import_spans_cover_the_leading_segment() {
    let adapter = PhpAdapter::new();
    let spans = adapter.extract_imports_with_spans(SRC);
    let symfony = spans.iter().find(|(s, ..)| s == "Symfony").unwrap();
    assert_eq!(symfony.3 - symfony.2, "Symfony".len());
    // Sorted ascending by (line, col).
    for pair in spans.windows(2) {
        assert!((pair[0].1, pair[0].2) <= (pair[1].1, pair[1].2));
    }
}

#[test]
fn callable_definitions_capture_class_method_and_function() {
    let adapter = PhpAdapter::new();
    let defs = adapter.callable_definitions(SRC);
    assert!(defs.contains("UserService"));
    assert!(defs.contains("fetch"));
    assert!(defs.contains("helper"));
    assert!(defs.contains("__construct"));
}

#[test]
fn value_bindings_capture_assignments_and_parameters() {
    let adapter = PhpAdapter::new();
    let binds = adapter.value_bindings(SRC);
    assert!(binds.contains("$total")); // assignment target
    assert!(binds.contains("$name")); // simple parameter
    assert!(binds.contains("$client")); // promoted constructor property
    assert!(binds.contains("$id"));
}

#[test]
fn internal_import_bindings_are_empty() {
    let adapter = PhpAdapter::new();
    assert!(adapter.internal_import_bindings(SRC).is_empty());
}

#[test]
fn prose_lines_cover_comments() {
    let adapter = PhpAdapter::new();
    let rows = adapter.prose_line_ranges(SRC);
    // "// header comment" sits on line 8 (1-indexed).
    assert!(rows.contains(&8));
}

#[test]
fn sampleable_ranges_span_top_level_units() {
    let adapter = PhpAdapter::new();
    let ranges = adapter.enumerate_sampleable_ranges(SRC);
    // One range for `class UserService` and one for `function helper`.
    assert_eq!(ranges.len(), 2);
    // The class spans multiple lines.
    assert!(ranges.iter().any(|(s, e)| e - s > 5));
}

#[test]
fn config_array_file_is_data_dominant() {
    let adapter = PhpAdapter::new();
    let src = r#"<?php
return [
"host" => "localhost",
"port" => 8080,
"debug" => true,
"name" => "argot",
"retries" => 3,
];
"#;
    assert!(adapter.is_data_dominant(src, 0.65));
    let lines = adapter.data_literal_lines(src);
    assert!(lines.contains(&3)); // "host" => "localhost"
}

#[test]
fn code_file_is_not_data_dominant() {
    let adapter = PhpAdapter::new();
    assert!(!adapter.is_data_dominant(SRC, 0.65));
}

#[test]
fn auto_generated_header_is_detected() {
    let adapter = PhpAdapter::new();
    let src = "<?php\n/** @generated by protoc — do not edit. */\nclass Foo {}\n";
    assert!(adapter.is_auto_generated(src, &crate::test_support::generated_markers()));
    assert!(!adapter.is_auto_generated(SRC, &crate::test_support::generated_markers()));
}

#[test]
fn identifier_noise_contains_keywords() {
    let adapter = PhpAdapter::new();
    assert!(adapter.identifier_noise().contains("function"));
    assert!(adapter.identifier_noise().contains("$this"));
    assert_eq!(adapter.identifier_noise().len(), NOISE.len());
}
