//! C# language adapter.
//!
//! Structural port following the same manual `TreeCursor`/`child_by_field_name`
//! traversal style as `python.rs` and `typescript.rs`. C# is a statically
//! typed, namespaced language, so this adapter is closest in spirit to the
//! TypeScript one (typed declarations, member-access call chains, `new`
//! expressions) — but the import model differs: C# `using` names a namespace,
//! never a relative path.
//!
//! Notes worth keeping in mind:
//! - `using System.Net.Http;` imports the whole namespace `System.Net.Http`;
//!   like TS specifiers, the dotted name is kept verbatim (never split on `.`).
//! - `global using X;` / `using static X;` differ only by anonymous keyword
//!   tokens — the namespace child is still a bare `qualified_name`/`identifier`.
//! - `using Foo = Bar.Baz;` is an alias: the LHS carries the `name` field, so
//!   the imported target is the *other* `qualified_name`/`identifier` child.
//! - C# `using` never carries a relative specifier, so
//!   `internal_import_bindings` is empty — repo-internal namespaces are
//!   discovered corpus-wide via `extract_imports` at fit time (like Python).

use std::collections::HashSet;
use std::path::Path;

use tree_sitter::{Node, Tree};

use super::{Language, LanguageAdapter, RepoModules};
use crate::text::splitlines;

use super::HEADER_LINE_LIMIT;

/// Declaration node kinds that bind a callable/type name (`name` field).
const CS_CALLABLE_DEFINITION_TYPES: &[&str] = &[
    "method_declaration",
    "constructor_declaration",
    "class_declaration",
    "interface_declaration",
    "struct_declaration",
    "record_declaration",
    "record_struct_declaration",
    "enum_declaration",
    "property_declaration",
];

/// Declaration kinds whose full line span is a sampleable calibration hunk.
const CS_SAMPLEABLE_TYPES: &[&str] = &["method_declaration", "constructor_declaration"];

/// Invocation / construction node kinds treated as calls.
const CS_CALL_TYPES: &[&str] = &["invocation_expression", "object_creation_expression"];

/// Initializer container kinds that can hold a static data literal.
const CS_DATA_CONTAINER_TYPES: &[&str] = &[
    "array_creation_expression",
    "implicit_array_creation_expression",
    "object_creation_expression",
    "collection_expression",
    "initializer_expression",
];

/// Element node kinds that count as literal data inside an initializer.
const CS_VALUE_LITERAL_TYPES: &[&str] = &[
    "integer_literal",
    "real_literal",
    "string_literal",
    "verbatim_string_literal",
    "raw_string_literal",
    "interpolated_string_expression",
    "character_literal",
    "boolean_literal",
    "null_literal",
    "initializer_expression",
    "collection_expression",
];

/// C#-specific structural generated tells not covered by the generic
/// `[detect].generated-markers`: the `<auto-generated>` doc convention and the
/// `[GeneratedCode]` / `[CompilerGenerated]` attributes. Generic phrases
/// ("auto-generated", "do not edit", tool banners, …) come from config, so a
/// custom marker a user adds applies to C# too.
const CS_STRUCTURAL_MARKERS: &[&str] = &[
    "<auto-generated",
    "generatedcode",
    "generatedcodeattribute",
    "compilergenerated",
    "this code was generated",
];

const VALUE_DOMINANT_THRESHOLD: f64 = 0.8;

/// Parse C# `source` into a tree-sitter `Tree` (reused per-thread parser).
fn parse(source: &str) -> Tree {
    crate::ts_parse::parse(source, Language::CSharp)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    go(node, &mut out);
    out
}

/// Direct children of `node` as a `Vec`.
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// The imported name of a `using_directive`: the `qualified_name` /
/// `identifier` child that is *not* the alias LHS (which carries field `name`).
fn using_import_name<'a>(using: Node<'a>) -> Option<Node<'a>> {
    let mut cursor = using.walk();
    if !cursor.goto_first_child() {
        return None;
    }
    loop {
        let node = cursor.node();
        let is_alias_lhs = cursor.field_name() == Some("name");
        if !is_alias_lhs && matches!(node.kind(), "qualified_name" | "identifier") {
            return Some(node);
        }
        if !cursor.goto_next_sibling() {
            return None;
        }
    }
}

/// The initializer expression bound by a `variable_declarator` — the first
/// named child that is not the `name` field.
fn declarator_initializer<'a>(declarator: Node<'a>) -> Option<Node<'a>> {
    let mut cursor = declarator.walk();
    if !cursor.goto_first_child() {
        return None;
    }
    loop {
        let node = cursor.node();
        if node.is_named() && cursor.field_name() != Some("name") {
            return Some(node);
        }
        if !cursor.goto_next_sibling() {
            return None;
        }
    }
}

/// The `initializer_expression` (`{ ... }`) inside a data container, if any.
/// `array`/`object` creations wrap their braces in an `initializer_expression`
/// child; a bare `initializer_expression` / `collection_expression` is itself
/// the block.
fn initializer_block<'a>(node: Node<'a>) -> Option<Node<'a>> {
    match node.kind() {
        "initializer_expression" | "collection_expression" => Some(node),
        _ => children(node)
            .into_iter()
            .find(|c| matches!(c.kind(), "initializer_expression" | "collection_expression")),
    }
}

/// True if ≥80% of the block's element children are literal data. Empty blocks
/// return true (conservative — allow).
fn is_value_literal_dominant(block: Node) -> bool {
    let values: Vec<Node> = children(block)
        .into_iter()
        .filter(|c| c.is_named())
        .collect();
    if values.is_empty() {
        return true;
    }
    let literal = values
        .iter()
        .filter(|v| CS_VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal as f64) / (values.len() as f64) >= VALUE_DOMINANT_THRESHOLD
}

/// Add 0-indexed row spans of data-literal `variable_declarator`s to `rows`.
fn collect_cs_data_rows(root: Node, rows: &mut HashSet<usize>) {
    for node in descendants(root) {
        if node.kind() != "variable_declarator" {
            continue;
        }
        let Some(init) = declarator_initializer(node) else {
            continue;
        };
        if !CS_DATA_CONTAINER_TYPES.contains(&init.kind()) {
            continue;
        }
        let Some(block) = initializer_block(init) else {
            continue;
        };
        if is_value_literal_dominant(block) {
            for r in node.start_position().row..=node.end_position().row {
                rows.insert(r);
            }
        }
    }
}

/// The simple type name of an `object_creation_expression`'s `type` field,
/// with generic type arguments stripped (`List<int>` → `List`).
fn creation_type_name(ty: Node, source: &str) -> Option<String> {
    match ty.kind() {
        "identifier" | "qualified_name" => Some(node_text(ty, source).to_string()),
        "generic_name" => children(ty)
            .into_iter()
            .find(|c| c.kind() == "identifier")
            .map(|id| node_text(id, source).to_string()),
        _ => None,
    }
}

/// Build the dotted callee for an `invocation_expression` /
/// `object_creation_expression`, or `None` when the chain bottoms out at an
/// unsupported expression.
fn extract_cs_callee(call_node: Node, source: &str) -> Option<String> {
    if call_node.kind() == "object_creation_expression" {
        let ty = call_node.child_by_field_name("type")?;
        return creation_type_name(ty, source);
    }
    // invocation_expression
    let mut callee = call_node.child_by_field_name("function")?;
    let mut parts: Vec<String> = Vec::new();
    while callee.kind() == "member_access_expression" {
        let name = callee.child_by_field_name("name")?;
        parts.insert(0, node_text(name, source).to_string());
        // A rooted member access (`x.y.M`) recurses through `expression`; a
        // grammar with no `expression` field bottoms out at the method name.
        match callee.child_by_field_name("expression") {
            Some(expr) => callee = expr,
            None => return Some(parts.join(".")),
        }
    }
    match callee.kind() {
        "identifier" => {
            parts.insert(0, node_text(callee, source).to_string());
            Some(parts.join("."))
        }
        "generic_name" => {
            let id = children(callee)
                .into_iter()
                .find(|c| c.kind() == "identifier")?;
            parts.insert(0, node_text(id, source).to_string());
            Some(parts.join("."))
        }
        // `this.M()` / `base.M()` — `this`/`base` are anonymous receiver nodes;
        // keep them (mirrors the TypeScript adapter's `this`/`super` handling)
        // so class-internal call voice stays visible.
        "this" | "base" => {
            parts.insert(0, node_text(callee, source).to_string());
            Some(parts.join("."))
        }
        k if CS_CALL_TYPES.contains(&k) => {
            parts.insert(0, "<call>".to_string());
            Some(parts.join("."))
        }
        _ => None,
    }
}

/// `CSharpAdapter` — the language adapter for `.cs` sources.
#[derive(Debug, Default)]
pub struct CSharpAdapter {
    noise: HashSet<String>,
}

impl CSharpAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Namespaces imported by `using` directives (dotted names kept verbatim).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "using_directive" {
                continue;
            }
            if let Some(name) = using_import_name(node) {
                let spec = node_text(name, source);
                if !spec.is_empty() {
                    out.insert(spec.to_string());
                }
            }
        }
        out
    }

    /// Like `extract_imports` but each namespace carries its `(spec, line,
    /// col_start, col_end)` span. Line 1-indexed; columns 0-indexed byte
    /// offsets over the namespace text, end exclusive. Sorted by
    /// `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "using_directive" {
                continue;
            }
            if let Some(name) = using_import_name(node) {
                let spec = node_text(name, source);
                if spec.is_empty() {
                    continue;
                }
                let line = name.start_position().row + 1;
                let col_start = name.start_position().column;
                let col_end = col_start + spec.len();
                out.push((spec.to_string(), line, col_start, col_end));
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// Repo-owned namespace prefixes from the corpus's own `namespace`
    /// declarations (block and file-scoped forms): `using` any namespace the
    /// repo declares is never foreign voice, including namespaces added
    /// after fit time (issue #92).
    pub fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        let mut modules = RepoModules::default();
        for file in super::walk_files_with_suffix(repo_root, &[".cs"]) {
            let Ok(text) = crate::text::read_text_lossy(&file) else {
                continue;
            };
            for line in text.lines() {
                let trimmed = line.trim();
                let Some(rest) = trimmed.strip_prefix("namespace ") else {
                    continue;
                };
                let ns: String = rest
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '.' || *c == '_')
                    .collect();
                if !ns.is_empty() {
                    modules.exact.insert(ns.clone());
                    modules.prefixes.insert(format!("{ns}."));
                }
            }
        }
        modules
    }

    /// True if the file is overwhelmingly static data literals (threshold 0.65).
    pub fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        if source.trim().is_empty() {
            return false;
        }
        let total_nonblank = splitlines(source)
            .iter()
            .filter(|line| !line.trim().is_empty())
            .count();
        if total_nonblank == 0 {
            return false;
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_cs_data_rows(tree.root_node(), &mut rows);
        (rows.len() as f64) / (total_nonblank as f64) > threshold
    }

    /// 1-indexed line numbers covered by static data-literal declarations.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_cs_data_rows(tree.root_node(), &mut rows);
        rows.into_iter().map(|r| r + 1).collect()
    }

    /// Names bound to callable/type definitions (methods, constructors,
    /// classes, interfaces, structs, records, enums, properties). Feeds
    /// local-binding attestation: code calling what it defines is not foreign.
    /// Method/constructor/local-function definitions with their line ranges — the
    /// embeddable units for the semantic index. Type and property declarations are
    /// containers/accessors, not standalone function bodies, so they are skipped.
    pub fn callable_bodies(&self, source: &str) -> Vec<super::CallableBody> {
        let tree = parse(source);
        let mut out = Vec::new();
        for node in descendants(tree.root_node()) {
            if matches!(
                node.kind(),
                "method_declaration" | "constructor_declaration" | "local_function_statement"
            ) {
                if let Some(name) = node.child_by_field_name("name") {
                    out.push(super::CallableBody {
                        symbol: node_text(name, source).to_string(),
                        start_line: node.start_position().row + 1,
                        end_line: node.end_position().row + 1,
                    });
                }
            }
        }
        out
    }

    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if CS_CALLABLE_DEFINITION_TYPES.contains(&node.kind()) {
                if let Some(name) = node.child_by_field_name("name") {
                    out.insert(node_text(name, source).to_string());
                }
            }
        }
        out
    }

    /// C# `using` directives never bind repo-internal (relative) names, so this
    /// is always empty (namespaces are the import stage's concern).
    pub fn internal_import_bindings(&self, _source: &str) -> HashSet<String> {
        HashSet::new()
    }

    /// Every locally bound value name — variable declarators and parameters.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if matches!(node.kind(), "variable_declarator" | "parameter") {
                if let Some(name) = node.child_by_field_name("name") {
                    out.insert(node_text(name, source).to_string());
                }
            }
        }
        out
    }

    /// True if a header comment/attribute (first `HEADER_LINE_LIMIT` lines)
    /// carries an auto-generation marker (case-insensitive) — C#'s structural
    /// tells or any of the configured `[detect].generated-markers`.
    pub fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        if source.is_empty() {
            return false;
        }
        for line in splitlines(source).iter().take(HEADER_LINE_LIMIT) {
            let lower = line.to_lowercase();
            if CS_STRUCTURAL_MARKERS.iter().any(|m| lower.contains(m))
                || markers.iter().any(|m| lower.contains(&m.to_lowercase()))
            {
                return true;
            }
        }
        false
    }

    /// 1-indexed `(start_line, end_line)` spans for method and constructor
    /// declarations (wherever nested) — the sampleable calibration hunks.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let mut ranges: Vec<(usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if CS_SAMPLEABLE_TYPES.contains(&node.kind()) {
                ranges.push((node.start_position().row + 1, node.end_position().row + 1));
            }
        }
        ranges
    }

    /// 1-indexed line numbers covered by comments (`//`, `/* */`, `///` doc).
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() == "comment" {
                for r in (node.start_position().row + 1)..=(node.end_position().row + 1) {
                    rows.insert(r);
                }
            }
        }
        rows
    }

    /// Dotted-callee signatures for every invocation / construction in
    /// `source`. Not on the `LanguageAdapter` trait — an inherent method
    /// mirroring the TypeScript adapter's `extract_callees`.
    pub fn extract_callees(&self, source: &str) -> Vec<String> {
        if source.trim().is_empty() {
            return Vec::new();
        }
        let tree = parse(source);
        let mut out: Vec<String> = Vec::new();
        for node in descendants(tree.root_node()) {
            if CS_CALL_TYPES.contains(&node.kind()) {
                if let Some(callee) = extract_cs_callee(node, source) {
                    out.push(callee);
                }
            }
        }
        out
    }

    /// C# reserved + contextual keywords and literals filtered out of the
    /// repo-wide identifier vocabulary.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

impl LanguageAdapter for CSharpAdapter {
    fn language(&self) -> Language {
        Language::CSharp
    }
    fn extract_imports(&self, source: &str) -> HashSet<String> {
        CSharpAdapter::extract_imports(self, source)
    }
    fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        CSharpAdapter::extract_imports_with_spans(self, source)
    }
    fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        CSharpAdapter::resolve_repo_modules(self, repo_root)
    }
    fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        CSharpAdapter::is_data_dominant(self, source, threshold)
    }
    fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        CSharpAdapter::data_literal_lines(self, source)
    }
    fn callable_definitions(&self, source: &str) -> HashSet<String> {
        CSharpAdapter::callable_definitions(self, source)
    }
    fn callable_bodies(&self, source: &str) -> Vec<super::CallableBody> {
        CSharpAdapter::callable_bodies(self, source)
    }
    fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        CSharpAdapter::internal_import_bindings(self, source)
    }
    fn value_bindings(&self, source: &str) -> HashSet<String> {
        CSharpAdapter::value_bindings(self, source)
    }
    fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        CSharpAdapter::is_auto_generated(self, source, markers)
    }
    fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        CSharpAdapter::enumerate_sampleable_ranges(self, source)
    }
    fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        CSharpAdapter::prose_line_ranges(self, source)
    }
    fn identifier_noise(&self) -> &HashSet<String> {
        CSharpAdapter::identifier_noise(self)
    }
    fn line_comment_prefix(&self) -> &'static str {
        "//"
    }
}

/// C# reserved keywords + common contextual keywords + literals.
const NOISE: &[&str] = &[
    "abstract",
    "as",
    "base",
    "bool",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "checked",
    "class",
    "const",
    "continue",
    "decimal",
    "default",
    "delegate",
    "do",
    "double",
    "else",
    "enum",
    "event",
    "explicit",
    "extern",
    "false",
    "finally",
    "fixed",
    "float",
    "for",
    "foreach",
    "goto",
    "if",
    "implicit",
    "in",
    "int",
    "interface",
    "internal",
    "is",
    "lock",
    "long",
    "namespace",
    "new",
    "null",
    "object",
    "operator",
    "out",
    "override",
    "params",
    "private",
    "protected",
    "public",
    "readonly",
    "ref",
    "return",
    "sbyte",
    "sealed",
    "short",
    "sizeof",
    "stackalloc",
    "static",
    "string",
    "struct",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "uint",
    "ulong",
    "unchecked",
    "unsafe",
    "ushort",
    "using",
    "virtual",
    "void",
    "volatile",
    "while",
    // Contextual keywords.
    "add",
    "and",
    "async",
    "await",
    "dynamic",
    "get",
    "global",
    "init",
    "nameof",
    "nint",
    "not",
    "nuint",
    "or",
    "partial",
    "record",
    "remove",
    "required",
    "set",
    "value",
    "var",
    "when",
    "where",
    "with",
    "yield",
];

#[cfg(test)]
mod tests;
