//! Java language adapter.
//!
//! Behaviour mirrors the other adapters (`python.rs`, `typescript.rs`): a
//! manual `TreeCursor`/`child_by_field_name`/`children` traversal of the pinned
//! tree-sitter-java grammar, exposing the same surface the scorers and sampler
//! need. Java is brace-based and C-family, so the structure follows the
//! TypeScript adapter closely.
//!
//! Notes worth keeping in mind:
//! - Java imports are always fully qualified (`import java.util.List;`); there
//!   is no relative-import form, so `internal_import_bindings` is always empty
//!   and repo-internal packages are discovered via `extract_imports` at fit
//!   time (like `python.rs`).
//! - The "module" for foreign-detection is the whole dotted import path
//!   (`java.util.List`, `com.squareup.okhttp3` for a `com.squareup.okhttp3.*`
//!   wildcard). We keep the importable path verbatim rather than splitting on
//!   `.`, mirroring the TypeScript adapter's "never split the specifier" rule.
//! - The shared Python-grammar `data_dominant`/`autogenerated` filters cannot
//!   see Java syntax (`//` comments, `{...}` array literals), so this adapter
//!   implements those heuristics against the Java tree directly, exactly as the
//!   TypeScript adapter does for `.ts`.

use crate::filters::autogenerated;
use std::collections::HashSet;
use std::path::Path;

use tree_sitter::{Node, Tree};

use super::{Language, LanguageAdapter, RepoModules};

use super::HEADER_LINE_LIMIT;

/// Value node kinds that count as literal data for the data-dominant check.
const JAVA_VALUE_LITERAL_TYPES: &[&str] = &[
    "string_literal",
    "character_literal",
    "decimal_integer_literal",
    "hex_integer_literal",
    "octal_integer_literal",
    "binary_integer_literal",
    "decimal_floating_point_literal",
    "hex_floating_point_literal",
    "true",
    "false",
    "null_literal",
    "array_initializer",
];

/// Call-expression node kinds (also used as the chain-root sentinel).
const JAVA_CALL_TYPES: &[&str] = &["method_invocation", "object_creation_expression"];

// Auto-generation markers — the same generic set the other adapters use.

/// Parse Java `source` into a tree-sitter `Tree` (reused parser).
fn parse(source: &str) -> Tree {
    crate::ts_parse::parse(source, crate::adapters::Language::Java)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    for child in node.children(&mut cursor) {
        out.push(child);
        go(child, &mut out);
    }
    out
}

/// Direct children of `node` as a `Vec`.
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// The dotted import path under an `import_declaration` — the `scoped_identifier`
/// or bare `identifier` naming the imported type/member. `None` for a malformed
/// import with no name node.
fn import_path(node: Node<'_>) -> Option<Node<'_>> {
    for c in children(node) {
        if matches!(c.kind(), "scoped_identifier" | "identifier") {
            return Some(c);
        }
    }
    None
}

/// Last dotted segment of an import path text (`java.util.List` → `List`).
fn last_segment(path: &str) -> &str {
    path.rsplit('.').next().unwrap_or(path)
}

/// Simple type name of a type node used as a constructor receiver
/// (`new java.util.ArrayList<String>()` → `ArrayList`).
fn type_simple_name(node: Node, source: &str) -> Option<String> {
    match node.kind() {
        "type_identifier" => Some(node_text(node, source).to_string()),
        "generic_type" => children(node)
            .into_iter()
            .find(|c| c.is_named())
            .and_then(|c| type_simple_name(c, source)),
        "scoped_type_identifier" => node
            .child_by_field_name("name")
            .map(|n| node_text(n, source).to_string())
            .or_else(|| {
                children(node)
                    .into_iter()
                    .rfind(|c| c.kind() == "type_identifier")
                    .map(|c| node_text(c, source).to_string())
            }),
        _ => Some(node_text(node, source).to_string()),
    }
}

/// True if ≥80% of the array initializer's immediate named values are literal
/// data. Empty containers return true (conservative — allow).
fn is_java_value_literal_dominant(node: Node) -> bool {
    if node.kind() != "array_initializer" {
        return true;
    }
    let values: Vec<Node> = children(node)
        .into_iter()
        .filter(|c| c.is_named())
        .collect();
    if values.is_empty() {
        return true;
    }
    let literal_count = values
        .iter()
        .filter(|v| JAVA_VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal_count as f64) / (values.len() as f64) >= 0.8
}

/// Add 0-indexed row spans of `field_declaration` data tables (a
/// `variable_declarator` whose value is a literal-dominant `array_initializer`)
/// to `rows`. Java constant tables live as `static final X[] = {...}` fields, so
/// every `field_declaration` in the file is inspected (including nested types).
fn collect_java_data_rows(root: Node, rows: &mut HashSet<usize>) {
    for node in descendants(root) {
        if node.kind() != "field_declaration" {
            continue;
        }
        for decl in children(node) {
            if decl.kind() != "variable_declarator" {
                continue;
            }
            let Some(value) = decl.child_by_field_name("value") else {
                continue;
            };
            if value.kind() == "array_initializer" && is_java_value_literal_dominant(value) {
                for r in node.start_position().row..=node.end_position().row {
                    rows.insert(r);
                }
            }
        }
    }
}

/// Build the dotted receiver chain for a `method_invocation` object node.
///
/// `obj.doThing()` → receiver `obj`; `a.b.c()` → `a.b`; `this.field.run()` →
/// `this.field`. A call in the chain (`foo().bar()`) contributes the `<call>`
/// sentinel, mirroring the TypeScript callee extractor. Returns `None` when the
/// chain bottoms out at an expression we don't model (array access, cast, …).
fn build_receiver(node: Node, source: &str) -> Option<String> {
    match node.kind() {
        "identifier" | "type_identifier" => Some(node_text(node, source).to_string()),
        "this" => Some("this".to_string()),
        "super" => Some("super".to_string()),
        "method_invocation" | "object_creation_expression" => Some("<call>".to_string()),
        "field_access" => {
            let field = node.child_by_field_name("field")?;
            let field_text = node_text(field, source);
            match node.child_by_field_name("object") {
                Some(obj) => {
                    let base = build_receiver(obj, source).unwrap_or_else(|| "<call>".to_string());
                    Some(format!("{base}.{field_text}"))
                }
                None => Some(field_text.to_string()),
            }
        }
        _ => None,
    }
}

/// Dotted-callee signature for a `method_invocation` / `object_creation_expression`,
/// or `None` when the receiver chain bottoms out at an unmodelled expression.
fn extract_java_callee(call_node: Node, source: &str) -> Option<String> {
    if call_node.kind() == "object_creation_expression" {
        let ty = call_node.child_by_field_name("type")?;
        return type_simple_name(ty, source);
    }
    // method_invocation
    let name = call_node.child_by_field_name("name")?;
    let method = node_text(name, source).to_string();
    match call_node.child_by_field_name("object") {
        None => Some(method),
        Some(obj) => {
            let base = build_receiver(obj, source)?;
            Some(format!("{base}.{method}"))
        }
    }
}

/// `JavaAdapter` — the language adapter for `.java` sources.
#[derive(Debug, Default)]
pub struct JavaAdapter {
    noise: HashSet<String>,
}

impl JavaAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Fully-qualified module paths imported in `source`. `import java.util.List`
    /// yields `java.util.List`; a wildcard `import com.foo.*` yields `com.foo`;
    /// a static import `import static org.junit.Assert.assertEquals` yields
    /// `org.junit.Assert.assertEquals`. Error-tolerant: git picks hunk
    /// boundaries, so fragments carry root parse errors — tree-sitter still
    /// yields the well-formed imports within.
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "import_declaration" {
                continue;
            }
            if let Some(path) = import_path(node) {
                out.insert(node_text(path, source).to_string());
            }
        }
        out
    }

    /// Like `extract_imports` but each specifier carries its `(spec, line,
    /// col_start, col_end)` span. Line 1-indexed; columns 0-indexed byte
    /// offsets covering the dotted path, end exclusive. Sorted by
    /// `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "import_declaration" {
                continue;
            }
            if let Some(path) = import_path(node) {
                let spec = node_text(path, source).to_string();
                let line = path.start_position().row + 1;
                let col_start = path.start_position().column;
                let col_end = col_start + spec.len();
                out.push((spec, line, col_start, col_end));
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// Repo-owned package prefixes from the corpus's own `package`
    /// declarations: importing any class or static member under a package
    /// the repo declares is never foreign voice — including symbols no file
    /// had imported at fit time (issue #92: a commit expanding wildcard
    /// static imports to explicit ones flooded the import tripwire with the
    /// repo's own members).
    pub fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        let mut modules = RepoModules::default();
        for file in super::walk_files_with_suffix(repo_root, &[".java"]) {
            let Ok(text) = crate::text::read_text_lossy(&file) else {
                continue;
            };
            for line in text.lines() {
                let trimmed = line.trim();
                if let Some(rest) = trimmed.strip_prefix("package ") {
                    let pkg = rest.trim_end().trim_end_matches(';').trim();
                    if !pkg.is_empty()
                        && pkg
                            .chars()
                            .all(|c| c.is_alphanumeric() || c == '.' || c == '_')
                    {
                        modules.exact.insert(pkg.to_string());
                        modules.prefixes.insert(format!("{pkg}."));
                    }
                    break;
                }
            }
        }
        modules
    }

    /// Names the source binds to callable definitions — methods, constructors,
    /// and type declarations (class/interface/enum/record). Feeds local-binding
    /// attestation: code calling what it defines is not foreign voice.
    /// Method/constructor definitions with their line ranges — the embeddable
    /// units for the semantic index. Type declarations (class/interface/enum/
    /// record) are containers, not function bodies, so they are skipped.
    pub fn callable_bodies(&self, source: &str) -> Vec<super::CallableBody> {
        let tree = parse(source);
        let mut out = Vec::new();
        for node in descendants(tree.root_node()) {
            if matches!(
                node.kind(),
                "method_declaration" | "constructor_declaration"
            ) {
                if let Some(name) = node.child_by_field_name("name") {
                    out.push(super::CallableBody {
                        symbol: node_text(name, source).to_string(),
                        start_line: node.start_position().row + 1,
                        end_line: node.end_position().row + 1,
                    });
                }
            }
        }
        out
    }

    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "method_declaration"
                | "constructor_declaration"
                | "class_declaration"
                | "interface_declaration"
                | "enum_declaration"
                | "record_declaration" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        out.insert(node_text(name, source).to_string());
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// Java imports are all absolute, so there are no relative (repo-internal)
    /// bindings to attest here — always empty.
    pub fn internal_import_bindings(&self, _source: &str) -> HashSet<String> {
        HashSet::new()
    }

    /// Every locally bound value name — local variables, fields, and formal /
    /// catch parameters — plus the simple names imports bring into scope
    /// (`import java.util.List` binds `List`; a wildcard binds nothing). Whether
    /// the MODULE is in-voice is the import stage's question.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "local_variable_declaration" | "field_declaration" => {
                    for decl in children(node) {
                        if decl.kind() == "variable_declarator" {
                            if let Some(name) = decl.child_by_field_name("name") {
                                out.insert(node_text(name, source).to_string());
                            }
                        }
                    }
                }
                "formal_parameter" | "catch_formal_parameter" | "spread_parameter" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        out.insert(node_text(name, source).to_string());
                    }
                }
                "import_declaration" => {
                    // A non-wildcard import binds its final segment as a simple
                    // name; a wildcard (`com.foo.*`) binds nothing specific.
                    let is_wildcard = children(node).iter().any(|c| c.kind() == "asterisk");
                    if !is_wildcard {
                        if let Some(path) = import_path(node) {
                            out.insert(last_segment(node_text(path, source)).to_string());
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// True if the file is overwhelmingly static array-literal tables
    /// (threshold 0.65 of non-blank lines).
    pub fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        if source.trim().is_empty() {
            return false;
        }
        let tree = parse(source);
        let total_nonblank = source.lines().filter(|l| !l.trim().is_empty()).count();
        if total_nonblank == 0 {
            return false;
        }
        let mut rows: HashSet<usize> = HashSet::new();
        collect_java_data_rows(tree.root_node(), &mut rows);
        (rows.len() as f64) / (total_nonblank as f64) > threshold
    }

    /// 1-indexed line numbers covered by static array-literal table fields.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_java_data_rows(tree.root_node(), &mut rows);
        rows.into_iter().map(|r| r + 1).collect()
    }

    /// True if the file header carries an auto-generation marker: a `@Generated`
    /// annotation anywhere, or a comment marker within the first
    /// `HEADER_LINE_LIMIT` lines (strong DO-NOT-EDIT markers count in the first
    /// 10). Comments only — a marker inside a string cannot trip a false hit.
    pub fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        if source.is_empty() {
            return false;
        }
        let tree = parse(source);
        let root = tree.root_node();
        for node in descendants(root) {
            match node.kind() {
                "annotation" | "marker_annotation" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        if node_text(name, source) == "Generated" {
                            return true;
                        }
                    }
                }
                "line_comment" | "block_comment" => {
                    let line_index = node.start_position().row;
                    if line_index >= HEADER_LINE_LIMIT {
                        continue;
                    }
                    let text = node_text(node, source);
                    if autogenerated::comment_indicates_generated(
                        line_index,
                        text,
                        HEADER_LINE_LIMIT,
                        markers,
                    ) {
                        return true;
                    }
                }
                _ => {}
            }
        }
        false
    }

    /// 1-indexed inclusive `(start_line, end_line)` spans for every method and
    /// constructor declaration — the executable code ranges calibration samples
    /// as hunks. Methods nest inside class bodies, so the whole tree is walked.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let mut ranges = Vec::new();
        for node in descendants(tree.root_node()) {
            if matches!(
                node.kind(),
                "method_declaration" | "constructor_declaration"
            ) {
                ranges.push((node.start_position().row + 1, node.end_position().row + 1));
            }
        }
        ranges
    }

    /// 1-indexed line numbers covered by comments (line and block/javadoc).
    /// Java has no docstring concept; all prose is in comments.
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(tree.root_node()) {
            if matches!(node.kind(), "line_comment" | "block_comment") {
                rows.extend(crate::ts_parse::prose_rows(source, node));
            }
        }
        rows
    }

    /// Dotted-callee signatures for every call in `source` (non-`None` only).
    /// `[]` on empty source. Not on the `LanguageAdapter` trait — an inherent
    /// method mirroring the TypeScript adapter's `extract_callees`.
    pub fn extract_callees(&self, source: &str) -> Vec<String> {
        if source.trim().is_empty() {
            return Vec::new();
        }
        let tree = parse(source);
        let mut out: Vec<String> = Vec::new();
        for node in descendants(tree.root_node()) {
            if JAVA_CALL_TYPES.contains(&node.kind()) {
                if let Some(callee) = extract_java_callee(node, source) {
                    out.push(callee);
                }
            }
        }
        out
    }

    /// Java reserved words, primitives, and literal keywords filtered out of the
    /// repo-wide identifier vocabulary.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

impl LanguageAdapter for JavaAdapter {
    fn language(&self) -> Language {
        Language::Java
    }
    fn extract_imports(&self, source: &str) -> HashSet<String> {
        JavaAdapter::extract_imports(self, source)
    }
    fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        JavaAdapter::extract_imports_with_spans(self, source)
    }
    fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        JavaAdapter::resolve_repo_modules(self, repo_root)
    }
    fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        JavaAdapter::is_data_dominant(self, source, threshold)
    }
    fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        JavaAdapter::data_literal_lines(self, source)
    }
    fn callable_definitions(&self, source: &str) -> HashSet<String> {
        JavaAdapter::callable_definitions(self, source)
    }
    fn callable_bodies(&self, source: &str) -> Vec<super::CallableBody> {
        JavaAdapter::callable_bodies(self, source)
    }
    fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        JavaAdapter::internal_import_bindings(self, source)
    }
    fn value_bindings(&self, source: &str) -> HashSet<String> {
        JavaAdapter::value_bindings(self, source)
    }
    fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        JavaAdapter::is_auto_generated(self, source, markers)
    }
    fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        JavaAdapter::enumerate_sampleable_ranges(self, source)
    }
    fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        JavaAdapter::prose_line_ranges(self, source)
    }
    fn identifier_noise(&self) -> &HashSet<String> {
        JavaAdapter::identifier_noise(self)
    }
    fn line_comment_prefix(&self) -> &'static str {
        "//"
    }
}

/// Java reserved words + primitive types + literal keywords.
const NOISE: &[&str] = &[
    "abstract",
    "assert",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extends",
    "final",
    "finally",
    "float",
    "for",
    "goto",
    "if",
    "implements",
    "import",
    "instanceof",
    "int",
    "interface",
    "long",
    "native",
    "new",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "strictfp",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "try",
    "var",
    "void",
    "volatile",
    "while",
    "yield",
    "true",
    "false",
    "null",
];

#[cfg(test)]
mod tests;
