//! Pascal language adapter — the `.pas`/`.pp`/`.dpr`/`.lpr` counterpart of the
//! other adapters, covering Object Pascal (Delphi + FreePascal dialects) via
//! the pinned `tree-sitter-pascal` grammar.
//!
//! Pascal has no relative-import syntax: a unit pulls dependencies with a flat
//! `uses A, B, C;` clause (interface- and implementation-section), and there is
//! nothing in the grammar to tell a repo-internal unit apart from a third-party
//! one. So — like Java/Go — the foreign-dependency signal comes from
//! [`extract_imports`](PascalAdapter::extract_imports) (the top-level segment of
//! each used unit) checked against the repo's own units, which
//! [`resolve_repo_modules`](PascalAdapter::resolve_repo_modules) discovers by
//! scanning the `unit`/`program`/`library` declarations across the tree.
//! `internal_import_bindings` is therefore always empty.
//!
//! Grammar notes worth keeping in mind:
//! - `declUses` holds one `moduleName` per used unit; a dotted unit
//!   (`Generics.Collections`, `mormot.core.json`) is a `moduleName` whose named
//!   children are the segment `identifier`s joined by `kDot`. The *top* segment
//!   is the dependency identity (matches the scorer's "top-level module only").
//! - A procedure/function is declared with `declProc` (`kProcedure`/`kFunction`/
//!   `kConstructor`/`kDestructor` + a `name` field) and defined with `defProc`
//!   (a `header: declProc` + optional `local` + `body: block`). A method
//!   definition's `name` is a `genericDot` (`TFoo.Bar`) — the method is its
//!   `rhs`.
//! - `declType` names both classes and records (the `type` field is a
//!   `declClass` carrying a `kClass` or `kRecord` token).
//! - `//`, `{ … }` and `(* … *)` all parse to a single `comment` node.
//! - Calls are `exprCall` (`entity` field: an `identifier` or an `exprDot`
//!   chain).
//! - Pascal is case-insensitive. Unit names fold to one identity (see
//!   `unit_identity`); other identifiers are kept verbatim like every other
//!   adapter, since the surrounding scorers compare them against a vocabulary
//!   learned from the same tree.

use std::collections::HashSet;
use std::path::Path;

use tree_sitter::{Node, Tree};

use crate::filters::autogenerated;

use super::{
    walk_files_with_suffix, CallableBody, Language, LanguageAdapter, RepoModules, HEADER_LINE_LIMIT,
};

/// File suffixes scanned for repo-owned unit declarations. `.inc` include
/// fragments carry no `unit`/`program` header, so they are not scanned here.
const UNIT_FILE_SUFFIXES: &[&str] = &[".pas", ".pp", ".dpr", ".lpr"];

/// How many head lines of a file are scanned for the module declaration.
const MODULE_DECL_SCAN_LINES: usize = 60;

/// RHS container kinds that count as static data-literal containers.
const DATA_LITERAL_TYPES: &[&str] = &["arrInitializer"];

/// Named value node kinds that count as literal data inside a container.
const VALUE_LITERAL_TYPES: &[&str] = &[
    "literalNumber",
    "literalString",
    "literalChar",
    "kTrue",
    "kFalse",
    "kNil",
    "arrInitializer",
];

/// ≥80% of a container's immediate named values must be literal data.
const VALUE_DOMINANT_THRESHOLD: f64 = 0.8;

/// Parse Pascal `source` into a tree-sitter `Tree` (reused per-thread parser).
pub(crate) fn parse(source: &str) -> Tree {
    crate::ts_parse::parse(source, Language::Pascal)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut stack = vec![node];
    while let Some(n) = stack.pop() {
        let mut cursor = n.walk();
        let children: Vec<Node<'a>> = n.children(&mut cursor).collect();
        for child in children.into_iter().rev() {
            out.push(child);
            stack.push(child);
        }
    }
    out
}

/// Direct children of `node`.
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// The top-level segment of a dotted unit name string (`mormot.core.base` →
/// `mormot`).
fn name_top_segment(name: &str) -> &str {
    name.split('.').next().unwrap_or(name).trim()
}

/// A unit name reduced to its identity.
///
/// Object Pascal is case-insensitive: `SysUtils`, `sysutils`, `sysUtils` and
/// `Sysutils` are one unit, and a real repository writes all four (MSEide/MSEgui
/// does, 200/289/15/2 times). Comparing the spellings instead of the identity
/// splits one dependency into several — 30 of MSEgui's 907 learned Pascal
/// specifiers were case-variants of another entry, and the supersession miner
/// read `sysutils` → `SysUtils` as a migration from a unit to itself. Folding
/// here means every surface (imports, declarations, the miner, the import
/// graph) compares the same identity.
fn unit_identity(name: &str) -> String {
    name.to_lowercase()
}

/// The unit names a `declUses` clause lists.
///
/// Reads `moduleName` children, plus identifiers the grammar wrapped in an
/// `ERROR` node: a conditional-compilation directive inside the clause
/// (`uses {$if defined(darwin)} cwstring {$else} msecwstring {$endif}`, straight
/// out of MSEgui's kernel) leaves the branch without a trailing comma
/// unparsed, so the unit it names would otherwise be invisible to the model
/// and every later `uses` of it would read as a brand-new dependency. The
/// `declUses` scope bounds the recovery — `{$if …}` conditions parse as `pp`
/// leaves, so no identifier from them can leak in.
fn uses_identifiers<'a>(decl_uses: Node<'a>, source: &'a str) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    for child in children(decl_uses) {
        match child.kind() {
            "moduleName" => out.extend(
                children(child)
                    .into_iter()
                    .find(|c| c.kind() == "identifier")
                    .filter(|id| !node_text(*id, source).is_empty()),
            ),
            "ERROR" => out.extend(
                children(child)
                    .into_iter()
                    .filter(|c| c.kind() == "identifier" && !node_text(*c, source).is_empty()),
            ),
            _ => {}
        }
    }
    out
}

/// The proc/func/constructor/destructor name a `declProc` binds. The `name`
/// field is a plain `identifier` for an interface/forward declaration, a
/// `genericDot` (`TFoo.Bar`) for a method definition's header (the method is
/// its `rhs`), or an `operatorName` for an operator overload.
fn proc_name<'a>(decl_proc: Node<'a>, source: &'a str) -> Option<&'a str> {
    let name = decl_proc.child_by_field_name("name")?;
    match name.kind() {
        "genericDot" => name
            .child_by_field_name("rhs")
            .map(|r| node_text(r, source))
            .or_else(|| Some(node_text(name, source))),
        _ => Some(node_text(name, source)),
    }
}

/// `PascalAdapter` — the language adapter for Object Pascal sources.
#[derive(Debug, Default)]
pub struct PascalAdapter {
    noise: HashSet<String>,
}

impl PascalAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Top-level segments of every unit pulled in by a `uses` clause (interface
    /// or implementation section, and the program/library `uses`). The segment
    /// is the dependency identity; a repo-internal unit is filtered later by the
    /// import-graph scorer against [`resolve_repo_modules`](Self::resolve_repo_modules).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        self.extract_imports_with_spans(source)
            .into_iter()
            .map(|(spec, _, _, _)| spec)
            .collect()
    }

    /// Like [`extract_imports`](Self::extract_imports) but each specifier carries
    /// its `(spec, line, col_start, col_end)` span, the caret pointing at the
    /// top segment. Line is 1-indexed; columns are 0-indexed byte offsets.
    /// Sorted by `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "declUses" {
                continue;
            }
            for id in uses_identifiers(node, source) {
                let raw = node_text(id, source);
                let spec = unit_identity(name_top_segment(raw));
                if spec.is_empty() {
                    continue;
                }
                let line = id.start_position().row + 1;
                let col_start = id.start_position().column;
                let col_end = col_start + raw.len();
                out.push((spec, line, col_start, col_end));
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// Always empty: Pascal has no relative-import form. Repo-internal units are
    /// recognised via [`resolve_repo_modules`](Self::resolve_repo_modules).
    pub fn internal_import_bindings(&self, _source: &str) -> HashSet<String> {
        HashSet::new()
    }

    /// The repo's own units, discovered by scanning each source file's
    /// `unit`/`program`/`library` declaration and registering the declaration's
    /// top-level segment (mirroring [`extract_imports`](Self::extract_imports)).
    /// A `uses` of one of these is repo-internal, not a foreign dependency.
    pub fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        let mut modules = RepoModules::default();
        for file in walk_files_with_suffix(repo_root, UNIT_FILE_SUFFIXES) {
            let Ok(text) = crate::text::read_text_lossy(&file) else {
                continue;
            };
            if let Some(name) = module_declaration_name(&text) {
                let seg = unit_identity(name_top_segment(&name));
                if !seg.is_empty() {
                    modules.exact.insert(seg);
                }
            }
        }
        modules
    }

    /// The `unit`/`program`/`library` name this source declares, reduced to
    /// its top segment the same way [`Self::extract_imports`] reduces a `uses`
    /// entry — so a declaration and a reference to it compare equal.
    pub fn declared_module(&self, source: &str) -> Option<String> {
        let name = module_declaration_name(source)?;
        let seg = unit_identity(name_top_segment(&name));
        (!seg.is_empty()).then_some(seg)
    }

    /// Names bound by callable/type definitions — every `declProc`
    /// (proc/func/constructor/destructor, in an interface, a class body, or a
    /// `defProc` header) plus every `declType` (class/record/interface/enum
    /// name). Local-binding attestation: code calling what it defines, or
    /// constructing a type it declares (`TFoo.Create`), is not foreign voice.
    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "declProc" => {
                    if let Some(name) = proc_name(node, source) {
                        if !name.is_empty() {
                            out.insert(name.to_string());
                        }
                    }
                }
                "declType" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        out.insert(node_text(name, source).to_string());
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// Procedure/function definitions with their 1-indexed inclusive line ranges
    /// — the embeddable units for the semantic index. Each `defProc` (an
    /// implementation body) yields its header's method/proc name.
    pub fn callable_bodies(&self, source: &str) -> Vec<CallableBody> {
        let tree = parse(source);
        let mut out = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "defProc" {
                continue;
            }
            let Some(header) = node.child_by_field_name("header") else {
                continue;
            };
            if let Some(name) = proc_name(header, source) {
                out.push(CallableBody {
                    symbol: name.to_string(),
                    start_line: node.start_position().row + 1,
                    end_line: node.end_position().row + 1,
                });
            }
        }
        out
    }

    /// Every locally bound value name — `var`/`const`/argument/field names and
    /// assignment targets. Attests bare calls only: calling a value you just
    /// bound is neighbourhood behaviour, not foreign voice.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "declVar" | "declConst" | "declArg" | "declField" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        if name.kind() == "identifier" {
                            out.insert(node_text(name, source).to_string());
                        }
                    }
                }
                "assignment" => {
                    if let Some(lhs) = node.child_by_field_name("lhs") {
                        if lhs.kind() == "identifier" {
                            out.insert(node_text(lhs, source).to_string());
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// True if the file header carries an auto-generation marker (head 20 lines).
    /// The shared detector parses with the Python grammar, which cannot see
    /// Pascal's `{ … }` / `(* … *)` / `//` comments, so — like Java/Go/C — this
    /// scans the Pascal `comment` nodes directly and reuses the shared
    /// marker-matching rule.
    pub fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        if source.is_empty() {
            return false;
        }
        let tree = parse(source);
        for node in descendants(tree.root_node()) {
            if node.kind() != "comment" {
                continue;
            }
            let line_index = node.start_position().row;
            if line_index >= HEADER_LINE_LIMIT {
                continue;
            }
            if autogenerated::comment_indicates_generated(
                line_index,
                node_text(node, source),
                HEADER_LINE_LIMIT,
                markers,
            ) {
                return true;
            }
        }
        false
    }

    /// True if the file is overwhelmingly top-level data-literal `const`/`var`
    /// tables (`arrInitializer` of literals), threshold `threshold` of non-blank
    /// lines.
    pub fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        if source.trim().is_empty() {
            return false;
        }
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() && root.kind() == "ERROR" {
            return false;
        }
        let total_nonblank = crate::text::splitlines(source)
            .iter()
            .filter(|line| !line.trim().is_empty())
            .count();
        if total_nonblank == 0 {
            return false;
        }
        let data_rows = self.data_rows(root);
        (data_rows.len() as f64) / (total_nonblank as f64) > threshold
    }

    /// 1-indexed line numbers covered by data-literal `const`/`var` spans.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() && root.kind() == "ERROR" {
            return HashSet::new();
        }
        self.data_rows(root).into_iter().map(|r| r + 1).collect()
    }

    /// 0-indexed rows covered by `const`/`var` declarations whose value is a
    /// literal-dominant `arrInitializer` (big lookup tables).
    fn data_rows(&self, root: Node) -> HashSet<usize> {
        let mut rows = HashSet::new();
        for node in descendants(root) {
            if !matches!(node.kind(), "declConst" | "declVar") {
                continue;
            }
            let value = decl_value_node(node);
            if let Some(value) = value {
                if DATA_LITERAL_TYPES.contains(&value.kind()) && is_value_literal_dominant(value) {
                    for r in node.start_position().row..=node.end_position().row {
                        rows.insert(r);
                    }
                }
            }
        }
        rows
    }

    /// 1-indexed inclusive spans for procedure/function definitions (`defProc`)
    /// at any depth. A unit with only interface declarations (no bodies) falls
    /// back to its top-level type declarations; a file with neither yields
    /// nothing to sample.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut ranges: Vec<(usize, usize)> = Vec::new();
        for node in descendants(root) {
            if node.kind() == "defProc" {
                ranges.push((node.start_position().row + 1, node.end_position().row + 1));
            }
        }
        if ranges.is_empty() {
            for node in descendants(root) {
                if node.kind() == "declType" {
                    ranges.push((node.start_position().row + 1, node.end_position().row + 1));
                }
            }
        }
        ranges.sort_unstable();
        ranges.dedup();
        ranges
    }

    /// 1-indexed line numbers covered by comments — `//` line comments and
    /// `{ … }` / `(* … *)` blocks (all a single `comment` node kind).
    fn prose_mask(&self, source: &str) -> crate::ts_parse::ProseMask {
        let tree = parse(source);
        let mut mask = crate::ts_parse::ProseMask::default();
        for node in descendants(tree.root_node()) {
            if node.kind() == "comment" {
                mask.add(source, node);
            }
        }
        mask
    }

    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        self.prose_mask(source).rows
    }

    /// Prose sharing a line with code: blanked in place, so the code survives
    /// and the words do not reach the scorers.
    pub fn prose_spans(&self, source: &str) -> Vec<(usize, usize, usize)> {
        self.prose_mask(source).spans
    }

    /// Pascal keywords, built-in pseudo-values and the ubiquitous `Result`/
    /// `Self` — noise tokens that would dominate `common here:` without saying
    /// anything.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

impl LanguageAdapter for PascalAdapter {
    fn language(&self) -> Language {
        Language::Pascal
    }
    fn extract_imports(&self, source: &str) -> HashSet<String> {
        PascalAdapter::extract_imports(self, source)
    }
    fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        PascalAdapter::extract_imports_with_spans(self, source)
    }
    fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        PascalAdapter::resolve_repo_modules(self, repo_root)
    }
    fn declared_module(&self, source: &str) -> Option<String> {
        PascalAdapter::declared_module(self, source)
    }
    fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        PascalAdapter::is_data_dominant(self, source, threshold)
    }
    fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        PascalAdapter::data_literal_lines(self, source)
    }
    fn callable_definitions(&self, source: &str) -> HashSet<String> {
        PascalAdapter::callable_definitions(self, source)
    }
    fn callable_bodies(&self, source: &str) -> Vec<CallableBody> {
        PascalAdapter::callable_bodies(self, source)
    }
    fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        PascalAdapter::internal_import_bindings(self, source)
    }
    fn value_bindings(&self, source: &str) -> HashSet<String> {
        PascalAdapter::value_bindings(self, source)
    }
    fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        PascalAdapter::is_auto_generated(self, source, markers)
    }
    fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        PascalAdapter::enumerate_sampleable_ranges(self, source)
    }
    fn prose_spans(&self, source: &str) -> Vec<(usize, usize, usize)> {
        Self::prose_spans(self, source)
    }
    fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        PascalAdapter::prose_line_ranges(self, source)
    }
    fn identifier_noise(&self) -> &HashSet<String> {
        PascalAdapter::identifier_noise(self)
    }
    fn identifiers_are_case_insensitive(&self) -> bool {
        true
    }
    fn line_comment_prefix(&self) -> &'static str {
        "//"
    }
}

/// The value node of a `declConst`/`declVar` declaration: for a `declConst` it
/// is the last named child of the `defaultValue` field; for a `declVar` (with an
/// initializer) it is the last named child after the type.
fn decl_value_node(decl: Node) -> Option<Node> {
    if let Some(dv) = decl.child_by_field_name("defaultValue") {
        return children(dv).into_iter().rfind(|c| c.is_named());
    }
    // `var x: T = (...)` — grab a trailing arrInitializer/literal sibling.
    children(decl)
        .into_iter()
        .filter(|c| c.is_named())
        .rev()
        .find(|c| VALUE_LITERAL_TYPES.contains(&c.kind()))
}

/// True if ≥80% of the container's immediate named values are literal data.
/// Empty containers and unknown kinds return true (conservative — allow).
fn is_value_literal_dominant(node: Node) -> bool {
    if node.kind() != "arrInitializer" {
        return true;
    }
    let values: Vec<Node> = children(node)
        .into_iter()
        .filter(|c| c.is_named())
        .collect();
    if values.is_empty() {
        return true;
    }
    let literal_count = values
        .iter()
        .filter(|v| VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal_count as f64) / (values.len() as f64) >= VALUE_DOMINANT_THRESHOLD
}

/// The declared module name of a Pascal source: the identifier after the first
/// `unit`/`program`/`library` keyword (case-insensitive) in the file head,
/// skipping comment/blank lines. Verbatim (dotted names kept whole).
fn module_declaration_name(source: &str) -> Option<String> {
    let mut in_block_comment = false;
    for line in source.lines().take(MODULE_DECL_SCAN_LINES) {
        let mut trimmed = line.trim();
        if in_block_comment {
            match trimmed.find('}').or_else(|| trimmed.find("*)")) {
                Some(i) => {
                    trimmed = trimmed[i + 1..].trim();
                    in_block_comment = false;
                }
                None => continue,
            }
        }
        if trimmed.is_empty() || trimmed.starts_with("//") {
            continue;
        }
        if trimmed.starts_with('{') || trimmed.starts_with("(*") {
            let close = trimmed.find('}').or_else(|| trimmed.find("*)"));
            match close {
                Some(i) => {
                    trimmed = trimmed[i + 1..].trim();
                    if trimmed.is_empty() {
                        continue;
                    }
                }
                None => {
                    in_block_comment = true;
                    continue;
                }
            }
        }
        let lower = trimmed.to_ascii_lowercase();
        for kw in ["unit ", "program ", "library "] {
            if let Some(rest) = lower.strip_prefix(kw) {
                let end = rest
                    .find(|c: char| c == ';' || c.is_whitespace())
                    .unwrap_or(rest.len());
                // Map the lowercased offset back onto the original-case slice.
                let start = kw.len();
                let name = trimmed[start..start + end].trim();
                if !name.is_empty() {
                    return Some(name.to_string());
                }
            }
        }
        // First real code line was not a module declaration (e.g. an include
        // fragment) — stop scanning.
        return None;
    }
    None
}

/// Pascal reserved words, built-in pseudo-values, and the ubiquitous
/// `Result`/`Self`. Case as written; the noise set is matched case-sensitively
/// like every other adapter (real repos are internally consistent).
const NOISE: &[&str] = &[
    "and",
    "array",
    "as",
    "asm",
    "begin",
    "case",
    "class",
    "const",
    "constructor",
    "destructor",
    "dispinterface",
    "div",
    "do",
    "downto",
    "else",
    "end",
    "except",
    "exports",
    "false",
    "file",
    "finalization",
    "finally",
    "for",
    "function",
    "goto",
    "if",
    "implementation",
    "in",
    "inherited",
    "initialization",
    "inline",
    "interface",
    "is",
    "label",
    "library",
    "mod",
    "nil",
    "not",
    "object",
    "of",
    "or",
    "out",
    "packed",
    "procedure",
    "program",
    "property",
    "raise",
    "record",
    "repeat",
    "resourcestring",
    "set",
    "shl",
    "shr",
    "string",
    "then",
    "threadvar",
    "to",
    "true",
    "try",
    "type",
    "unit",
    "until",
    "uses",
    "var",
    "while",
    "with",
    "xor",
    // Object Pascal contextual/common built-ins that carry no dependency signal.
    "override",
    "virtual",
    "abstract",
    "overload",
    "reintroduce",
    "private",
    "protected",
    "public",
    "published",
    "Result",
    "Self",
    "nil",
];

#[cfg(test)]
mod tests;
