//! Ruby language adapter — the `.rb` counterpart of [`super::python`].
//!
//! Ruby is dynamic like Python: there are no static imports, so dependency
//! signal comes from `require` / `require_relative` / `load` / `autoload`
//! calls (and `include`/`extend`/`prepend` of a constant). Everything here is
//! a manual `TreeCursor`/child walk over the pinned `tree-sitter-ruby` grammar,
//! matching the style in [`super::python`] and `tokenize.rs`.
//!
//! Grammar notes worth keeping in mind:
//! - The named `class`/`module` nodes share their `kind()` with the anonymous
//!   `class`/`module` keyword tokens, so those matches are guarded with
//!   `is_named()`.
//! - A method call is a single `call` node bundling `receiver` + `method` +
//!   `arguments`; a dotted chain (`a.b.c`) nests `call` nodes through the
//!   `receiver` field rather than Python's separate `attribute` nodes.
//! - `=begin … =end` blocks parse to a single multi-line `comment` node.

use std::collections::HashSet;
use tree_sitter::{Node, Tree};

use crate::filters::autogenerated;

use super::HEADER_LINE_LIMIT;

/// RHS node kinds that count as static data-literal containers.
const DATA_LITERAL_TYPES: &[&str] = &["array", "hash"];

/// Named value node kinds that count as literal data inside a container.
const VALUE_LITERAL_TYPES: &[&str] = &[
    "string",
    "chained_string",
    "bare_string",
    "integer",
    "float",
    "rational",
    "complex",
    "true",
    "false",
    "nil",
    "simple_symbol",
    "hash_key_symbol",
    "bare_symbol",
    "delimited_symbol",
    "character",
    "array",
    "hash",
];

/// ≥80% of a container's immediate named values must be literal data.
const VALUE_DOMINANT_THRESHOLD: f64 = 0.8;

/// Parse Ruby `source` into a tree-sitter `Tree` (reused per-thread parser).
pub(crate) fn parse(source: &str) -> Tree {
    crate::ts_parse::parse(source, crate::adapters::Language::Ruby)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    go(node, &mut out);
    out
}

/// Direct children of `node`.
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// Leading path segment of a required specifier (`a/b/c` → `a`).
fn path_top_segment(path: &str) -> &str {
    path.split('/').next().unwrap_or(path)
}

/// Last path segment with a trailing `.rb` stripped (`foo/bar.rb` → `bar`).
fn path_basename(path: &str) -> &str {
    let last = path.rsplit('/').next().unwrap_or(path);
    last.strip_suffix(".rb").unwrap_or(last)
}

/// A bare call is a `call` node with no `receiver` field — the dynamic-language
/// equivalent of a top-level `require`/`include`/DSL invocation.
fn bare_call_method<'a>(node: Node<'a>) -> Option<Node<'a>> {
    if node.kind() != "call" || node.child_by_field_name("receiver").is_some() {
        return None;
    }
    node.child_by_field_name("method")
}

/// First `string` argument of a call, returned as its `string_content` node.
/// (Skips a leading symbol, as in `autoload :Foo, "foo"`.)
fn first_string_content<'a>(call: Node<'a>) -> Option<Node<'a>> {
    let args = call.child_by_field_name("arguments")?;
    for arg in children(args) {
        if arg.kind() == "string" {
            return children(arg)
                .into_iter()
                .find(|c| c.kind() == "string_content");
        }
    }
    None
}

/// Bind name for a `class`/`module` name field — the defined constant. For a
/// scoped name (`Foo::Bar`) it's the rightmost segment (`Bar`).
fn constant_binding<'a>(name: Node<'a>, source: &'a str) -> Option<&'a str> {
    match name.kind() {
        "constant" => Some(node_text(name, source)),
        "scope_resolution" => name
            .child_by_field_name("name")
            .map(|c| node_text(c, source))
            .or(Some(node_text(name, source))),
        _ => None,
    }
}

/// `RubyAdapter` — the language adapter for `.rb` sources.
#[derive(Debug, Default)]
pub struct RubyAdapter {
    noise: HashSet<String>,
}

impl RubyAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Top-level modules referenced via `require`/`load`/`autoload` (external
    /// gems). `include`/`extend`/`prepend` are deliberately *not* captured:
    /// they mix a module (usually a repo-internal one, or a stdlib module like
    /// `Comparable`) into a class — usage, not a dependency load. The gem is
    /// already signalled by its `require`; treating the mixin as an import
    /// false-alarmed on internal and standard-library modules.
    /// `require_relative` is repo-internal and handled by
    /// [`internal_import_bindings`](Self::internal_import_bindings).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            let Some(method) = bare_call_method(node) else {
                continue;
            };
            match node_text(method, source) {
                "require" | "load" | "autoload" => {
                    if let Some(content) = first_string_content(node) {
                        let seg = path_top_segment(node_text(content, source));
                        if !seg.is_empty() {
                            out.insert(seg.to_string());
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// Like [`extract_imports`](Self::extract_imports) but each specifier
    /// carries its `(spec, line, col_start, col_end)` span, the caret pointing
    /// at the leading segment. Line is 1-indexed; columns are 0-indexed byte
    /// offsets. Sorted by `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            let Some(method) = bare_call_method(node) else {
                continue;
            };
            let (anchor, spec) = match node_text(method, source) {
                "require" | "load" | "autoload" => match first_string_content(node) {
                    Some(content) => (
                        content,
                        path_top_segment(node_text(content, source)).to_string(),
                    ),
                    None => continue,
                },
                _ => continue,
            };
            if spec.is_empty() {
                continue;
            }
            let line = anchor.start_position().row + 1;
            let col_start = anchor.start_position().column;
            let col_end = col_start + spec.len();
            out.push((spec, line, col_start, col_end));
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// Names bound by repo-internal `require_relative` — the required file's
    /// basename (`require_relative "lib/foo"` → `foo`). Repo neighbours are not
    /// foreign voice.
    pub fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            let Some(method) = bare_call_method(node) else {
                continue;
            };
            if node_text(method, source) != "require_relative" {
                continue;
            }
            if let Some(content) = first_string_content(node) {
                let base = path_basename(node_text(content, source));
                if !base.is_empty() {
                    out.insert(base.to_string());
                }
            }
        }
        out
    }

    /// Names the source binds to callable definitions — `def`/`def self.`
    /// methods and `class`/`module` constants. Local-binding attestation: code
    /// calling what it defines is not foreign voice.
    /// Method definitions with their line ranges — the embeddable units for the
    /// semantic index. `method` (`def foo`) and `singleton_method` (`def self.foo`
    /// / `def obj.foo`); class/module containers are skipped.
    pub fn callable_bodies(&self, source: &str) -> Vec<super::CallableBody> {
        let tree = parse(source);
        let mut out = Vec::new();
        for node in descendants(tree.root_node()) {
            if matches!(node.kind(), "method" | "singleton_method") {
                if let Some(name) = node.child_by_field_name("name") {
                    out.push(super::CallableBody {
                        symbol: node_text(name, source).to_string(),
                        start_line: node.start_position().row + 1,
                        end_line: node.end_position().row + 1,
                    });
                }
            }
        }
        out
    }

    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "method" | "singleton_method" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        out.insert(node_text(name, source).to_string());
                    }
                }
                "class" | "module" if node.is_named() => {
                    if let Some(name) = node.child_by_field_name("name") {
                        if let Some(bound) = constant_binding(name, source) {
                            out.insert(bound.to_string());
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// Every locally bound value name — assignment targets and method/block
    /// parameters. Attests bare calls only.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        let collect_ids = |node: Node, out: &mut HashSet<String>| {
            if matches!(node.kind(), "identifier" | "constant") {
                out.insert(node_text(node, source).to_string());
                return;
            }
            for d in descendants(node) {
                if matches!(d.kind(), "identifier" | "constant") {
                    out.insert(node_text(d, source).to_string());
                }
            }
        };
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "assignment" | "operator_assignment" => {
                    if let Some(left) = node.child_by_field_name("left") {
                        collect_ids(left, &mut out);
                    }
                }
                // Parameter names, not their default-value expressions: bare
                // `identifier` children plus each structured param's `name`.
                "method_parameters" | "block_parameters" | "lambda_parameters" => {
                    for child in children(node) {
                        if child.kind() == "identifier" {
                            out.insert(node_text(child, source).to_string());
                        } else if let Some(name) = child.child_by_field_name("name") {
                            out.insert(node_text(name, source).to_string());
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// True if the file header carries an auto-generation marker (head 20
    /// lines). Ruby `#` comments are recognised by the shared, comment-scoped
    /// detector, matching the Python adapter's delegation.
    pub fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        autogenerated::is_auto_generated(source, HEADER_LINE_LIMIT, markers)
    }

    /// True if the file is overwhelmingly top-level data-literal assignments
    /// (`array`/`hash` tables), threshold 0.65 of non-blank lines.
    pub fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        if source.trim().is_empty() {
            return false;
        }
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() && root.kind() == "ERROR" {
            return false;
        }
        let total_nonblank = crate::text::splitlines(source)
            .iter()
            .filter(|line| !line.trim().is_empty())
            .count();
        if total_nonblank == 0 {
            return false;
        }
        let data_rows = self.data_rows(root);
        (data_rows.len() as f64) / (total_nonblank as f64) > threshold
    }

    /// 1-indexed line numbers covered by data-literal assignment spans.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() && root.kind() == "ERROR" {
            return HashSet::new();
        }
        self.data_rows(root).into_iter().map(|r| r + 1).collect()
    }

    /// 0-indexed rows covered by module-level (and top-level class/module body)
    /// data-literal assignments.
    fn data_rows(&self, root: Node) -> HashSet<usize> {
        let mut rows = HashSet::new();
        let top = children(root);
        collect_stmt_data_rows(&top, &mut rows);
        for child in &top {
            if matches!(child.kind(), "class" | "module") && child.is_named() {
                if let Some(body) = child.child_by_field_name("body") {
                    collect_stmt_data_rows(&children(body), &mut rows);
                }
            }
        }
        rows
    }

    /// 1-indexed inclusive spans for method definitions (`def` / `def self.`)
    /// at any depth. Pure-DSL files with no methods fall back to top-level
    /// `class`/`module` spans; a file with neither yields nothing to sample.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut ranges: Vec<(usize, usize)> = Vec::new();
        for node in descendants(root) {
            if matches!(node.kind(), "method" | "singleton_method") {
                ranges.push((node.start_position().row + 1, node.end_position().row + 1));
            }
        }
        if ranges.is_empty() {
            for child in children(root) {
                if matches!(child.kind(), "class" | "module") && child.is_named() {
                    ranges.push((child.start_position().row + 1, child.end_position().row + 1));
                }
            }
        }
        ranges.sort_unstable();
        ranges.dedup();
        ranges
    }

    /// 1-indexed line numbers covered by comments — both `#` line comments and
    /// `=begin … =end` blocks (a single multi-line comment node).
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() == "comment" {
                for r in (node.start_position().row + 1)..=(node.end_position().row + 1) {
                    rows.insert(r);
                }
            }
        }
        rows
    }

    /// Ruby keywords, pseudo-constants, and `self` — noise tokens that would
    /// dominate `common here:` without saying anything.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

/// Scan sibling statements, adding `array`/`hash` data-literal spans (0-indexed
/// rows) for assignments whose RHS is value-literal dominant.
fn collect_stmt_data_rows(stmts: &[Node], rows: &mut HashSet<usize>) {
    for stmt in stmts {
        if stmt.kind() != "assignment" {
            continue;
        }
        let Some(rhs) = stmt.child_by_field_name("right") else {
            continue;
        };
        if DATA_LITERAL_TYPES.contains(&rhs.kind()) && is_value_literal_dominant(rhs) {
            for r in stmt.start_position().row..=stmt.end_position().row {
                rows.insert(r);
            }
        }
    }
}

/// True if ≥80% of the container's immediate named values are literal data.
/// Empty containers and unknown kinds return true (conservative — allow).
fn is_value_literal_dominant(node: Node) -> bool {
    let values: Vec<Node> = match node.kind() {
        "array" => children(node)
            .into_iter()
            .filter(|c| c.is_named())
            .collect(),
        "hash" => {
            let mut vals = Vec::new();
            for child in children(node) {
                match child.kind() {
                    "pair" => {
                        if let Some(val) = child.child_by_field_name("value") {
                            vals.push(val);
                        }
                    }
                    // `**splat` is non-literal.
                    "hash_splat_argument" => vals.push(child),
                    _ => {}
                }
            }
            vals
        }
        _ => return true,
    };
    if values.is_empty() {
        return true;
    }
    let literal_count = values
        .iter()
        .filter(|v| VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal_count as f64) / (values.len() as f64) >= VALUE_DOMINANT_THRESHOLD
}

/// Ruby keywords + pseudo-constants + `self`.
const NOISE: &[&str] = &[
    "BEGIN",
    "END",
    "__ENCODING__",
    "__END__",
    "__FILE__",
    "__LINE__",
    "alias",
    "and",
    "begin",
    "break",
    "case",
    "class",
    "def",
    "defined?",
    "do",
    "else",
    "elsif",
    "end",
    "ensure",
    "false",
    "for",
    "if",
    "in",
    "module",
    "next",
    "nil",
    "not",
    "or",
    "redo",
    "rescue",
    "retry",
    "return",
    "self",
    "super",
    "then",
    "true",
    "undef",
    "unless",
    "until",
    "when",
    "while",
    "yield",
];

#[cfg(test)]
mod tests;
