//! TypeScript / JavaScript language adapter — port of
//! `engine/argot/scoring/adapters/typescript.py`.
//!
//! Behaviour-preserving port of the tree-sitter parsing logic. The Python
//! engine uses tree-sitter's Query API; we replicate the same captures with
//! manual `TreeCursor`/`child_by_field_name`/`children` traversal (matching the
//! style of `python.rs`).
//!
//! Parity notes worth keeping in mind:
//! - `extract_imports` captures `import ... from "spec"` and side-effect
//!   `import "spec"` (the `import_statement` `source` field) plus
//!   `require("spec")` calls. `export {a} from "spec"` is an `export_statement`
//!   (not `import_statement`) and is NOT captured — matching the Python query
//!   `(import_statement source: (string) @src)`.
//! - Relative specifiers (`./x`, `../x`) and Node.js subpath imports (`#…`,
//!   private to the declaring package) are excluded as repo-internal. Everything
//!   else (`@/alias`, `@myorg/pkg`, `node:fs`, bare names) is kept verbatim — TS
//!   specifiers are never split on `.` the way Python top-level modules are.
//! - Unlike the Python-language adapter, the TS adapter never bails on
//!   `root.has_error()`: the Python code only returns empty on a parse
//!   exception, which tree-sitter never raises.

use crate::filters::autogenerated;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

use tree_sitter::{Node, Tree};

use super::{Language, LanguageAdapter, RepoModules};
use crate::text::{read_text_lossy, splitlines};

use super::HEADER_LINE_LIMIT;

/// RHS node types that indicate a data-dominant initializer.
const TS_DATA_LITERAL_TYPES: &[&str] = &["array", "object"];

/// Top-level TS declaration types sampleable as calibration hunks.
const TS_SAMPLEABLE_TOP_LEVEL: &[&str] = &[
    "function_declaration",
    "class_declaration",
    "interface_declaration",
    "type_alias_declaration",
];

/// RHS node types treated as function bodies for const-arrow sampling.
const TS_FUNCTION_VALUE_TYPES: &[&str] =
    &["arrow_function", "function_expression", "class_expression"];

/// Value node types that count as literal data for the data-dominant check.
const TS_VALUE_LITERAL_TYPES: &[&str] = &[
    "string",
    "template_string",
    "number",
    "true",
    "false",
    "null",
    "undefined",
    "array",
    "object",
];

/// Call-expression node types (also used as the chain-root sentinel).
const TS_CALL_TYPES: &[&str] = &["call_expression", "new_expression"];
/// Member-access node types walked to build a dotted callee.
const TS_MEMBER_TYPES: &[&str] = &["member_expression"];
/// Identifier node types that terminate a callee chain.
const TS_IDENTIFIER_TYPES: &[&str] = &["identifier", "type_identifier"];

// Auto-generation markers — the same generic set the Python adapter uses.

/// Parse TypeScript `source` into a tree-sitter `Tree` (reused parser).
fn parse(source: &str) -> Tree {
    crate::ts_parse::parse(source, crate::adapters::Language::Typescript)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    for child in node.children(&mut cursor) {
        out.push(child);
        go(child, &mut out);
    }
    out
}

/// Direct children of `node` as a `Vec` (mirrors Python's `node.children`).
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// Strip surrounding quotes from a tree-sitter string-node text.
fn strip_quotes(text: &str) -> &str {
    let bytes = text.as_bytes();
    if bytes.len() >= 2 {
        let first = bytes[0];
        let last = bytes[bytes.len() - 1];
        if (first == b'"' || first == b'\'' || first == b'`') && last == first {
            return &text[1..text.len() - 1];
        }
    }
    text
}

fn is_relative(specifier: &str) -> bool {
    specifier.starts_with("./") || specifier.starts_with("../")
}

/// Repo-internal by specifier shape alone: a relative path (`./`, `../`) or a
/// Node.js subpath import (`#…`, private to the declaring package by the Node
/// resolution spec). Neither names a third-party dependency, so both are kept
/// out of the foreign-import surface and both bind repo-internal names.
/// (Workspace packages like `@scope/pkg` are internal too, but only their
/// resolution can tell — see [`Adapter::resolve_repo_modules`].)
fn is_internal_specifier(specifier: &str) -> bool {
    is_relative(specifier) || specifier.starts_with('#')
}

/// Return the initializer child of a `variable_declarator` — the first named
/// child after the `=` token — or `None`.
fn get_ts_rhs(node: Node) -> Option<Node> {
    let mut found_eq = false;
    for child in children(node) {
        if child.kind() == "=" && !found_eq {
            found_eq = true;
            continue;
        }
        if found_eq && child.is_named() {
            return Some(child);
        }
    }
    None
}

/// True if ≥80% of the node's immediate values are literal data. Empty
/// containers and unknown types return true (conservative — allow).
fn is_ts_value_literal_dominant(node: Node) -> bool {
    let values: Vec<Node> = match node.kind() {
        "array" => children(node)
            .into_iter()
            .filter(|c| c.is_named())
            .collect(),
        "object" => {
            let mut vals = Vec::new();
            for child in children(node) {
                match child.kind() {
                    "pair" => {
                        if let Some(val) = child.child_by_field_name("value") {
                            vals.push(val);
                        }
                    }
                    "method_definition" | "shorthand_property_identifier" => vals.push(child),
                    _ => {}
                }
            }
            vals
        }
        _ => return true,
    };
    if values.is_empty() {
        return true;
    }
    let literal_count = values
        .iter()
        .filter(|v| TS_VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal_count as f64) / (values.len() as f64) >= 0.8
}

/// Add row spans (0-indexed) of top-level data-literal declarations to `rows`.
fn collect_ts_data_rows(root: Node, rows: &mut HashSet<usize>) {
    for child in children(root) {
        let mut target_decl: Option<Node> = None;

        match child.kind() {
            "lexical_declaration" | "variable_declaration" => {
                target_decl = Some(child);
            }
            "export_statement" => {
                for sub in children(child) {
                    if matches!(sub.kind(), "lexical_declaration" | "variable_declaration") {
                        target_decl = Some(sub);
                        break;
                    }
                    // Unwrap `as_expression` (e.g. `export default { ... } as const`).
                    let inner_sub = if sub.kind() == "as_expression" {
                        children(sub).first().copied().unwrap_or(sub)
                    } else {
                        sub
                    };
                    if TS_DATA_LITERAL_TYPES.contains(&inner_sub.kind()) {
                        // export default [...] or export default {...}
                        if is_ts_value_literal_dominant(inner_sub) {
                            for r in child.start_position().row..=child.end_position().row {
                                rows.insert(r);
                            }
                        }
                        break;
                    }
                }
            }
            _ => {}
        }

        let Some(target) = target_decl else { continue };

        for decl_child in children(target) {
            if decl_child.kind() != "variable_declarator" {
                continue;
            }
            if let Some(rhs) = get_ts_rhs(decl_child) {
                if TS_DATA_LITERAL_TYPES.contains(&rhs.kind()) && is_ts_value_literal_dominant(rhs)
                {
                    for r in decl_child.start_position().row..=decl_child.end_position().row {
                        rows.insert(r);
                    }
                }
            }
        }
    }
}

/// Walk the tree for `require("specifier")` calls, returning non-relative specs.
fn extract_require_imports(root: Node, source: &str) -> Vec<String> {
    let mut mods = Vec::new();
    for node in descendants(root) {
        if node.kind() != "call_expression" {
            continue;
        }
        let (Some(func), Some(args)) = (
            node.child_by_field_name("function"),
            node.child_by_field_name("arguments"),
        ) else {
            continue;
        };
        if func.kind() != "identifier" || node_text(func, source) != "require" {
            continue;
        }
        for arg in children(args) {
            if arg.kind() == "string" {
                let spec = strip_quotes(node_text(arg, source));
                if !spec.is_empty() && !is_internal_specifier(spec) {
                    mods.push(spec.to_string());
                }
            }
        }
    }
    mods
}

/// Like `extract_require_imports` but with `(spec, line, col_start, col_end)`
/// spans. The span covers the specifier text, skipping the opening quote.
fn extract_require_imports_with_spans(
    root: Node,
    source: &str,
) -> Vec<(String, usize, usize, usize)> {
    let mut out = Vec::new();
    for node in descendants(root) {
        if node.kind() != "call_expression" {
            continue;
        }
        let (Some(func), Some(args)) = (
            node.child_by_field_name("function"),
            node.child_by_field_name("arguments"),
        ) else {
            continue;
        };
        if func.kind() != "identifier" || node_text(func, source) != "require" {
            continue;
        }
        for arg in children(args) {
            if arg.kind() == "string" {
                let spec = strip_quotes(node_text(arg, source));
                if !spec.is_empty() && !is_internal_specifier(spec) {
                    let line = arg.start_position().row + 1;
                    // Skip the opening quote so the underline lands on the spec.
                    let col_start = arg.start_position().column + 1;
                    let col_end = col_start + spec.len();
                    out.push((spec.to_string(), line, col_start, col_end));
                }
            }
        }
    }
    out
}

/// Build the dotted callee for a `call_expression` / `new_expression`, or
/// `None` when the chain bottoms out at a subscript / parenthesised expression.
fn extract_ts_callee(call_node: Node, source: &str) -> Option<String> {
    let field = if call_node.kind() == "new_expression" {
        "constructor"
    } else {
        "function"
    };
    let mut callee = call_node.child_by_field_name(field)?;
    let mut parts: Vec<String> = Vec::new();
    while TS_MEMBER_TYPES.contains(&callee.kind()) {
        let prop = callee.child_by_field_name("property")?;
        let obj = callee.child_by_field_name("object")?;
        parts.insert(0, node_text(prop, source).to_string());
        callee = obj;
    }
    if TS_IDENTIFIER_TYPES.contains(&callee.kind()) {
        parts.insert(0, node_text(callee, source).to_string());
        return Some(parts.join("."));
    }
    if TS_CALL_TYPES.contains(&callee.kind()) {
        parts.insert(0, "<call>".to_string());
        return Some(parts.join("."));
    }
    None
}

/// Expand a workspaces value into its list of glob patterns. Accepts either an
/// array (`["packages/*"]`) or an object with a `packages` array.
fn workspace_patterns(ws: Option<&serde_json::Value>) -> Vec<String> {
    let list = match ws {
        Some(v) if v.is_object() => v.get("packages"),
        other => other,
    };
    match list {
        Some(serde_json::Value::Array(arr)) => arr
            .iter()
            .filter_map(|p| p.as_str().map(str::to_string))
            .collect(),
        _ => Vec::new(),
    }
}

/// Match a single path segment against a glob segment supporting `*`, `?` and
/// `[...]` character classes (fnmatch semantics — `*`/`?` never cross `/`).
fn fnmatch_segment(pattern: &str, name: &str) -> bool {
    fn class_match(cls: &[char], c: char) -> (bool, usize) {
        // cls starts just after '['; returns (matched, consumed-incl-']').
        let mut i = 0;
        let negate = cls.first() == Some(&'!');
        if negate {
            i += 1;
        }
        let mut matched = false;
        let mut consumed_close = None;
        let start = i;
        while i < cls.len() {
            if cls[i] == ']' && i > start {
                consumed_close = Some(i);
                break;
            }
            // range a-z
            if i + 2 < cls.len() && cls[i + 1] == '-' && cls[i + 2] != ']' {
                if cls[i] <= c && c <= cls[i + 2] {
                    matched = true;
                }
                i += 3;
            } else {
                if cls[i] == c {
                    matched = true;
                }
                i += 1;
            }
        }
        match consumed_close {
            // +1 for '[', +1 to move past ']'
            Some(close) => (matched ^ negate, close + 2),
            // Unterminated class → treat '[' literally.
            None => (c == '[', 1),
        }
    }

    fn helper(p: &[char], n: &[char]) -> bool {
        if p.is_empty() {
            return n.is_empty();
        }
        match p[0] {
            '*' => helper(&p[1..], n) || (!n.is_empty() && helper(p, &n[1..])),
            '?' => !n.is_empty() && helper(&p[1..], &n[1..]),
            '[' => {
                if n.is_empty() {
                    return false;
                }
                let (matched, consumed) = class_match(&p[1..], n[0]);
                matched && helper(&p[consumed..], &n[1..])
            }
            c => !n.is_empty() && n[0] == c && helper(&p[1..], &n[1..]),
        }
    }

    let p: Vec<char> = pattern.chars().collect();
    let n: Vec<char> = name.chars().collect();
    helper(&p, &n)
}

/// Filesystem glob mirroring `pathlib.Path.glob`: `*`/`?`/`[...]` match within a
/// path segment, `**` matches zero or more directories.
fn glob_paths(root: &Path, pattern: &str) -> Vec<PathBuf> {
    fn recurse(current: &Path, segments: &[&str], out: &mut Vec<PathBuf>) {
        let Some((seg, rest)) = segments.split_first() else {
            if current.exists() {
                out.push(current.to_path_buf());
            }
            return;
        };
        if *seg == "**" {
            // Zero directories: apply the rest here.
            recurse(current, rest, out);
            // One or more: descend keeping `**` in front.
            if let Ok(entries) = std::fs::read_dir(current) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if path.is_dir() {
                        recurse(&path, segments, out);
                    }
                }
            }
            return;
        }
        if let Ok(entries) = std::fs::read_dir(current) {
            for entry in entries.flatten() {
                let name = entry.file_name();
                if fnmatch_segment(seg, &name.to_string_lossy()) {
                    recurse(&entry.path(), rest, out);
                }
            }
        }
    }

    let segments: Vec<&str> = pattern.split('/').filter(|s| !s.is_empty()).collect();
    let mut out = Vec::new();
    recurse(root, &segments, &mut out);
    out.sort();
    out
}

/// Read a package name (`data["name"]`) as a non-empty string, or `None`.
fn read_package_name(data: &serde_json::Value) -> Option<String> {
    data.get("name")
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

/// The `packages:` globs from `pnpm-workspace.yaml`, if present. pnpm monorepos
/// declare their member packages here instead of package.json's `workspaces`
/// field; without reading it, every workspace-internal `@scope/pkg` import reads
/// as a third-party dependency. Other keys (`catalog:`, `catalogs:`) are ignored.
fn pnpm_workspace_patterns(repo_root: &Path) -> Vec<String> {
    #[derive(serde::Deserialize)]
    struct PnpmWorkspace {
        #[serde(default)]
        packages: Vec<String>,
    }
    read_text_lossy(&repo_root.join("pnpm-workspace.yaml"))
        .ok()
        .and_then(|text| serde_yaml::from_str::<PnpmWorkspace>(&text).ok())
        .map(|w| w.packages)
        .unwrap_or_default()
}

/// Resolve workspace glob `patterns` (npm or pnpm) to the `name` of each member
/// package.json under `repo_root`, inserting them into `out`.
fn insert_workspace_package_names(
    repo_root: &Path,
    patterns: &[String],
    out: &mut HashSet<String>,
) {
    for pattern in patterns {
        let glob = format!("{pattern}/package.json");
        for ws_pkg in glob_paths(repo_root, &glob) {
            if let Some(ws_name) = read_text_lossy(&ws_pkg)
                .ok()
                .and_then(|text| serde_json::from_str::<serde_json::Value>(&text).ok())
                .and_then(|data| read_package_name(&data))
            {
                out.insert(ws_name);
            }
        }
    }
}

/// `TypeScriptAdapter` — the language adapter for `.ts` / `.tsx` sources.
#[derive(Debug, Default)]
pub struct TypeScriptAdapter {
    noise: HashSet<String>,
}

impl TypeScriptAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Names the source binds to callable definitions — function/class
    /// declarations and variables bound to function values. Ambient
    /// (`declare …`) statements are skipped: they bind nothing locally.
    /// Feeds local-binding attestation: code calling what it defines is not
    /// foreign voice.
    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        let mut stack = vec![tree.root_node()];
        while let Some(node) = stack.pop() {
            if node.kind() == "ambient_declaration" {
                continue;
            }
            match node.kind() {
                "function_declaration" | "generator_function_declaration" | "class_declaration" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        out.insert(node_text(name, source).to_string());
                    }
                }
                "variable_declarator" => {
                    if let (Some(name), Some(rhs)) =
                        (node.child_by_field_name("name"), get_ts_rhs(node))
                    {
                        if TS_FUNCTION_VALUE_TYPES.contains(&rhs.kind())
                            && name.kind() == "identifier"
                        {
                            out.insert(node_text(name, source).to_string());
                        }
                    }
                }
                _ => {}
            }
            for c in children(node).into_iter().rev() {
                stack.push(c);
            }
        }
        out
    }

    /// Function/method definitions with their line ranges — the embeddable units
    /// for the semantic index. Covers `function`/generator declarations, class
    /// `method_definition`s, and function-valued `const`/`let` bindings (arrows,
    /// function expressions). Ambient (`declare`) blocks carry no bodies, so
    /// they're skipped.
    pub fn callable_bodies(&self, source: &str) -> Vec<super::CallableBody> {
        let tree = parse(source);
        let mut out = Vec::new();
        let mut stack = vec![tree.root_node()];
        while let Some(node) = stack.pop() {
            if node.kind() == "ambient_declaration" {
                continue;
            }
            let named = match node.kind() {
                "function_declaration" | "generator_function_declaration" | "method_definition" => {
                    node.child_by_field_name("name")
                }
                "variable_declarator" => match get_ts_rhs(node) {
                    Some(rhs)
                        if TS_FUNCTION_VALUE_TYPES.contains(&rhs.kind())
                            && node
                                .child_by_field_name("name")
                                .is_some_and(|n| n.kind() == "identifier") =>
                    {
                        node.child_by_field_name("name")
                    }
                    _ => None,
                },
                _ => None,
            };
            if let Some(name) = named {
                out.push(super::CallableBody {
                    symbol: node_text(name, source).to_string(),
                    start_line: node.start_position().row + 1,
                    end_line: node.end_position().row + 1,
                });
            }
            for c in children(node).into_iter().rev() {
                stack.push(c);
            }
        }
        out
    }

    /// Every locally bound value name — variable declarators (including
    /// destructuring patterns), function parameters, and import clauses (any
    /// specifier: importing a name binds it; whether the MODULE is in-voice
    /// is the import stage's question). Type annotations are skipped: their
    /// identifiers are types, not bindings.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        let mut stack = vec![tree.root_node()];
        while let Some(node) = stack.pop() {
            let binding_root = matches!(
                node.kind(),
                "variable_declarator" | "formal_parameters" | "catch_clause" | "import_clause"
            );
            if binding_root {
                let mut inner = vec![node];
                while let Some(n) = inner.pop() {
                    match n.kind() {
                        "type_annotation" | "type_arguments" | "type_parameters" => continue,
                        "identifier" | "shorthand_property_identifier_pattern" => {
                            out.insert(node_text(n, source).to_string());
                        }
                        // A declarator's value is an expression, not a binding.
                        _ if n.kind() == "variable_declarator" && n.id() != node.id() => {}
                        _ => {}
                    }
                    for c in children(n).into_iter().rev() {
                        if n.kind() == "variable_declarator"
                            && n.child_by_field_name("value").map(|v| v.id()) == Some(c.id())
                        {
                            continue;
                        }
                        inner.push(c);
                    }
                }
                continue;
            }
            for c in children(node).into_iter().rev() {
                stack.push(c);
            }
        }
        out
    }

    /// Names bound by imports from repo-internal (relative) specifiers —
    /// default imports, named imports (aliases win), and namespace imports.
    /// A callee the file imports from its own package neighbourhood is not
    /// foreign voice.
    pub fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut out = HashSet::new();
        for node in descendants(root) {
            if node.kind() != "import_statement" {
                continue;
            }
            let Some(src) = node.child_by_field_name("source") else {
                continue;
            };
            if src.kind() != "string" {
                continue;
            }
            let spec = strip_quotes(node_text(src, source));
            if !is_internal_specifier(spec) {
                continue;
            }
            for clause in children(node) {
                if clause.kind() != "import_clause" {
                    continue;
                }
                for item in descendants(clause) {
                    match item.kind() {
                        // Default import: `import X from './x'`.
                        "identifier"
                            if item.parent().map(|p| p.kind()) == Some("import_clause") =>
                        {
                            out.insert(node_text(item, source).to_string());
                        }
                        // Named import: alias if present, else the name.
                        "import_specifier" => {
                            let bound = item
                                .child_by_field_name("alias")
                                .or_else(|| item.child_by_field_name("name"));
                            if let Some(b) = bound {
                                out.insert(node_text(b, source).to_string());
                            }
                        }
                        // Namespace import: `import * as x from './x'`.
                        "namespace_import" => {
                            for c in children(item) {
                                if c.kind() == "identifier" {
                                    out.insert(node_text(c, source).to_string());
                                }
                            }
                        }
                        _ => {}
                    }
                }
            }
        }
        out
    }

    /// Non-relative module specifiers imported in `source` (import + require).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut mods: HashSet<String> = HashSet::new();
        for node in descendants(root) {
            if node.kind() != "import_statement" {
                continue;
            }
            if let Some(src) = node.child_by_field_name("source") {
                if src.kind() == "string" {
                    let spec = strip_quotes(node_text(src, source));
                    if !spec.is_empty() && !is_internal_specifier(spec) {
                        mods.insert(spec.to_string());
                    }
                }
            }
        }
        for spec in extract_require_imports(root, source) {
            mods.insert(spec);
        }
        mods
    }

    /// Like `extract_imports` but each specifier carries its `(spec, line,
    /// col_start, col_end)` span. Line 1-indexed; columns 0-indexed byte
    /// offsets covering the specifier text (quote skipped), end exclusive.
    /// Sorted by `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(root) {
            if node.kind() != "import_statement" {
                continue;
            }
            if let Some(src) = node.child_by_field_name("source") {
                if src.kind() == "string" {
                    let spec = strip_quotes(node_text(src, source));
                    if !spec.is_empty() && !is_internal_specifier(spec) {
                        let line = src.start_position().row + 1;
                        // Skip the opening quote so the underline lands on the spec.
                        let col_start = src.start_position().column + 1;
                        let col_end = col_start + spec.len();
                        out.push((spec.to_string(), line, col_start, col_end));
                    }
                }
            }
        }
        out.extend(extract_require_imports_with_spans(root, source));
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// Package names (own + workspaces) and tsconfig path-alias prefixes.
    ///
    /// tsconfig paths classification:
    /// - `"@/*"` → prefix `"@/"` (strip trailing `*`)
    /// - `"#lib"` (no glob) → exact `"#lib"`
    /// - wildcard elsewhere (`"@lib/*/tests"`) → skipped
    pub fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        let mut exact: HashSet<String> = HashSet::new();
        let mut prefixes: HashSet<String> = HashSet::new();

        let pkg_json = repo_root.join("package.json");
        if pkg_json.exists() {
            if let Some(data) = read_text_lossy(&pkg_json)
                .ok()
                .and_then(|text| serde_json::from_str::<serde_json::Value>(&text).ok())
            {
                if let Some(name) = read_package_name(&data) {
                    exact.insert(name);
                }
                let patterns = workspace_patterns(data.get("workspaces"));
                insert_workspace_package_names(repo_root, &patterns, &mut exact);
            }
        }

        // pnpm monorepos declare workspace members in pnpm-workspace.yaml, not
        // in package.json — read it too so their `@scope/pkg` names count as
        // repo-internal rather than foreign dependencies.
        let pnpm_patterns = pnpm_workspace_patterns(repo_root);
        insert_workspace_package_names(repo_root, &pnpm_patterns, &mut exact);

        let tsconfig = repo_root.join("tsconfig.json");
        if tsconfig.exists() {
            if let Some(tsdata) = read_text_lossy(&tsconfig)
                .ok()
                .and_then(|text| serde_json::from_str::<serde_json::Value>(&text).ok())
            {
                if let Some(paths) = tsdata
                    .get("compilerOptions")
                    .and_then(|c| c.get("paths"))
                    .and_then(|p| p.as_object())
                {
                    for key in paths.keys() {
                        let star_count = key.matches('*').count();
                        if star_count == 0 {
                            if !key.is_empty() {
                                exact.insert(key.clone());
                            }
                        } else if star_count == 1 && key.ends_with("/*") {
                            // "@/*" → prefix "@/"
                            let prefix = &key[..key.len() - 1];
                            if !prefix.is_empty() {
                                prefixes.insert(prefix.to_string());
                            }
                        }
                        // else: unsupported wildcard pattern → skipped.
                    }
                }
            }
        }

        RepoModules { exact, prefixes }
    }

    /// 1-indexed `(start_line, end_line)` spans for top-level sampleable units:
    /// function/class/interface/type-alias declarations and lexical/variable
    /// declarations whose RHS is arrow/function/class expression. `export`
    /// wrappers are unwrapped transparently.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut ranges: Vec<(usize, usize)> = Vec::new();
        for child in children(root) {
            let mut inner = child;
            if child.kind() == "export_statement" {
                for sub in children(child) {
                    if TS_SAMPLEABLE_TOP_LEVEL.contains(&sub.kind())
                        || matches!(sub.kind(), "lexical_declaration" | "variable_declaration")
                        || TS_FUNCTION_VALUE_TYPES.contains(&sub.kind())
                    {
                        inner = sub;
                        break;
                    }
                }
            }

            // Top-level declarations and bare function/class expressions both
            // contribute their own line span (Python keeps these as separate
            // branches; in Rust they collapse to one).
            if TS_SAMPLEABLE_TOP_LEVEL.contains(&inner.kind())
                || TS_FUNCTION_VALUE_TYPES.contains(&inner.kind())
            {
                ranges.push((inner.start_position().row + 1, inner.end_position().row + 1));
            } else if matches!(inner.kind(), "lexical_declaration" | "variable_declaration") {
                for decl_child in children(inner) {
                    if decl_child.kind() != "variable_declarator" {
                        continue;
                    }
                    if let Some(rhs) = get_ts_rhs(decl_child) {
                        if TS_FUNCTION_VALUE_TYPES.contains(&rhs.kind()) {
                            ranges.push((
                                decl_child.start_position().row + 1,
                                decl_child.end_position().row + 1,
                            ));
                        }
                    }
                }
            }
        }
        ranges
    }

    /// True if the file is overwhelmingly top-level data literals (threshold
    /// 0.65 of non-blank lines).
    pub fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        if source.is_empty() || source.trim().is_empty() {
            return false;
        }
        let tree = parse(source);
        let root = tree.root_node();

        let total_nonblank = splitlines(source)
            .iter()
            .filter(|line| !line.trim().is_empty())
            .count();
        if total_nonblank == 0 {
            return false;
        }

        let mut data_rows: HashSet<usize> = HashSet::new();
        collect_ts_data_rows(root, &mut data_rows);
        let ratio = (data_rows.len() as f64) / (total_nonblank as f64);
        ratio > threshold
    }

    /// 1-indexed line numbers covered by top-level data-literal declarations.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.is_empty() || source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_ts_data_rows(tree.root_node(), &mut rows);
        rows.into_iter().map(|r| r + 1).collect()
    }

    /// True if a comment in the first `HEADER_LINE_LIMIT` lines carries an
    /// auto-generation marker (case-insensitive), or a strong DO-NOT-EDIT
    /// marker within the first 10 lines.
    pub fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        if source.is_empty() {
            return false;
        }
        let tree = parse(source);
        let root = tree.root_node();
        for node in descendants(root) {
            if node.kind() != "comment" {
                continue;
            }
            let line_index = node.start_position().row;
            if line_index >= HEADER_LINE_LIMIT {
                continue;
            }
            let text = node_text(node, source);
            if autogenerated::comment_indicates_generated(
                line_index,
                text,
                HEADER_LINE_LIMIT,
                markers,
            ) {
                return true;
            }
        }
        false
    }

    /// 1-indexed line numbers covered by comments (line and block). TypeScript
    /// has no docstring concept; all prose is in comments.
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(root) {
            if node.kind() == "comment" {
                let start = node.start_position().row + 1;
                let end = node.end_position().row + 1;
                for r in start..=end {
                    rows.insert(r);
                }
            }
        }
        rows
    }

    /// Dotted-callee signatures for every call/new expression in `source`
    /// (non-`None` only). `[]` on empty source. Not on the `LanguageAdapter`
    /// trait — an inherent method mirroring `typescript.py`'s `extract_callees`.
    pub fn extract_callees(&self, source: &str) -> Vec<String> {
        if source.trim().is_empty() {
            return Vec::new();
        }
        let tree = parse(source);
        let root = tree.root_node();
        let mut out: Vec<String> = Vec::new();
        for node in descendants(root) {
            if TS_CALL_TYPES.contains(&node.kind()) {
                if let Some(callee) = extract_ts_callee(node, source) {
                    out.push(callee);
                }
            }
        }
        out
    }

    /// TS/JS reserved words, literals, and implicit identifiers filtered out of
    /// the repo-wide identifier vocabulary.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

impl LanguageAdapter for TypeScriptAdapter {
    fn language(&self) -> Language {
        Language::Typescript
    }
    fn extract_imports(&self, source: &str) -> HashSet<String> {
        TypeScriptAdapter::extract_imports(self, source)
    }
    fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        TypeScriptAdapter::extract_imports_with_spans(self, source)
    }
    fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        TypeScriptAdapter::resolve_repo_modules(self, repo_root)
    }
    fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        TypeScriptAdapter::is_data_dominant(self, source, threshold)
    }
    fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        TypeScriptAdapter::data_literal_lines(self, source)
    }
    fn callable_definitions(&self, source: &str) -> HashSet<String> {
        TypeScriptAdapter::callable_definitions(self, source)
    }
    fn callable_bodies(&self, source: &str) -> Vec<super::CallableBody> {
        TypeScriptAdapter::callable_bodies(self, source)
    }
    fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        TypeScriptAdapter::internal_import_bindings(self, source)
    }
    fn value_bindings(&self, source: &str) -> HashSet<String> {
        TypeScriptAdapter::value_bindings(self, source)
    }
    fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        TypeScriptAdapter::is_auto_generated(self, source, markers)
    }
    fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        TypeScriptAdapter::enumerate_sampleable_ranges(self, source)
    }
    fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        TypeScriptAdapter::prose_line_ranges(self, source)
    }
    fn identifier_noise(&self) -> &HashSet<String> {
        TypeScriptAdapter::identifier_noise(self)
    }
    fn line_comment_prefix(&self) -> &'static str {
        "//"
    }
}

/// TypeScript / JavaScript reserved words + literals + implicit identifiers.
const NOISE: &[&str] = &[
    "abstract",
    "any",
    "as",
    "asserts",
    "assert",
    "async",
    "await",
    "boolean",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "constructor",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "from",
    "function",
    "get",
    "global",
    "if",
    "implements",
    "import",
    "in",
    "infer",
    "instanceof",
    "interface",
    "is",
    "keyof",
    "let",
    "module",
    "namespace",
    "never",
    "new",
    "null",
    "number",
    "object",
    "of",
    "package",
    "private",
    "protected",
    "public",
    "readonly",
    "require",
    "return",
    "satisfies",
    "set",
    "static",
    "string",
    "super",
    "switch",
    "symbol",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "unique",
    "unknown",
    "var",
    "void",
    "while",
    "with",
    "yield",
    "arguments",
];

#[cfg(test)]
mod tests;
