//! `argot describe-voice` — generate a human-readable STYLE.md from the learned
//! voice. Onboarding companion for new contributors and LLM agents: a
//! description of how the repo *actually* writes, grounded in its own history
//! rather than aspirational rules.

use std::path::PathBuf;
use std::process::ExitCode;

use argot_core::inspect::{inspect_model, LanguageModelView, ModelReport};

/// Callees shown per cluster in the generated guide.
pub const DEFAULT_TOP: usize = 8;

pub fn run_describe_voice(repo: PathBuf, top: usize, out: Option<PathBuf>) -> ExitCode {
    let report = match inspect_model(&repo, top) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("error: {e}");
            return ExitCode::from(2);
        }
    };
    let md = render_style_md(&report);
    match out {
        Some(path) => match std::fs::write(&path, md) {
            Ok(()) => {
                println!("Wrote {}", path.display());
                ExitCode::SUCCESS
            }
            Err(e) => {
                eprintln!("error: {e}");
                ExitCode::from(2)
            }
        },
        None => {
            print!("{md}");
            ExitCode::SUCCESS
        }
    }
}

/// Render the model report as a Markdown style guide. Pure — testable on a
/// hand-built [`ModelReport`].
pub fn render_style_md(report: &ModelReport) -> String {
    use std::fmt::Write as _;
    let mut out = String::new();

    let _ = writeln!(out, "# Voice of this repository");
    let _ = writeln!(out);
    match &report.manifest {
        Some(m) => {
            let _ = writeln!(
                out,
                "_Generated by `argot describe-voice` from {} files ({} lines). Model `{}`._",
                m.corpus_files, m.corpus_lines, m.model_hash
            );
        }
        None => {
            let _ = writeln!(out, "_Generated by `argot describe-voice`._");
        }
    }
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "This is **descriptive, not prescriptive**: argot reports how this repo \
tends to write, learned from its own git history — not a style it should adopt. \
Code that reaches for names absent below will read as *out of voice*."
    );
    let _ = writeln!(out);

    if report.languages.is_empty() {
        let _ = writeln!(out, "_No fitted model yet — run `argot fit` first._");
        return out;
    }

    for (lang, view) in &report.languages {
        let _ = writeln!(out, "## {lang}");
        let _ = writeln!(out);
        render_language(&mut out, view);
        let _ = writeln!(out);
    }
    out
}

fn render_language(out: &mut String, view: &LanguageModelView) {
    use std::fmt::Write as _;

    // Familiar imports.
    if view.familiar_imports.is_empty() {
        let _ = writeln!(out, "**Imports.** No import surface was recorded.");
    } else {
        let shown = 20.min(view.familiar_imports.len());
        let list = view.familiar_imports[..shown]
            .iter()
            .map(|m| format!("`{m}`"))
            .collect::<Vec<_>>()
            .join(", ");
        let more = view.familiar_imports.len().saturating_sub(shown);
        let tail = if more > 0 {
            format!(" (+{more} more)")
        } else {
            String::new()
        };
        let _ = writeln!(
            out,
            "**Familiar imports.** The repo draws on {list}{tail}. An import \
outside this set is foreign and gets flagged."
        );
    }
    let _ = writeln!(out);

    // Typical calls per cluster.
    let _ = writeln!(
        out,
        "**Typical calls by area.** Files group by what they call; each group's \
most-used callees:"
    );
    let _ = writeln!(out);
    for cl in &view.clusters {
        if cl.top_callees.is_empty() {
            continue;
        }
        let strongest = cl.top_callees[0].1;
        // A callee used in a large share of a cluster's files is a strong tell.
        let confidence = if cl.files > 0 && strongest * 2 >= cl.files {
            "strong"
        } else {
            "mild"
        };
        let names = cl
            .top_callees
            .iter()
            .map(|(name, count)| format!("`{name}` ({count})"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "- **Group {}** ({} files, {confidence} tendency): {names}",
            cl.id, cl.files
        );
    }
    let _ = writeln!(out);

    // Red-flag summary.
    let _ = writeln!(
        out,
        "**Red flags.** {} distinct callees are attested across {} corpus files. \
A hunk that calls something absent from its area's set above — or imports \
outside the familiar set — is what argot flags as out of voice.",
        view.attested_callees, view.corpus_files
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use argot_core::inspect::{ClusterView, ManifestView};
    use std::collections::BTreeMap;

    fn sample_report() -> ModelReport {
        let mut languages = BTreeMap::new();
        languages.insert(
            "python".to_string(),
            LanguageModelView {
                threshold: 4.2,
                model_hash: "abc".to_string(),
                n_cal: 100,
                distinct_tokens: 5000,
                total_tokens: 200_000,
                attested_callees: 1090,
                corpus_files: 500,
                familiar_imports: vec!["fastapi".to_string(), "pydantic".to_string()],
                clusters: vec![ClusterView {
                    id: "0".to_string(),
                    files: 100,
                    top_callees: vec![("app.get".to_string(), 90), ("Depends".to_string(), 40)],
                }],
            },
        );
        ModelReport {
            path: ".".to_string(),
            manifest: Some(ManifestView {
                manifest_version: 1,
                config_version: 3,
                model_hash: "deadbeef".to_string(),
                scorer_config_hash: "cafe".to_string(),
                fit_commit_sha: "sha".to_string(),
                fit_timestamp: "t".to_string(),
                corpus_files: 500,
                corpus_lines: 30000,
            }),
            languages,
        }
    }

    #[test]
    fn style_md_surfaces_imports_clusters_and_confidence() {
        let md = render_style_md(&sample_report());
        assert!(md.contains("# Voice of this repository"));
        assert!(md.contains("## python"));
        assert!(md.contains("`fastapi`"));
        assert!(md.contains("`app.get` (90)"));
        // app.get is in 90 of 100 files → strong tendency.
        assert!(md.contains("strong tendency"));
        assert!(md.contains("Model `deadbeef`"));
    }

    #[test]
    fn empty_model_reports_no_fit() {
        let report = ModelReport {
            path: ".".to_string(),
            manifest: None,
            languages: BTreeMap::new(),
        };
        let md = render_style_md(&report);
        assert!(md.contains("run `argot fit`"));
    }
}
