# engine/argot/research/signal/phase14/calibration/random_hunk_sampler.py
"""Random hunk sampler for calibration corpus generation.

Finds top-level Python function / class definitions with at least MIN_BODY_LINES
lines and samples n of them uniformly at random using a fixed numpy seed.
"""

from __future__ import annotations

import ast
from pathlib import Path

import numpy as np

from argot.research.signal.phase14.filters.autogenerated import is_auto_generated
from argot.research.signal.phase14.filters.data_dominant import is_data_dominant

MIN_BODY_LINES: int = 5

_DEFAULT_EXCLUDE_DIRS: frozenset[str] = frozenset(
    {
        "test",
        "tests",
        "doc",
        "docs",
        "examples",
        "example",
        "migrations",
        "migration",
        "benchmarks",
        "benchmark",
        "fixtures",
        "scripts",
        "build",
        "dist",
        "__pycache__",
        ".git",
        ".tox",
        ".eggs",
    }
)


def _is_excluded(path: Path, source_dir: Path, exclude_dirs: frozenset[str]) -> bool:
    try:
        rel = path.relative_to(source_dir)
    except ValueError:
        return True
    for part in rel.parts[:-1]:
        if part in exclude_dirs or part.startswith("test"):
            return True
    name = rel.name
    return name.startswith("test_") or name == "conftest.py"


def collect_candidates(
    source_dir: Path,
    *,
    exclude_dirs: frozenset[str] | None = None,
    exclude_auto_generated: bool = True,
    exclude_data_dominant: bool = True,
) -> list[str]:
    """Return all qualifying hunk strings from source_dir.

    A qualifying hunk is a top-level (module-level) FunctionDef, AsyncFunctionDef,
    or ClassDef with at least MIN_BODY_LINES lines between its first and last line.

    Args:
        exclude_auto_generated: When True (default), skip files whose header
            contains an auto-generation marker.  Pass False to include them
            (useful for testing the filter itself).
        exclude_data_dominant: When True (default), skip files whose content is
            overwhelmingly static data literals (e.g. locale string tables).
            Pass False to include them.
    """
    excl = exclude_dirs if exclude_dirs is not None else _DEFAULT_EXCLUDE_DIRS
    hunks: list[str] = []

    for py_file in sorted(source_dir.rglob("*.py")):
        if _is_excluded(py_file, source_dir, excl):
            continue
        try:
            source = py_file.read_text(encoding="utf-8", errors="replace")
            tree = ast.parse(source)
        except SyntaxError:
            continue

        if exclude_auto_generated and is_auto_generated(source):
            continue

        if exclude_data_dominant and is_data_dominant(source):
            continue

        lines = source.splitlines()
        for node in ast.iter_child_nodes(tree):
            if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
                continue
            start = node.lineno
            end = node.end_lineno
            if end is None:
                continue
            if (end - start) < MIN_BODY_LINES:
                continue
            hunks.append("\n".join(lines[start - 1 : end]))

    return hunks


def sample_hunks(
    source_dir: Path,
    n: int,
    seed: int,
    *,
    exclude_dirs: frozenset[str] | None = None,
    exclude_auto_generated: bool = True,
    exclude_data_dominant: bool = True,
) -> list[str]:
    """Sample n hunk strings from source_dir using a fixed numpy RNG seed.

    Raises:
        ValueError: if fewer than n qualifying hunks exist in source_dir.
    """
    candidates = collect_candidates(
        source_dir,
        exclude_dirs=exclude_dirs,
        exclude_auto_generated=exclude_auto_generated,
        exclude_data_dominant=exclude_data_dominant,
    )
    if len(candidates) < n:
        raise ValueError(
            f"Only {len(candidates)} qualifying hunks found in {source_dir!r}, "
            f"cannot sample n={n}. Reduce n or expand source_dir."
        )
    rng = np.random.default_rng(seed)
    indices = rng.choice(len(candidates), size=n, replace=False)
    return [candidates[int(i)] for i in sorted(indices)]


def sample_hunks_disjoint(
    source_dir: Path,
    n_cal: int,
    n_ctrl: int,
    seed: int,
    *,
    exclude_dirs: frozenset[str] | None = None,
    exclude_auto_generated: bool = True,
    exclude_data_dominant: bool = True,
) -> tuple[list[str], list[str]]:
    """Sample two disjoint hunk sets from source_dir using a fixed numpy RNG seed.

    Shuffles all candidates with `seed`, then splits:
      - cal_hunks  = first n_cal elements
      - ctrl_hunks = next n_ctrl elements (index n_cal … n_cal+n_ctrl−1)

    The two sets are guaranteed disjoint by construction.

    Returns:
        (cal_hunks, ctrl_hunks)

    Raises:
        ValueError: if fewer than n_cal + n_ctrl qualifying hunks exist.
    """
    candidates = collect_candidates(
        source_dir,
        exclude_dirs=exclude_dirs,
        exclude_auto_generated=exclude_auto_generated,
        exclude_data_dominant=exclude_data_dominant,
    )
    needed = n_cal + n_ctrl
    if len(candidates) < needed:
        raise ValueError(
            f"Only {len(candidates)} qualifying hunks found in {source_dir!r}, "
            f"cannot sample n_cal={n_cal} + n_ctrl={n_ctrl}={needed}. "
            f"Reduce counts or expand source_dir."
        )
    rng = np.random.default_rng(seed)
    perm = rng.permutation(len(candidates))
    cal_indices = perm[:n_cal]
    ctrl_indices = perm[n_cal : n_cal + n_ctrl]
    return (
        [candidates[int(i)] for i in cal_indices],
        [candidates[int(i)] for i in ctrl_indices],
    )
