# engine/argot/research/signal/phase14/adapters/python_adapter.py
"""PythonAdapter — wraps existing Python-specific logic behind LanguageAdapter."""

from __future__ import annotations

import ast
from pathlib import Path

from argot.scoring.adapters.language_adapter import RepoModules
from argot.scoring.filters.autogenerated import (
    is_auto_generated as _is_auto_generated,
)
from argot.scoring.filters.data_dominant import is_data_dominant
from argot.scoring.parsers import PythonTreeSitterParser

HEADER_LINE_LIMIT: int = 20


class PythonAdapter:
    """LanguageAdapter implementation for Python source files."""

    file_extensions: frozenset[str] = frozenset({".py"})

    def __init__(self) -> None:
        self._parser = PythonTreeSitterParser()

    def extract_imports(self, source: str) -> set[str]:
        """Return top-level module names imported in *source* (non-relative only)."""
        return set(self._parser.extract_imports(source))

    def resolve_repo_modules(self, repo_root: Path) -> RepoModules:  # noqa: ARG002
        """Python internal modules are discovered via extract_imports in fit(); return empty."""
        return RepoModules(exact=frozenset(), prefixes=frozenset())

    def enumerate_sampleable_ranges(self, source: str) -> list[tuple[int, int]]:
        """Return 1-indexed (start_line, end_line) spans for module-level definitions.

        Covers FunctionDef, AsyncFunctionDef, ClassDef at module scope only.
        Returns [] on SyntaxError.
        """
        try:
            tree = ast.parse(source)
        except SyntaxError:
            return []
        ranges: list[tuple[int, int]] = []
        for node in ast.iter_child_nodes(tree):
            if (
                isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef)
                and node.end_lineno is not None
            ):
                ranges.append((node.lineno, node.end_lineno))
        return ranges

    def is_data_dominant(self, source: str, threshold: float = 0.65) -> bool:
        return is_data_dominant(source, threshold)

    def is_auto_generated(self, source: str) -> bool:
        return _is_auto_generated(source, head_lines=HEADER_LINE_LIMIT)

    def prose_line_ranges(self, source: str) -> frozenset[int]:
        return self._parser.prose_line_ranges(source)
