use super::*;

#[test]
fn callable_bodies_covers_funcs_and_methods() {
    let a = GoAdapter::new();
    let src = "package p\n\nfunc Add(a, b int) int {\n\tsum := a + b\n\treturn sum\n}\n\nfunc (r Repo) Save(x int) error {\n\tr.store(x)\n\treturn nil\n}\n";
    let names: Vec<String> = a
        .callable_bodies(src)
        .into_iter()
        .map(|b| b.symbol)
        .collect();
    assert!(names.contains(&"Add".to_string()), "{names:?}");
    assert!(names.contains(&"Save".to_string()), "{names:?}");
}

#[test]
fn resolve_repo_modules_reads_go_mod_module_paths() {
    let dir = std::env::temp_dir().join(format!("argot_go_mod_test_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(dir.join("sub")).unwrap();
    std::fs::write(
        dir.join("go.mod"),
        "module github.com/acme/tool/v2\n\ngo 1.22\n",
    )
    .unwrap();
    std::fs::write(dir.join("sub/go.mod"), "module github.com/acme/helper\n").unwrap();

    let modules = GoAdapter::new().resolve_repo_modules(&dir);
    // The `/v2` major-version suffix folds, so the repo's own module keys the
    // same whether an internal import writes the v1 or v2 form.
    assert!(modules.exact.contains("github.com/acme/tool"));
    assert!(modules.prefixes.contains("github.com/acme/tool/"));
    assert!(!modules.exact.contains("github.com/acme/tool/v2"));
    assert!(modules.prefixes.contains("github.com/acme/helper/"));
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn major_version_suffix_folds_but_api_versions_do_not() {
    let adapter = GoAdapter::new();
    // A `/v2` module import folds to the same key as its v1 form, so a version
    // bump is not read as a brand-new dependency.
    let v2 =
        adapter.extract_imports("package main\n\nimport \"go.mongodb.org/mongo-driver/v2/bson\"\n");
    assert!(v2.contains("go.mongodb.org/mongo-driver/bson"), "{v2:?}");
    assert!(!v2.contains("go.mongodb.org/mongo-driver/v2/bson"));

    // v1 and mixed API-version segments are never major-version markers.
    assert_eq!(
        fold_go_major_version("k8s.io/api/autoscaling/v1"),
        "k8s.io/api/autoscaling/v1"
    );
    assert_eq!(
        fold_go_major_version("k8s.io/api/apps/v2beta1"),
        "k8s.io/api/apps/v2beta1"
    );
    // A genuine `/v2` API surface folds to a *different* key than the attested
    // v1, so it still reads as new (no false negative).
    assert_eq!(
        fold_go_major_version("k8s.io/api/autoscaling/v2"),
        "k8s.io/api/autoscaling"
    );
    assert_eq!(fold_go_major_version("fmt"), "fmt");
    assert_eq!(fold_go_major_version("github.com/x/y"), "github.com/x/y");
}

#[test]
fn imports_are_full_paths() {
    let adapter = GoAdapter::new();
    let src = "package main\n\nimport (\n\t\"fmt\"\n\t\"github.com/x/y\"\n)\n";
    let imports = adapter.extract_imports(src);
    assert!(imports.contains("fmt"));
    assert!(imports.contains("github.com/x/y"));
    // Full path, not split on '/'.
    assert!(!imports.contains("github.com"));
}

#[test]
fn aliased_import_path_still_extracts() {
    let adapter = GoAdapter::new();
    let src = "package main\n\nimport f \"fmt\"\n";
    let imports = adapter.extract_imports(src);
    assert!(imports.contains("fmt"));
}

#[test]
fn callable_definitions_cover_funcs_methods_and_func_literals() {
    let adapter = GoAdapter::new();
    let src = "package main\n\nfunc Foo() {}\n\nfunc (r Recv) Bar() {}\n\nvar Baz = func() {}\n";
    let defs = adapter.callable_definitions(src);
    assert!(defs.contains("Foo"));
    assert!(defs.contains("Bar"));
    assert!(defs.contains("Baz"));
}

#[test]
fn value_bindings_cover_short_var_and_params() {
    let adapter = GoAdapter::new();
    let src = "package main\n\nfunc f(a int, b string) {\n\tx := a\n\treturn\n}\n";
    let binds = adapter.value_bindings(src);
    assert!(binds.contains("a"));
    assert!(binds.contains("b"));
    assert!(binds.contains("x"));
}

#[test]
fn sampleable_ranges_are_top_level_functions() {
    let adapter = GoAdapter::new();
    let src = "package main\n\nfunc a() {\n\treturn\n}\n\nfunc b() {\n\treturn\n}\n";
    let ranges = adapter.enumerate_sampleable_ranges(src);
    assert_eq!(ranges.len(), 2);
}

#[test]
fn generated_header_is_detected() {
    let adapter = GoAdapter::new();
    let src = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage main\n\nfunc F() {}\n";
    assert!(adapter.is_auto_generated(src, &crate::test_support::generated_markers()));
    let hand = "// A normal comment.\n\npackage main\n\nfunc F() {}\n";
    assert!(!adapter.is_auto_generated(hand, &crate::test_support::generated_markers()));
}

#[test]
fn top_level_data_tables_are_data_dominant() {
    let adapter = GoAdapter::new();
    let src = "package main\n\nvar Cities = []string{\n\t\"a\",\n\t\"b\",\n\t\"c\",\n\t\"d\",\n\t\"e\",\n}\n";
    assert!(adapter.is_data_dominant(src, 0.65));
    assert!(!adapter.data_literal_lines(src).is_empty());
}

#[test]
fn code_is_not_data_dominant() {
    let adapter = GoAdapter::new();
    let src = "package main\n\nfunc add(a, b int) int {\n\treturn a + b\n}\n";
    assert!(!adapter.is_data_dominant(src, 0.65));
}

#[test]
fn go_has_no_relative_imports() {
    let adapter = GoAdapter::new();
    let src = "package main\n\nimport \"github.com/x/y\"\n";
    assert!(adapter.internal_import_bindings(src).is_empty());
}

#[test]
fn identifier_noise_contains_keywords_and_builtins() {
    let adapter = GoAdapter::new();
    assert!(adapter.identifier_noise().contains("func"));
    assert!(adapter.identifier_noise().contains("append"));
    assert_eq!(adapter.identifier_noise().len(), NOISE.len());
}
