//! C language adapter.
//!
//! Behaviour-preserving sibling of `python.rs` / `typescript.rs`: the same
//! manual `TreeCursor` / `child_by_field_name` traversal style over the pinned
//! tree-sitter-c grammar.
//!
//! C is structurally poorer than the brace languages for voice signal:
//! - There is no exception-handling construct, so the except-ratio primitive
//!   is undefined for C (handled in that scorer, not here).
//! - There is no object/method receiver — a `call_expression`'s callee is a
//!   bare function name (or a `field_expression` for a function-pointer call
//!   such as `obj->fn()`). We build a dotted callee for the latter but keep it
//!   simple; the call-receiver signal is inherently weaker for C. We lean on
//!   `#include` imports and local definitions instead.
//!
//! Import model: `#include <stdio.h>` (a `system_lib_string`) is an
//! external/system module — its module name is the header path up to the first
//! `/` (`stdio.h` stays whole; `openssl/ssl.h` → `openssl`). `#include "foo.h"`
//! (a `string_literal`) is repo-internal and is surfaced through
//! `internal_import_bindings`, not `extract_imports` — mirroring how the
//! TypeScript adapter excludes relative specifiers.

use std::collections::HashSet;
use std::path::Path;

use tree_sitter::{Node, Tree};

use super::{Language, LanguageAdapter, RepoModules};
use crate::text::splitlines;

const HEADER_LINE_LIMIT: usize = 20;
const DATA_DOMINANT_THRESHOLD: f64 = 0.65;

/// Value node kinds that count as literal data inside an `initializer_list`.
const C_VALUE_LITERAL_TYPES: &[&str] = &[
    "number_literal",
    "string_literal",
    "char_literal",
    "concatenated_string",
    "true",
    "false",
    "null",
    "initializer_list",
    "initializer_pair",
];

// Auto-generation markers — the same generic set the other adapters use.
const GENERIC_MARKERS: &[&str] = &[
    "auto generated",
    "auto-generated",
    "autogenerated",
    "auto_generated",
    "automatically generated",
    "automatically-generated",
    "automatically created",
    "machine generated",
    "machine-generated",
    "machine created",
    "programmatically generated",
    "computer generated",
    "computer-generated",
    "generated by",
    "generated file",
    "generated code",
    "generated from",
    "generated source",
    "this file was generated",
    "this file is generated",
    "this file has been generated",
    "this file is auto-generated",
    "this file is autogenerated",
    "this file was automatically",
    "this file is automatically",
    "this is a generated file",
    "this file was created by",
    "this module is generated",
    "@generated",
    "@autogenerated",
    "@auto-generated",
    "@ generated",
];
const DO_NOT_EDIT_MARKERS: &[&str] = &[
    "do not edit",
    "do not edit this file",
    "do not modify",
    "do not modify this file",
    "do not modify by hand",
    "do not change this file",
    "please do not edit",
    "please do not modify",
    "source of this file is",
];
const TOOL_MARKERS: &[&str] = &[
    "generated by protoc",
    "generated by the protocol buffer compiler",
    "generated by flex",
    "generated by bison",
    "generated by yacc",
    "generated by lex",
    "generated by re2c",
    "generated by gperf",
    "output of",
    "produced by",
    "compiled from",
];
/// "do not edit" / "do not modify" in the first 10 lines suffice on their own.
const STRONG_FIRST_10_MARKERS: &[&str] = &["do not edit", "do not modify"];

/// Parse C `source` into a tree-sitter `Tree` (reused per-thread parser).
fn parse(source: &str) -> Tree {
    crate::scoring::ts_parse::parse(source, Language::C)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    for child in node.children(&mut cursor) {
        out.push(child);
        go(child, &mut out);
    }
    out
}

/// Direct children of `node` as a `Vec`.
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

/// Direct children of `node` whose field name is `field` (a declaration can
/// carry several `declarator` fields, which `child_by_field_name` cannot
/// express — hence the manual cursor walk).
fn field_children<'a>(node: Node<'a>, field: &str) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    if cursor.goto_first_child() {
        loop {
            if cursor.field_name() == Some(field) {
                out.push(cursor.node());
            }
            if !cursor.goto_next_sibling() {
                break;
            }
        }
    }
    out
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// Strip the surrounding `<...>` from a `system_lib_string` node's text.
fn strip_angle(text: &str) -> &str {
    let b = text.as_bytes();
    if b.len() >= 2 && b[0] == b'<' && b[b.len() - 1] == b'>' {
        &text[1..text.len() - 1]
    } else {
        text
    }
}

/// Strip surrounding double quotes from a `string_literal` node's text.
fn strip_quotes(text: &str) -> &str {
    let b = text.as_bytes();
    if b.len() >= 2 && b[0] == b'"' && b[b.len() - 1] == b'"' {
        &text[1..text.len() - 1]
    } else {
        text
    }
}

/// External-module name for a `<...>` include: the header path up to the first
/// `/` (`stdio.h` stays whole; `openssl/ssl.h` → `openssl`).
fn system_module(header: &str) -> &str {
    header.split('/').next().unwrap_or(header)
}

/// Base identifier of a quoted header path: the last path segment without its
/// extension (`net/conn.h` → `conn`, `foo.h` → `foo`).
fn header_base(header: &str) -> &str {
    let last = header.rsplit('/').next().unwrap_or(header);
    match last.rfind('.') {
        Some(i) if i > 0 => &last[..i],
        _ => last,
    }
}

/// `(is_system, header_text)` for a `preproc_include` `path` node, or `None`.
fn include_path(path: Node, source: &str) -> Option<(bool, String)> {
    match path.kind() {
        "system_lib_string" => Some((true, strip_angle(node_text(path, source)).to_string())),
        "string_literal" => Some((false, strip_quotes(node_text(path, source)).to_string())),
        _ => None,
    }
}

/// Drill through pointer/array/parenthesized declarators to the innermost
/// `function_declarator`, then return its declared name — used for both
/// `function_definition`s and top-level prototype `declaration`s.
fn declared_function_name(decl: Node, source: &str) -> Option<String> {
    let mut node = decl;
    loop {
        match node.kind() {
            "function_declarator" => {
                let inner = node.child_by_field_name("declarator")?;
                return plain_identifier(inner, source);
            }
            "pointer_declarator" | "array_declarator" | "parenthesized_declarator" => {
                node = node.child_by_field_name("declarator")?;
            }
            _ => return None,
        }
    }
}

/// The identifier a plain (non-function) declarator ultimately binds, drilling
/// through `init_declarator` / pointer / array / parenthesized wrappers.
/// Returns `None` for a `function_declarator` (that is a callable, not a value).
fn plain_identifier(decl: Node, source: &str) -> Option<String> {
    let mut node = decl;
    loop {
        match node.kind() {
            "identifier" | "field_identifier" | "type_identifier" => {
                return Some(node_text(node, source).to_string());
            }
            "init_declarator"
            | "pointer_declarator"
            | "array_declarator"
            | "parenthesized_declarator" => {
                node = node.child_by_field_name("declarator")?;
            }
            _ => return None,
        }
    }
}

/// True if ≥80% of an `initializer_list`'s immediate named values are literal
/// data (or nested initializer lists). Empty lists return true (conservative).
fn is_initializer_literal_dominant(node: Node) -> bool {
    let values: Vec<Node> = children(node)
        .into_iter()
        .filter(|c| c.is_named())
        .collect();
    if values.is_empty() {
        return true;
    }
    let literal = values
        .iter()
        .filter(|v| C_VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal as f64) / (values.len() as f64) >= 0.8
}

/// Add row spans (0-indexed) of top-level data-literal declarations to `rows` —
/// `T name[] = { ... };` where the initializer is literal-dominant.
fn collect_c_data_rows(root: Node, rows: &mut HashSet<usize>) {
    for child in children(root) {
        if child.kind() != "declaration" {
            continue;
        }
        for decl in field_children(child, "declarator") {
            if decl.kind() != "init_declarator" {
                continue;
            }
            let Some(value) = decl.child_by_field_name("value") else {
                continue;
            };
            if value.kind() == "initializer_list" && is_initializer_literal_dominant(value) {
                for r in child.start_position().row..=child.end_position().row {
                    rows.insert(r);
                }
            }
        }
    }
}

/// Build the dotted callee for a `call_expression`, or `None` when the chain
/// bottoms out at something that is neither an identifier nor a nested call.
fn extract_c_callee(call_node: Node, src: &[u8]) -> Option<String> {
    let mut callee = call_node.child_by_field_name("function")?;
    let mut parts: Vec<String> = Vec::new();
    while callee.kind() == "field_expression" {
        let field = callee.child_by_field_name("field")?;
        let arg = callee.child_by_field_name("argument")?;
        parts.insert(0, byte_text(field, src));
        callee = arg;
    }
    if callee.kind() == "identifier" {
        parts.insert(0, byte_text(callee, src));
        Some(parts.join("."))
    } else if callee.kind() == "call_expression" {
        parts.insert(0, "<call>".to_string());
        Some(parts.join("."))
    } else {
        None
    }
}

fn byte_text(node: Node, src: &[u8]) -> String {
    let r = node.byte_range();
    if r.is_empty() {
        String::new()
    } else {
        String::from_utf8_lossy(&src[r]).into_owned()
    }
}

/// `CAdapter` — the language adapter for `.c` / `.h` sources.
#[derive(Debug, Default)]
pub struct CAdapter {
    noise: HashSet<String>,
}

impl CAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// External (`<...>`) module names imported via `#include`. Quoted
    /// (`"..."`) includes are repo-internal and are excluded here (they surface
    /// through `internal_import_bindings`).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "preproc_include" {
                continue;
            }
            let Some(path) = node.child_by_field_name("path") else {
                continue;
            };
            if let Some((true, header)) = include_path(path, source) {
                let module = system_module(&header);
                if !module.is_empty() {
                    out.insert(module.to_string());
                }
            }
        }
        out
    }

    /// Like `extract_imports` but each module carries its `(spec, line,
    /// col_start, col_end)` span. Line 1-indexed; columns 0-indexed byte
    /// offsets covering the module text (skipping the opening `<`).
    /// Sorted by `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "preproc_include" {
                continue;
            }
            let Some(path) = node.child_by_field_name("path") else {
                continue;
            };
            if let Some((true, header)) = include_path(path, source) {
                let module = system_module(&header).to_string();
                if module.is_empty() {
                    continue;
                }
                let line = path.start_position().row + 1;
                // Skip the opening `<` so the underline lands on the module.
                let col_start = path.start_position().column + 1;
                let col_end = col_start + module.len();
                out.push((module, line, col_start, col_end));
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// C has no package manifest with owned module names — internal neighbours
    /// are discovered from quoted includes at fit time, so there are no
    /// exact/prefix rules (mirrors the Python adapter).
    pub fn resolve_repo_modules(&self, _repo_root: &Path) -> RepoModules {
        RepoModules::default()
    }

    /// Names the source binds to callable definitions — `function_definition`
    /// names, top-level prototype `declaration`s, `typedef` names, and named
    /// `struct` specifiers. Feeds local-binding attestation: code calling what
    /// it defines is not foreign voice.
    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "function_definition" => {
                    if let Some(decl) = node.child_by_field_name("declarator") {
                        if let Some(name) = declared_function_name(decl, source) {
                            out.insert(name);
                        }
                    }
                }
                "declaration" => {
                    for decl in field_children(node, "declarator") {
                        if let Some(name) = declared_function_name(decl, source) {
                            out.insert(name);
                        }
                    }
                }
                "type_definition" => {
                    for decl in field_children(node, "declarator") {
                        if decl.kind() == "type_identifier" {
                            out.insert(node_text(decl, source).to_string());
                        }
                    }
                }
                "struct_specifier" | "union_specifier" | "enum_specifier" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        out.insert(node_text(name, source).to_string());
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// Names bound by repo-internal (quoted) includes: the header base
    /// identifier (`#include "net/conn.h"` → `conn`). C includes bind no
    /// identifiers we can name precisely, so this is a deliberately weak proxy
    /// marking the `"..."` neighbourhood as not-foreign.
    pub fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "preproc_include" {
                continue;
            }
            let Some(path) = node.child_by_field_name("path") else {
                continue;
            };
            if let Some((false, header)) = include_path(path, source) {
                let base = header_base(&header);
                if !base.is_empty() {
                    out.insert(base.to_string());
                }
            }
        }
        out
    }

    /// Every locally bound value name — variable `declaration` declarators and
    /// `parameter_declaration` names. Function prototypes are skipped (they are
    /// callables, reported by `callable_definitions`).
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "declaration" => {
                    for decl in field_children(node, "declarator") {
                        if let Some(name) = plain_identifier(decl, source) {
                            out.insert(name);
                        }
                    }
                }
                "parameter_declaration" => {
                    if let Some(decl) = node.child_by_field_name("declarator") {
                        if let Some(name) = plain_identifier(decl, source) {
                            out.insert(name);
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// True if the file is overwhelmingly top-level data literals (static
    /// tables/arrays), threshold 0.65 of non-blank lines.
    pub fn is_data_dominant(&self, source: &str) -> bool {
        if source.trim().is_empty() {
            return false;
        }
        let tree = parse(source);
        let total_nonblank = splitlines(source)
            .iter()
            .filter(|line| !line.trim().is_empty())
            .count();
        if total_nonblank == 0 {
            return false;
        }
        let mut rows: HashSet<usize> = HashSet::new();
        collect_c_data_rows(tree.root_node(), &mut rows);
        (rows.len() as f64) / (total_nonblank as f64) > DATA_DOMINANT_THRESHOLD
    }

    /// 1-indexed line numbers covered by top-level data-literal declarations.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_c_data_rows(tree.root_node(), &mut rows);
        rows.into_iter().map(|r| r + 1).collect()
    }

    /// True if a comment in the first `HEADER_LINE_LIMIT` lines carries an
    /// auto-generation marker (case-insensitive), or a strong DO-NOT-EDIT
    /// marker within the first 10 lines.
    pub fn is_auto_generated(&self, source: &str) -> bool {
        if source.is_empty() {
            return false;
        }
        let tree = parse(source);
        for node in descendants(tree.root_node()) {
            if node.kind() != "comment" {
                continue;
            }
            let line_index = node.start_position().row;
            if line_index >= HEADER_LINE_LIMIT {
                continue;
            }
            let text = node_text(node, source).to_lowercase();
            if line_index < 10 && STRONG_FIRST_10_MARKERS.iter().any(|m| text.contains(m)) {
                return true;
            }
            let hit = GENERIC_MARKERS
                .iter()
                .chain(DO_NOT_EDIT_MARKERS.iter())
                .chain(TOOL_MARKERS.iter())
                .any(|m| text.contains(m));
            if hit {
                return true;
            }
        }
        false
    }

    /// 1-indexed inclusive `(start_line, end_line)` spans for top-level
    /// `function_definition`s with a `compound_statement` body.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let mut ranges = Vec::new();
        for child in children(tree.root_node()) {
            if child.kind() != "function_definition" {
                continue;
            }
            if child.child_by_field_name("body").map(|b| b.kind()) == Some("compound_statement") {
                ranges.push((child.start_position().row + 1, child.end_position().row + 1));
            }
        }
        ranges
    }

    /// 1-indexed line numbers covered by comments (line `//` and block
    /// `/* */`). C has no docstring concept; all prose is in comments.
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() == "comment" {
                let start = node.start_position().row + 1;
                let end = node.end_position().row + 1;
                for r in start..=end {
                    rows.insert(r);
                }
            }
        }
        rows
    }

    /// C keywords + primitive types — noise tokens filtered out of the
    /// repo-wide identifier vocabulary.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

impl LanguageAdapter for CAdapter {
    fn language(&self) -> Language {
        Language::C
    }
    fn extract_imports(&self, source: &str) -> HashSet<String> {
        CAdapter::extract_imports(self, source)
    }
    fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        CAdapter::extract_imports_with_spans(self, source)
    }
    fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        CAdapter::resolve_repo_modules(self, repo_root)
    }
    fn is_data_dominant(&self, source: &str) -> bool {
        CAdapter::is_data_dominant(self, source)
    }
    fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        CAdapter::data_literal_lines(self, source)
    }
    fn callable_definitions(&self, source: &str) -> HashSet<String> {
        CAdapter::callable_definitions(self, source)
    }
    fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        CAdapter::internal_import_bindings(self, source)
    }
    fn value_bindings(&self, source: &str) -> HashSet<String> {
        CAdapter::value_bindings(self, source)
    }
    fn is_auto_generated(&self, source: &str) -> bool {
        CAdapter::is_auto_generated(self, source)
    }
    fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        CAdapter::enumerate_sampleable_ranges(self, source)
    }
    fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        CAdapter::prose_line_ranges(self, source)
    }
    fn identifier_noise(&self) -> &HashSet<String> {
        CAdapter::identifier_noise(self)
    }
    fn line_comment_prefix(&self) -> &'static str {
        "//"
    }
}

/// Whether `kind` is a C call-expression node (used by the shared call-receiver
/// walk). C has a single call node kind.
pub fn is_call_kind(kind: &str) -> bool {
    kind == "call_expression"
}

/// The dotted-callee extractor for C, exposed for the shared call-receiver
/// scorer's function-pointer dispatch.
pub fn callee(call_node: Node, src: &[u8]) -> Option<String> {
    extract_c_callee(call_node, src)
}

/// C keywords, primitive types, and common preprocessor/singleton tokens —
/// noise tokens that would dominate `common here:` without saying anything.
const NOISE: &[&str] = &[
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    "bool",
    "true",
    "false",
    "NULL",
    "_Bool",
    "_Complex",
    "_Imaginary",
    "_Alignas",
    "_Alignof",
    "_Atomic",
    "_Generic",
    "_Noreturn",
    "_Static_assert",
    "_Thread_local",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn system_includes_are_imports_internal_ones_are_not() {
        let adapter = CAdapter::new();
        let src = "#include <stdio.h>\n#include <openssl/ssl.h>\n#include \"foo.h\"\n";
        let imports = adapter.extract_imports(src);
        assert!(imports.contains("stdio.h"));
        // openssl/ssl.h → leading segment "openssl".
        assert!(imports.contains("openssl"));
        // Quoted include is repo-internal, not an external import.
        assert!(!imports.contains("foo.h"));
        assert!(!imports.contains("foo"));
    }

    #[test]
    fn quoted_includes_bind_internal_header_base() {
        let adapter = CAdapter::new();
        let src = "#include <stdio.h>\n#include \"foo.h\"\n#include \"net/conn.h\"\n";
        let bindings = adapter.internal_import_bindings(src);
        assert!(bindings.contains("foo"));
        assert!(bindings.contains("conn"));
        // System headers are not internal bindings.
        assert!(!bindings.contains("stdio"));
    }

    #[test]
    fn import_spans_underline_the_module() {
        let adapter = CAdapter::new();
        let src = "#include <stdio.h>\n";
        let spans = adapter.extract_imports_with_spans(src);
        assert_eq!(spans.len(), 1);
        let (module, line, col_start, col_end) = &spans[0];
        assert_eq!(module, "stdio.h");
        assert_eq!(*line, 1);
        // "<" is column 9 (0-indexed), so the module starts at column 10.
        assert_eq!(*col_start, 10);
        assert_eq!(*col_end, col_start + "stdio.h".len());
    }

    #[test]
    fn callable_definitions_cover_functions_prototypes_and_types() {
        let adapter = CAdapter::new();
        let src = "static char *make(void);\nint add(int a, int b) { return a + b; }\n\
            typedef struct Point { int x; } Point;\nstruct Node { int v; };\n";
        let defs = adapter.callable_definitions(src);
        assert!(defs.contains("make"), "prototype");
        assert!(defs.contains("add"), "definition");
        assert!(defs.contains("Point"), "typedef name");
        assert!(defs.contains("Node"), "struct name");
    }

    #[test]
    fn value_bindings_cover_vars_and_params_not_functions() {
        let adapter = CAdapter::new();
        let src = "int g = 3;\nvoid run(int arg, char *name) { int local = 0; }\n";
        let values = adapter.value_bindings(src);
        assert!(values.contains("g"));
        assert!(values.contains("arg"));
        assert!(values.contains("name"));
        assert!(values.contains("local"));
        // `run` is a callable, not a value binding.
        assert!(!values.contains("run"));
    }

    #[test]
    fn callee_extraction_handles_bare_and_field_calls() {
        let src = b"void run(void) { foo(); obj->method(x); }";
        let mut parser = tree_sitter::Parser::new();
        parser
            .set_language(&tree_sitter_c::LANGUAGE.into())
            .unwrap();
        let tree = parser.parse(&src[..], None).unwrap();
        let mut callees = Vec::new();
        let mut stack = vec![tree.root_node()];
        while let Some(node) = stack.pop() {
            if node.kind() == "call_expression" {
                if let Some(c) = callee(node, src) {
                    callees.push(c);
                }
            }
            for i in (0..node.child_count()).rev() {
                if let Some(c) = node.child(i) {
                    stack.push(c);
                }
            }
        }
        assert!(callees.contains(&"foo".to_string()));
        assert!(callees.contains(&"obj.method".to_string()));
    }

    #[test]
    fn data_dominant_flags_big_tables() {
        let adapter = CAdapter::new();
        let src = "int table[] = {\n1, 2, 3,\n4, 5, 6,\n7, 8, 9,\n10, 11, 12,\n};\n";
        assert!(adapter.is_data_dominant(src));
        let lines = adapter.data_literal_lines(src);
        assert!(lines.contains(&1));
        assert!(lines.contains(&2));

        let code = "int add(int a, int b) {\n    int r = a + b;\n    return r;\n}\n";
        assert!(!adapter.is_data_dominant(code));
    }

    #[test]
    fn sampleable_ranges_are_function_bodies() {
        let adapter = CAdapter::new();
        let src = "int g;\nint add(int a, int b) {\n    return a + b;\n}\n";
        let ranges = adapter.enumerate_sampleable_ranges(src);
        assert_eq!(ranges, vec![(2, 4)]);
    }

    #[test]
    fn prose_lines_cover_line_and_block_comments() {
        let adapter = CAdapter::new();
        let src = "// header\n/* block\n comment */\nint z = 0;\n";
        let rows = adapter.prose_line_ranges(src);
        assert!(rows.contains(&1));
        assert!(rows.contains(&2));
        assert!(rows.contains(&3));
        assert!(!rows.contains(&4));
    }

    #[test]
    fn auto_generated_marker_in_header_detected() {
        let adapter = CAdapter::new();
        assert!(adapter.is_auto_generated("/* Generated by bison. DO NOT EDIT. */\nint x;\n"));
        assert!(!adapter.is_auto_generated("// a normal handwritten file\nint x;\n"));
    }

    #[test]
    fn identifier_noise_contains_keywords_and_types() {
        let adapter = CAdapter::new();
        assert!(adapter.identifier_noise().contains("return"));
        assert!(adapter.identifier_noise().contains("int"));
        assert_eq!(adapter.identifier_noise().len(), NOISE.len());
    }

    #[test]
    fn line_comment_prefix_is_slashes() {
        let adapter = CAdapter::new();
        assert_eq!(
            <CAdapter as LanguageAdapter>::line_comment_prefix(&adapter),
            "//"
        );
    }
}
