//! C++ language adapter.
//!
//! Behaviour-preserving sibling of `python.rs` / `typescript.rs`: wraps the
//! pinned tree-sitter C++ grammar behind the uniform `LanguageAdapter` surface.
//! We replicate the same manual `child_by_field_name` / `children` traversal
//! style used by the other adapters (the 0.23 streaming Query API is a footgun
//! — see `tokenize.rs`).
//!
//! Dependency signals map from `#include` directives:
//! - `#include <vector>` (`system_lib_string`) — an external/system header, the
//!   analog of a non-relative import. Surfaced by `extract_imports`.
//! - `#include "foo.hpp"` (`string_literal`) — a repo-internal header, the
//!   analog of a relative import. Its stem is surfaced by
//!   `internal_import_bindings`; it is NOT treated as foreign.

use std::collections::HashSet;

use tree_sitter::{Node, Tree};

use super::Language;

const HEADER_LINE_LIMIT: usize = 20;

/// RHS node types that indicate a data-dominant initializer.
const CPP_DATA_LITERAL_TYPES: &[&str] = &["initializer_list"];

/// Value node types that count as literal data for the data-dominant check.
const CPP_VALUE_LITERAL_TYPES: &[&str] = &[
    "number_literal",
    "string_literal",
    "char_literal",
    "concatenated_string",
    "true",
    "false",
    "null",
    "nullptr",
    "user_defined_literal",
    "initializer_list",
];

// Auto-generation markers — the same generic set the other adapters use.
const GENERIC_MARKERS: &[&str] = &[
    "auto generated",
    "auto-generated",
    "autogenerated",
    "auto_generated",
    "automatically generated",
    "automatically-generated",
    "automatically created",
    "machine generated",
    "machine-generated",
    "machine created",
    "programmatically generated",
    "computer generated",
    "computer-generated",
    "generated by",
    "generated file",
    "generated code",
    "generated from",
    "generated source",
    "this file was generated",
    "this file is generated",
    "this file has been generated",
    "this file is auto-generated",
    "this file is autogenerated",
    "this file was automatically",
    "this file is automatically",
    "this is a generated file",
    "this file was created by",
    "this module is generated",
    "@generated",
    "@autogenerated",
    "@auto-generated",
    "@ generated",
];
const DO_NOT_EDIT_MARKERS: &[&str] = &[
    "do not edit",
    "do not edit this file",
    "do not modify",
    "do not modify this file",
    "do not modify by hand",
    "do not change this file",
    "please do not edit",
    "please do not modify",
    "source of this file is",
];
const TOOL_MARKERS: &[&str] = &[
    "generated by protoc",
    "generated by the protocol buffer compiler",
    "generated by swagger",
    "generated by openapi-generator",
    "generated by openapi",
    "generated by graphql",
    "generated by buf",
    "generated by betterproto",
    "generated by moc",
    "meta object code",
    "output of",
    "produced by",
    "compiled from",
    "transpiled from",
];
/// "do not edit" / "do not modify" in the first 10 lines suffice on their own.
const STRONG_FIRST_10_MARKERS: &[&str] = &["do not edit", "do not modify"];

/// Parse C++ `source` into a tree-sitter `Tree` (reused parser).
fn parse(source: &str) -> Tree {
    crate::scoring::ts_parse::parse(source, Language::Cpp)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    go(node, &mut out);
    out
}

/// Direct children of `node` as a `Vec`.
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

/// Direct children of `node` carrying field name `field` (a statement can
/// repeat a field, e.g. `int a, b;` has two `declarator` children).
fn field_children<'a>(node: Node<'a>, field: &str) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    if cursor.goto_first_child() {
        loop {
            if cursor.field_name() == Some(field) {
                out.push(cursor.node());
            }
            if !cursor.goto_next_sibling() {
                break;
            }
        }
    }
    out
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// Inner text of an include path node: `<vector>` → `vector`,
/// `"foo/bar.hpp"` → `foo/bar.hpp`.
fn include_target(path: Node, source: &str) -> Option<String> {
    match path.kind() {
        "system_lib_string" => {
            let raw = node_text(path, source);
            let inner = raw.strip_prefix('<').unwrap_or(raw);
            let inner = inner.strip_suffix('>').unwrap_or(inner);
            (!inner.is_empty()).then(|| inner.to_string())
        }
        "string_literal" => {
            // `string_literal` wraps a `string_content` child between quotes.
            let inner = children(path)
                .into_iter()
                .find(|c| c.kind() == "string_content")
                .map(|c| node_text(c, source).to_string())
                .unwrap_or_else(|| {
                    let raw = node_text(path, source);
                    raw.trim_matches('"').to_string()
                });
            (!inner.is_empty()).then_some(inner)
        }
        _ => None,
    }
}

/// The header stem for a quoted include target: last path segment without its
/// extension (`foo/widget.hpp` → `widget`).
fn header_stem(target: &str) -> Option<String> {
    let base = target.rsplit('/').next().unwrap_or(target);
    let stem = base.split('.').next().unwrap_or(base);
    (!stem.is_empty()).then(|| stem.to_string())
}

/// Innermost bound name of a (possibly wrapped) declarator. Navigates through
/// pointer/reference/array/parenthesized/function wrappers down to the
/// identifier. For `Foo::bar` (qualified_identifier) the unqualified `name`
/// field is returned — the callable's own name.
fn declarator_name(node: Node, source: &str) -> Option<String> {
    match node.kind() {
        "identifier"
        | "field_identifier"
        | "type_identifier"
        | "namespace_identifier"
        | "operator_name"
        | "destructor_name" => Some(node_text(node, source).to_string()),
        "qualified_identifier" => node
            .child_by_field_name("name")
            .and_then(|n| declarator_name(n, source)),
        // `reference_declarator` (`&b` / `&&b`) holds its inner declarator as
        // an unnamed child, so the `declarator` field lookup misses it.
        "reference_declarator" => children(node)
            .into_iter()
            .filter(|c| c.is_named())
            .find_map(|c| declarator_name(c, source)),
        _ => node
            .child_by_field_name("declarator")
            .and_then(|d| declarator_name(d, source)),
    }
}

/// True if ≥80% of an initializer_list's elements are literal data. Empty lists
/// return true (conservative — allow).
fn is_cpp_value_literal_dominant(node: Node) -> bool {
    if node.kind() != "initializer_list" {
        return true;
    }
    let values: Vec<Node> = children(node)
        .into_iter()
        .filter(|c| c.is_named())
        .collect();
    if values.is_empty() {
        return true;
    }
    let literal_count = values
        .iter()
        .filter(|v| CPP_VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal_count as f64) / (values.len() as f64) >= 0.8
}

/// Add row spans (0-indexed) of top-level data-literal declarations to `rows`.
fn collect_cpp_data_rows(root: Node, rows: &mut HashSet<usize>) {
    for child in children(root) {
        if child.kind() != "declaration" {
            continue;
        }
        for decl in field_children(child, "declarator") {
            if decl.kind() != "init_declarator" {
                continue;
            }
            let Some(value) = decl.child_by_field_name("value") else {
                continue;
            };
            if CPP_DATA_LITERAL_TYPES.contains(&value.kind())
                && is_cpp_value_literal_dominant(value)
            {
                for r in child.start_position().row..=child.end_position().row {
                    rows.insert(r);
                }
            }
        }
    }
}

/// `CppAdapter` — the language adapter for `.cpp` / `.cc` / `.hpp` / `.cxx`.
///
/// Call-expression callee extraction (`obj.method` / `ptr->run` /
/// `Class::make`) lives in `scoring::call_receiver` alongside the Python and
/// TypeScript extractors, so the receiver-namespace logic stays in one place.
#[derive(Debug, Default)]
pub struct CppAdapter {
    noise: HashSet<String>,
}

impl CppAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// External/system headers included in `source` (`#include <...>`). Quoted
    /// includes are repo-internal and excluded (see `internal_import_bindings`).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "preproc_include" {
                continue;
            }
            let Some(path) = node.child_by_field_name("path") else {
                continue;
            };
            if path.kind() == "system_lib_string" {
                if let Some(target) = include_target(path, source) {
                    out.insert(target);
                }
            }
        }
        out
    }

    /// Like `extract_imports` but each header carries its `(spec, line,
    /// col_start, col_end)` span. Line 1-indexed; columns 0-indexed byte
    /// offsets covering the header text (delimiter skipped). Sorted by
    /// `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "preproc_include" {
                continue;
            }
            let Some(path) = node.child_by_field_name("path") else {
                continue;
            };
            if path.kind() != "system_lib_string" {
                continue;
            }
            if let Some(target) = include_target(path, source) {
                let line = path.start_position().row + 1;
                // Skip the opening `<` so the underline lands on the header.
                let col_start = path.start_position().column + 1;
                let col_end = col_start + target.len();
                out.push((target, line, col_start, col_end));
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// Header stems of repo-internal (quoted) includes. A callee whose name
    /// matches an included neighbourhood header is not foreign voice.
    pub fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "preproc_include" {
                continue;
            }
            let Some(path) = node.child_by_field_name("path") else {
                continue;
            };
            if path.kind() != "string_literal" {
                continue;
            }
            if let Some(stem) = include_target(path, source)
                .as_deref()
                .and_then(header_stem)
            {
                out.insert(stem);
            }
        }
        out
    }

    /// Names the source binds to callable definitions — free functions,
    /// methods (`Class::method`), classes, and structs. Feeds local-binding
    /// attestation: code calling what it defines is not foreign voice.
    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "function_definition" => {
                    if let Some(decl) = node.child_by_field_name("declarator") {
                        if let Some(name) = declarator_name(decl, source) {
                            out.insert(name);
                        }
                    }
                }
                "class_specifier" | "struct_specifier" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        out.insert(node_text(name, source).to_string());
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// Every locally bound value name — variable declarators (including
    /// pointer/array wrappers) and function parameters.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "init_declarator" | "parameter_declaration" | "optional_parameter_declaration" => {
                    if let Some(decl) = node.child_by_field_name("declarator") {
                        if let Some(name) = declarator_name(decl, source) {
                            out.insert(name);
                        }
                    }
                }
                // Uninitialized declarations (`int a, b;`) carry their names
                // directly on `declarator` children rather than init_declarators.
                "declaration" => {
                    for decl in field_children(node, "declarator") {
                        if decl.kind() == "init_declarator" {
                            continue;
                        }
                        if let Some(name) = declarator_name(decl, source) {
                            out.insert(name);
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// True if the file is overwhelmingly top-level data literals (threshold
    /// 0.65 of non-blank lines).
    pub fn is_data_dominant(&self, source: &str) -> bool {
        if source.trim().is_empty() {
            return false;
        }
        let tree = parse(source);
        let total_nonblank = crate::text::splitlines(source)
            .iter()
            .filter(|line| !line.trim().is_empty())
            .count();
        if total_nonblank == 0 {
            return false;
        }
        let mut data_rows: HashSet<usize> = HashSet::new();
        collect_cpp_data_rows(tree.root_node(), &mut data_rows);
        (data_rows.len() as f64) / (total_nonblank as f64) > 0.65
    }

    /// 1-indexed line numbers covered by top-level data-literal declarations.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_cpp_data_rows(tree.root_node(), &mut rows);
        rows.into_iter().map(|r| r + 1).collect()
    }

    /// True if a comment in the first `HEADER_LINE_LIMIT` lines carries an
    /// auto-generation marker (case-insensitive), or a strong DO-NOT-EDIT
    /// marker within the first 10 lines.
    pub fn is_auto_generated(&self, source: &str) -> bool {
        if source.is_empty() {
            return false;
        }
        let tree = parse(source);
        for node in descendants(tree.root_node()) {
            if node.kind() != "comment" {
                continue;
            }
            let line_index = node.start_position().row;
            if line_index >= HEADER_LINE_LIMIT {
                continue;
            }
            let text = node_text(node, source).to_lowercase();
            if line_index < 10 && STRONG_FIRST_10_MARKERS.iter().any(|m| text.contains(m)) {
                return true;
            }
            let hit = GENERIC_MARKERS
                .iter()
                .chain(DO_NOT_EDIT_MARKERS.iter())
                .chain(TOOL_MARKERS.iter())
                .any(|m| text.contains(m));
            if hit {
                return true;
            }
        }
        false
    }

    /// 1-indexed `(start_line, end_line)` spans for every function / method
    /// definition (free functions, inline members, out-of-line `Class::method`
    /// bodies) — the sampleable code units.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let mut ranges: Vec<(usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() == "function_definition" {
                ranges.push((node.start_position().row + 1, node.end_position().row + 1));
            }
        }
        ranges
    }

    /// 1-indexed line numbers covered by comments (line `//` and block `/* */`).
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() == "comment" {
                for r in (node.start_position().row + 1)..=(node.end_position().row + 1) {
                    rows.insert(r);
                }
            }
        }
        rows
    }

    /// C++ keywords, built-in types, and literals filtered out of the
    /// repo-wide identifier vocabulary.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

/// C++ keywords + built-in types + literals (implicit / low-signal tokens).
const NOISE: &[&str] = &[
    "alignas",
    "alignof",
    "and",
    "and_eq",
    "asm",
    "auto",
    "bitand",
    "bitor",
    "bool",
    "break",
    "case",
    "catch",
    "char",
    "char16_t",
    "char32_t",
    "char8_t",
    "class",
    "co_await",
    "co_return",
    "co_yield",
    "compl",
    "concept",
    "const",
    "const_cast",
    "consteval",
    "constexpr",
    "constinit",
    "continue",
    "decltype",
    "default",
    "delete",
    "do",
    "double",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "export",
    "extern",
    "false",
    "float",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "not",
    "not_eq",
    "nullptr",
    "operator",
    "or",
    "or_eq",
    "private",
    "protected",
    "public",
    "register",
    "reinterpret_cast",
    "requires",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "static_cast",
    "struct",
    "switch",
    "template",
    "this",
    "thread_local",
    "throw",
    "true",
    "try",
    "typedef",
    "typeid",
    "typename",
    "union",
    "unsigned",
    "using",
    "virtual",
    "void",
    "volatile",
    "wchar_t",
    "while",
    "xor",
    "xor_eq",
];

#[cfg(test)]
mod tests {
    use super::*;

    fn adapter() -> CppAdapter {
        CppAdapter::new()
    }

    #[test]
    fn system_includes_are_imports_quoted_are_not() {
        let src = "#include <vector>\n#include \"widget.hpp\"\n#include <boost/algorithm.hpp>\n";
        let imports = adapter().extract_imports(src);
        assert!(imports.contains("vector"));
        assert!(imports.contains("boost/algorithm.hpp"));
        assert!(!imports.contains("widget.hpp"));
        assert!(!imports.contains("widget"));
    }

    #[test]
    fn quoted_include_stem_is_internal_binding() {
        let src = "#include \"foo/widget.hpp\"\n#include <vector>\n";
        let internal = adapter().internal_import_bindings(src);
        assert!(internal.contains("widget"));
        assert!(!internal.contains("vector"));
    }

    #[test]
    fn import_spans_point_at_header_text() {
        let src = "#include <vector>\n";
        let spans = adapter().extract_imports_with_spans(src);
        assert_eq!(spans.len(), 1);
        let (spec, line, col_start, col_end) = &spans[0];
        assert_eq!(spec, "vector");
        assert_eq!(*line, 1);
        // "#include " is 9 chars, then '<' at col 9, header starts at col 10.
        assert_eq!(*col_start, 10);
        assert_eq!(*col_end, 10 + "vector".len());
    }

    #[test]
    fn callable_definitions_capture_functions_methods_and_types() {
        let src = "class Widget { public: int compute() { return 0; } };\n\
                   void Widget::run() {}\n\
                   int freefn() { return 1; }\n\
                   struct Point { int x; };\n";
        let defs = adapter().callable_definitions(src);
        assert!(defs.contains("Widget"));
        assert!(defs.contains("compute"));
        assert!(defs.contains("run")); // from Widget::run
        assert!(defs.contains("freefn"));
        assert!(defs.contains("Point"));
    }

    #[test]
    fn value_bindings_capture_locals_and_params() {
        let src = "int f(int a, const std::string& b) {\n    int y = 3;\n    double z;\n}\n";
        let vals = adapter().value_bindings(src);
        assert!(vals.contains("a"));
        assert!(vals.contains("b"));
        assert!(vals.contains("y"));
        assert!(vals.contains("z"));
    }

    #[test]
    fn callee_extraction_covers_member_arrow_and_qualified() {
        // The C++ callee extractor lives in `call_receiver`; assert its output
        // routes through the `Language::Cpp` arm end-to-end.
        let src =
            "void f() {\n    obj.method();\n    ptr->run();\n    ns::make();\n    bare();\n}\n";
        let callees: Vec<String> =
            crate::scoring::call_receiver::extract_callees(src, Language::Cpp)
                .into_iter()
                .flatten()
                .collect();
        assert!(callees.contains(&"obj.method".to_string()));
        assert!(callees.contains(&"ptr.run".to_string()));
        assert!(callees.contains(&"ns.make".to_string()));
        assert!(callees.contains(&"bare".to_string()));
    }

    #[test]
    fn data_dominant_flags_table_files() {
        let src = "static const int table[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};\n\
                   static const int more[] = {11, 12, 13, 14, 15, 16, 17, 18};\n";
        assert!(adapter().is_data_dominant(src));
        let code = "int add(int a, int b) {\n    return a + b;\n}\n";
        assert!(!adapter().is_data_dominant(code));
    }

    #[test]
    fn sampleable_ranges_cover_function_bodies() {
        let src = "int add(int a, int b) {\n    return a + b;\n}\n\nvoid noop() {}\n";
        let ranges = adapter().enumerate_sampleable_ranges(src);
        assert!(ranges.contains(&(1, 3)));
        assert!(ranges.iter().any(|&(s, _)| s == 5));
    }

    #[test]
    fn prose_ranges_cover_line_and_block_comments() {
        let src = "// header\nint x = 1;\n/* multi\n   line */\nint y = 2;\n";
        let prose = adapter().prose_line_ranges(src);
        assert!(prose.contains(&1));
        assert!(prose.contains(&3));
        assert!(prose.contains(&4));
        assert!(!prose.contains(&2));
    }

    #[test]
    fn auto_generated_detects_do_not_edit_header() {
        let gen = "// DO NOT EDIT — generated by protoc\nint x = 1;\n";
        assert!(adapter().is_auto_generated(gen));
        let hand = "// a normal header\nint x = 1;\n";
        assert!(!adapter().is_auto_generated(hand));
    }

    #[test]
    fn identifier_noise_contains_keywords() {
        let a = adapter();
        assert!(a.identifier_noise().contains("class"));
        assert!(a.identifier_noise().contains("template"));
        assert_eq!(a.identifier_noise().len(), NOISE.len());
    }
}
