//! C# language adapter.
//!
//! Structural port following the same manual `TreeCursor`/`child_by_field_name`
//! traversal style as `python.rs` and `typescript.rs`. C# is a statically
//! typed, namespaced language, so this adapter is closest in spirit to the
//! TypeScript one (typed declarations, member-access call chains, `new`
//! expressions) — but the import model differs: C# `using` names a namespace,
//! never a relative path.
//!
//! Notes worth keeping in mind:
//! - `using System.Net.Http;` imports the whole namespace `System.Net.Http`;
//!   like TS specifiers, the dotted name is kept verbatim (never split on `.`).
//! - `global using X;` / `using static X;` differ only by anonymous keyword
//!   tokens — the namespace child is still a bare `qualified_name`/`identifier`.
//! - `using Foo = Bar.Baz;` is an alias: the LHS carries the `name` field, so
//!   the imported target is the *other* `qualified_name`/`identifier` child.
//! - C# `using` never carries a relative specifier, so
//!   `internal_import_bindings` is empty — repo-internal namespaces are
//!   discovered corpus-wide via `extract_imports` at fit time (like Python).

use std::collections::HashSet;
use std::path::Path;

use tree_sitter::{Node, Tree};

use super::{Language, LanguageAdapter, RepoModules};
use crate::text::splitlines;

const HEADER_LINE_LIMIT: usize = 20;

/// Declaration node kinds that bind a callable/type name (`name` field).
const CS_CALLABLE_DEFINITION_TYPES: &[&str] = &[
    "method_declaration",
    "constructor_declaration",
    "class_declaration",
    "interface_declaration",
    "struct_declaration",
    "record_declaration",
    "record_struct_declaration",
    "enum_declaration",
    "property_declaration",
];

/// Declaration kinds whose full line span is a sampleable calibration hunk.
const CS_SAMPLEABLE_TYPES: &[&str] = &["method_declaration", "constructor_declaration"];

/// Invocation / construction node kinds treated as calls.
const CS_CALL_TYPES: &[&str] = &["invocation_expression", "object_creation_expression"];

/// Initializer container kinds that can hold a static data literal.
const CS_DATA_CONTAINER_TYPES: &[&str] = &[
    "array_creation_expression",
    "implicit_array_creation_expression",
    "object_creation_expression",
    "collection_expression",
    "initializer_expression",
];

/// Element node kinds that count as literal data inside an initializer.
const CS_VALUE_LITERAL_TYPES: &[&str] = &[
    "integer_literal",
    "real_literal",
    "string_literal",
    "verbatim_string_literal",
    "raw_string_literal",
    "interpolated_string_expression",
    "character_literal",
    "boolean_literal",
    "null_literal",
    "initializer_expression",
    "collection_expression",
];

/// Header markers (lowercased substring match) flagging machine-authored files.
const AUTO_GENERATED_MARKERS: &[&str] = &[
    "<auto-generated",
    "auto-generated",
    "auto generated",
    "autogenerated",
    "automatically generated",
    "generatedcode",
    "generatedcodeattribute",
    "compilergenerated",
    "generated by",
    "generated code",
    "this file was generated",
    "this code was generated",
    "do not edit",
    "do not modify",
];

const VALUE_DOMINANT_THRESHOLD: f64 = 0.8;
const DATA_DOMINANT_THRESHOLD: f64 = 0.65;

/// Parse C# `source` into a tree-sitter `Tree` (reused per-thread parser).
fn parse(source: &str) -> Tree {
    crate::scoring::ts_parse::parse(source, Language::CSharp)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    go(node, &mut out);
    out
}

/// Direct children of `node` as a `Vec`.
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// The imported name of a `using_directive`: the `qualified_name` /
/// `identifier` child that is *not* the alias LHS (which carries field `name`).
fn using_import_name<'a>(using: Node<'a>) -> Option<Node<'a>> {
    let mut cursor = using.walk();
    if !cursor.goto_first_child() {
        return None;
    }
    loop {
        let node = cursor.node();
        let is_alias_lhs = cursor.field_name() == Some("name");
        if !is_alias_lhs && matches!(node.kind(), "qualified_name" | "identifier") {
            return Some(node);
        }
        if !cursor.goto_next_sibling() {
            return None;
        }
    }
}

/// The initializer expression bound by a `variable_declarator` — the first
/// named child that is not the `name` field.
fn declarator_initializer<'a>(declarator: Node<'a>) -> Option<Node<'a>> {
    let mut cursor = declarator.walk();
    if !cursor.goto_first_child() {
        return None;
    }
    loop {
        let node = cursor.node();
        if node.is_named() && cursor.field_name() != Some("name") {
            return Some(node);
        }
        if !cursor.goto_next_sibling() {
            return None;
        }
    }
}

/// The `initializer_expression` (`{ ... }`) inside a data container, if any.
/// `array`/`object` creations wrap their braces in an `initializer_expression`
/// child; a bare `initializer_expression` / `collection_expression` is itself
/// the block.
fn initializer_block<'a>(node: Node<'a>) -> Option<Node<'a>> {
    match node.kind() {
        "initializer_expression" | "collection_expression" => Some(node),
        _ => children(node)
            .into_iter()
            .find(|c| matches!(c.kind(), "initializer_expression" | "collection_expression")),
    }
}

/// True if ≥80% of the block's element children are literal data. Empty blocks
/// return true (conservative — allow).
fn is_value_literal_dominant(block: Node) -> bool {
    let values: Vec<Node> = children(block)
        .into_iter()
        .filter(|c| c.is_named())
        .collect();
    if values.is_empty() {
        return true;
    }
    let literal = values
        .iter()
        .filter(|v| CS_VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal as f64) / (values.len() as f64) >= VALUE_DOMINANT_THRESHOLD
}

/// Add 0-indexed row spans of data-literal `variable_declarator`s to `rows`.
fn collect_cs_data_rows(root: Node, rows: &mut HashSet<usize>) {
    for node in descendants(root) {
        if node.kind() != "variable_declarator" {
            continue;
        }
        let Some(init) = declarator_initializer(node) else {
            continue;
        };
        if !CS_DATA_CONTAINER_TYPES.contains(&init.kind()) {
            continue;
        }
        let Some(block) = initializer_block(init) else {
            continue;
        };
        if is_value_literal_dominant(block) {
            for r in node.start_position().row..=node.end_position().row {
                rows.insert(r);
            }
        }
    }
}

/// The simple type name of an `object_creation_expression`'s `type` field,
/// with generic type arguments stripped (`List<int>` → `List`).
fn creation_type_name(ty: Node, source: &str) -> Option<String> {
    match ty.kind() {
        "identifier" | "qualified_name" => Some(node_text(ty, source).to_string()),
        "generic_name" => children(ty)
            .into_iter()
            .find(|c| c.kind() == "identifier")
            .map(|id| node_text(id, source).to_string()),
        _ => None,
    }
}

/// Build the dotted callee for an `invocation_expression` /
/// `object_creation_expression`, or `None` when the chain bottoms out at an
/// unsupported expression.
fn extract_cs_callee(call_node: Node, source: &str) -> Option<String> {
    if call_node.kind() == "object_creation_expression" {
        let ty = call_node.child_by_field_name("type")?;
        return creation_type_name(ty, source);
    }
    // invocation_expression
    let mut callee = call_node.child_by_field_name("function")?;
    let mut parts: Vec<String> = Vec::new();
    while callee.kind() == "member_access_expression" {
        let name = callee.child_by_field_name("name")?;
        parts.insert(0, node_text(name, source).to_string());
        // A rooted member access (`x.y.M`) recurses through `expression`; a
        // grammar with no `expression` field bottoms out at the method name.
        match callee.child_by_field_name("expression") {
            Some(expr) => callee = expr,
            None => return Some(parts.join(".")),
        }
    }
    match callee.kind() {
        "identifier" => {
            parts.insert(0, node_text(callee, source).to_string());
            Some(parts.join("."))
        }
        "generic_name" => {
            let id = children(callee)
                .into_iter()
                .find(|c| c.kind() == "identifier")?;
            parts.insert(0, node_text(id, source).to_string());
            Some(parts.join("."))
        }
        // `this.M()` / `base.M()` — `this`/`base` are anonymous receiver nodes;
        // keep them (mirrors the TypeScript adapter's `this`/`super` handling)
        // so class-internal call voice stays visible.
        "this" | "base" => {
            parts.insert(0, node_text(callee, source).to_string());
            Some(parts.join("."))
        }
        k if CS_CALL_TYPES.contains(&k) => {
            parts.insert(0, "<call>".to_string());
            Some(parts.join("."))
        }
        _ => None,
    }
}

/// `CSharpAdapter` — the language adapter for `.cs` sources.
#[derive(Debug, Default)]
pub struct CSharpAdapter {
    noise: HashSet<String>,
}

impl CSharpAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Namespaces imported by `using` directives (dotted names kept verbatim).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "using_directive" {
                continue;
            }
            if let Some(name) = using_import_name(node) {
                let spec = node_text(name, source);
                if !spec.is_empty() {
                    out.insert(spec.to_string());
                }
            }
        }
        out
    }

    /// Like `extract_imports` but each namespace carries its `(spec, line,
    /// col_start, col_end)` span. Line 1-indexed; columns 0-indexed byte
    /// offsets over the namespace text, end exclusive. Sorted by
    /// `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "using_directive" {
                continue;
            }
            if let Some(name) = using_import_name(node) {
                let spec = node_text(name, source);
                if spec.is_empty() {
                    continue;
                }
                let line = name.start_position().row + 1;
                let col_start = name.start_position().column;
                let col_end = col_start + spec.len();
                out.push((spec.to_string(), line, col_start, col_end));
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// C# `using` names namespaces, never relative paths, so there are no
    /// repo-internal exact/prefix rules — internal namespaces are discovered
    /// via `extract_imports` at fit time.
    pub fn resolve_repo_modules(&self, _repo_root: &Path) -> RepoModules {
        RepoModules::default()
    }

    /// True if the file is overwhelmingly static data literals (threshold 0.65).
    pub fn is_data_dominant(&self, source: &str) -> bool {
        if source.trim().is_empty() {
            return false;
        }
        let total_nonblank = splitlines(source)
            .iter()
            .filter(|line| !line.trim().is_empty())
            .count();
        if total_nonblank == 0 {
            return false;
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_cs_data_rows(tree.root_node(), &mut rows);
        (rows.len() as f64) / (total_nonblank as f64) > DATA_DOMINANT_THRESHOLD
    }

    /// 1-indexed line numbers covered by static data-literal declarations.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_cs_data_rows(tree.root_node(), &mut rows);
        rows.into_iter().map(|r| r + 1).collect()
    }

    /// Names bound to callable/type definitions (methods, constructors,
    /// classes, interfaces, structs, records, enums, properties). Feeds
    /// local-binding attestation: code calling what it defines is not foreign.
    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if CS_CALLABLE_DEFINITION_TYPES.contains(&node.kind()) {
                if let Some(name) = node.child_by_field_name("name") {
                    out.insert(node_text(name, source).to_string());
                }
            }
        }
        out
    }

    /// C# `using` directives never bind repo-internal (relative) names, so this
    /// is always empty (namespaces are the import stage's concern).
    pub fn internal_import_bindings(&self, _source: &str) -> HashSet<String> {
        HashSet::new()
    }

    /// Every locally bound value name — variable declarators and parameters.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if matches!(node.kind(), "variable_declarator" | "parameter") {
                if let Some(name) = node.child_by_field_name("name") {
                    out.insert(node_text(name, source).to_string());
                }
            }
        }
        out
    }

    /// True if a header comment/attribute (first `HEADER_LINE_LIMIT` lines)
    /// carries an auto-generation marker (case-insensitive).
    pub fn is_auto_generated(&self, source: &str) -> bool {
        if source.is_empty() {
            return false;
        }
        for line in splitlines(source).iter().take(HEADER_LINE_LIMIT) {
            let lower = line.to_lowercase();
            if AUTO_GENERATED_MARKERS.iter().any(|m| lower.contains(m)) {
                return true;
            }
        }
        false
    }

    /// 1-indexed `(start_line, end_line)` spans for method and constructor
    /// declarations (wherever nested) — the sampleable calibration hunks.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let mut ranges: Vec<(usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if CS_SAMPLEABLE_TYPES.contains(&node.kind()) {
                ranges.push((node.start_position().row + 1, node.end_position().row + 1));
            }
        }
        ranges
    }

    /// 1-indexed line numbers covered by comments (`//`, `/* */`, `///` doc).
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() == "comment" {
                for r in (node.start_position().row + 1)..=(node.end_position().row + 1) {
                    rows.insert(r);
                }
            }
        }
        rows
    }

    /// Dotted-callee signatures for every invocation / construction in
    /// `source`. Not on the `LanguageAdapter` trait — an inherent method
    /// mirroring the TypeScript adapter's `extract_callees`.
    pub fn extract_callees(&self, source: &str) -> Vec<String> {
        if source.trim().is_empty() {
            return Vec::new();
        }
        let tree = parse(source);
        let mut out: Vec<String> = Vec::new();
        for node in descendants(tree.root_node()) {
            if CS_CALL_TYPES.contains(&node.kind()) {
                if let Some(callee) = extract_cs_callee(node, source) {
                    out.push(callee);
                }
            }
        }
        out
    }

    /// C# reserved + contextual keywords and literals filtered out of the
    /// repo-wide identifier vocabulary.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

impl LanguageAdapter for CSharpAdapter {
    fn language(&self) -> Language {
        Language::CSharp
    }
    fn extract_imports(&self, source: &str) -> HashSet<String> {
        CSharpAdapter::extract_imports(self, source)
    }
    fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        CSharpAdapter::extract_imports_with_spans(self, source)
    }
    fn resolve_repo_modules(&self, repo_root: &Path) -> RepoModules {
        CSharpAdapter::resolve_repo_modules(self, repo_root)
    }
    fn is_data_dominant(&self, source: &str) -> bool {
        CSharpAdapter::is_data_dominant(self, source)
    }
    fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        CSharpAdapter::data_literal_lines(self, source)
    }
    fn callable_definitions(&self, source: &str) -> HashSet<String> {
        CSharpAdapter::callable_definitions(self, source)
    }
    fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        CSharpAdapter::internal_import_bindings(self, source)
    }
    fn value_bindings(&self, source: &str) -> HashSet<String> {
        CSharpAdapter::value_bindings(self, source)
    }
    fn is_auto_generated(&self, source: &str) -> bool {
        CSharpAdapter::is_auto_generated(self, source)
    }
    fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        CSharpAdapter::enumerate_sampleable_ranges(self, source)
    }
    fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        CSharpAdapter::prose_line_ranges(self, source)
    }
    fn identifier_noise(&self) -> &HashSet<String> {
        CSharpAdapter::identifier_noise(self)
    }
    fn line_comment_prefix(&self) -> &'static str {
        "//"
    }
}

/// C# reserved keywords + common contextual keywords + literals.
const NOISE: &[&str] = &[
    "abstract",
    "as",
    "base",
    "bool",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "checked",
    "class",
    "const",
    "continue",
    "decimal",
    "default",
    "delegate",
    "do",
    "double",
    "else",
    "enum",
    "event",
    "explicit",
    "extern",
    "false",
    "finally",
    "fixed",
    "float",
    "for",
    "foreach",
    "goto",
    "if",
    "implicit",
    "in",
    "int",
    "interface",
    "internal",
    "is",
    "lock",
    "long",
    "namespace",
    "new",
    "null",
    "object",
    "operator",
    "out",
    "override",
    "params",
    "private",
    "protected",
    "public",
    "readonly",
    "ref",
    "return",
    "sbyte",
    "sealed",
    "short",
    "sizeof",
    "stackalloc",
    "static",
    "string",
    "struct",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "uint",
    "ulong",
    "unchecked",
    "unsafe",
    "ushort",
    "using",
    "virtual",
    "void",
    "volatile",
    "while",
    // Contextual keywords.
    "add",
    "and",
    "async",
    "await",
    "dynamic",
    "get",
    "global",
    "init",
    "nameof",
    "nint",
    "not",
    "nuint",
    "or",
    "partial",
    "record",
    "remove",
    "required",
    "set",
    "value",
    "var",
    "when",
    "where",
    "with",
    "yield",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_imports_keeps_full_namespace() {
        let adapter = CSharpAdapter::new();
        let src = "using System;\nusing System.Net.Http;\nusing Newtonsoft.Json;\n";
        let imports = adapter.extract_imports(src);
        assert!(imports.contains("System"));
        assert!(imports.contains("System.Net.Http"));
        assert!(imports.contains("Newtonsoft.Json"));
    }

    #[test]
    fn global_and_static_and_alias_usings() {
        let adapter = CSharpAdapter::new();
        let src = "global using System.Text;\nusing static System.Math;\nusing Foo = System.Collections.Generic.List;\n";
        let imports = adapter.extract_imports(src);
        assert!(imports.contains("System.Text"));
        assert!(imports.contains("System.Math"));
        // Alias target namespace is imported; the alias LHS `Foo` is not.
        assert!(imports.contains("System.Collections.Generic.List"));
        assert!(!imports.contains("Foo"));
    }

    #[test]
    fn import_spans_are_sorted_and_cover_namespace() {
        let adapter = CSharpAdapter::new();
        let spans = adapter.extract_imports_with_spans("using System.Net.Http;\n");
        assert_eq!(spans.len(), 1);
        let (spec, line, col_start, col_end) = &spans[0];
        assert_eq!(spec, "System.Net.Http");
        assert_eq!(*line, 1);
        assert_eq!(*col_end - *col_start, "System.Net.Http".len());
    }

    #[test]
    fn callable_definitions_cover_all_declaration_kinds() {
        let adapter = CSharpAdapter::new();
        let src = "namespace App {\n  public class Widget {\n    public Widget() {}\n    public int Add(int a, int b) { return a + b; }\n    public int Count { get; set; }\n  }\n  interface IThing {}\n  struct Point {}\n  record Rec(int X);\n  enum Color { Red }\n}\n";
        let defs = adapter.callable_definitions(src);
        assert!(defs.contains("Widget")); // class + constructor
        assert!(defs.contains("Add"));
        assert!(defs.contains("Count"));
        assert!(defs.contains("IThing"));
        assert!(defs.contains("Point"));
        assert!(defs.contains("Rec"));
        assert!(defs.contains("Color"));
    }

    #[test]
    fn value_bindings_cover_locals_and_parameters() {
        let adapter = CSharpAdapter::new();
        let src = "class C { void M(int a, string b) { var y = 2; int z = 3; } }\n";
        let vals = adapter.value_bindings(src);
        assert!(vals.contains("a"));
        assert!(vals.contains("b"));
        assert!(vals.contains("y"));
        assert!(vals.contains("z"));
    }

    #[test]
    fn extract_callees_handles_members_new_and_this() {
        let adapter = CSharpAdapter::new();
        let src = "class C { void M() { obj.Do(); Helper.Run(x); new Thing(1); this.Go(); base.Init(); } }\n";
        let callees = adapter.extract_callees(src);
        assert!(callees.contains(&"obj.Do".to_string()));
        assert!(callees.contains(&"Helper.Run".to_string()));
        assert!(callees.contains(&"Thing".to_string()));
        assert!(callees.contains(&"this.Go".to_string()));
        assert!(callees.contains(&"base.Init".to_string()));
    }

    #[test]
    fn internal_import_bindings_is_empty() {
        let adapter = CSharpAdapter::new();
        assert!(adapter
            .internal_import_bindings("using App.Internal;\n")
            .is_empty());
    }

    #[test]
    fn data_dominant_table_vs_code() {
        let adapter = CSharpAdapter::new();
        let table = "class Data {\n  static readonly int[] T = new int[] {\n    1, 2, 3, 4, 5,\n    6, 7, 8, 9, 10,\n    11, 12, 13, 14, 15,\n  };\n}\n";
        assert!(adapter.is_data_dominant(table));
        assert!(!adapter.data_literal_lines(table).is_empty());

        let code = "class C {\n  public int Add(int a, int b) {\n    var sum = a + b;\n    return sum;\n  }\n}\n";
        assert!(!adapter.is_data_dominant(code));
    }

    #[test]
    fn auto_generated_markers_detected() {
        let adapter = CSharpAdapter::new();
        assert!(adapter.is_auto_generated("// <auto-generated>\nclass C {}\n"));
        assert!(adapter.is_auto_generated("// DO NOT EDIT\nclass C {}\n"));
        assert!(adapter.is_auto_generated("[GeneratedCode(\"tool\", \"1\")]\nclass C {}\n"));
        assert!(!adapter.is_auto_generated("// a normal file\nclass C {}\n"));
    }

    #[test]
    fn sampleable_ranges_are_methods_and_constructors() {
        let adapter = CSharpAdapter::new();
        let src = "class C {\n  public C() {\n    x = 1;\n  }\n  public int Add(int a, int b) {\n    return a + b;\n  }\n}\n";
        let ranges = adapter.enumerate_sampleable_ranges(src);
        // constructor (lines 2-4) and method (lines 5-7).
        assert_eq!(ranges.len(), 2);
        assert!(ranges.contains(&(2, 4)));
        assert!(ranges.contains(&(5, 7)));
    }

    #[test]
    fn prose_line_ranges_cover_comments() {
        let adapter = CSharpAdapter::new();
        let src = "// line comment\nclass C {\n  /* block\n     comment */\n  void M() {}\n}\n";
        let rows = adapter.prose_line_ranges(src);
        assert!(rows.contains(&1));
        assert!(rows.contains(&3));
        assert!(rows.contains(&4));
    }

    #[test]
    fn identifier_noise_contains_keywords() {
        let adapter = CSharpAdapter::new();
        assert!(adapter.identifier_noise().contains("class"));
        assert!(adapter.identifier_noise().contains("var"));
        assert!(adapter.identifier_noise().contains("this"));
        assert_eq!(adapter.identifier_noise().len(), NOISE.len());
    }

    #[test]
    fn line_comment_prefix_is_slashes() {
        let adapter = CSharpAdapter::new();
        assert_eq!(
            <CSharpAdapter as LanguageAdapter>::line_comment_prefix(&adapter),
            "//"
        );
    }
}
