//! PHP language adapter.
//!
//! Behaviour-preserving in the same style as `python.rs` / `typescript.rs`:
//! the tree-sitter parse tree is walked manually
//! (`child_by_field_name`/`children`) rather than through the streaming Query
//! API. Parsing uses the full-PHP grammar (`tree_sitter_php::LANGUAGE_PHP`),
//! which understands the `<?php` opening tag — so every method here expects
//! whole-file source (files always carry the tag).
//!
//! Parity notes worth keeping in mind:
//! - The "module" for a `use Foo\Bar;` import is the *leading* namespace
//!   segment (`Foo`), mirroring the way the Python adapter reduces a dotted
//!   module to its top-level package. Grouped (`use Foo\{A, B};`), aliased
//!   (`use Foo\Bar as Baz;`) and function/const (`use function Foo\f;`) forms
//!   all reduce to the same leading segment.
//! - A file's own `namespace App\Service;` declaration is *not* an import —
//!   only `use` declarations feed the dependency signal.
//! - `require`/`include` of file *paths* are not treated as module imports:
//!   they name filesystem paths, not namespaces, so folding them into the
//!   namespace-based import vocabulary would only add noise.

use std::collections::HashSet;
use std::path::Path;

use tree_sitter::{Node, Tree};

use super::{Language, LanguageAdapter, RepoModules};
use crate::scoring::filters::autogenerated;
use crate::text::splitlines;

const HEADER_LINE_LIMIT: usize = 20;

/// Callable-definition node kinds — each carries a `name` field.
const CALLABLE_TYPES: &[&str] = &[
    "function_definition",
    "method_declaration",
    "class_declaration",
    "interface_declaration",
    "trait_declaration",
    "enum_declaration",
];

/// Top-level declaration kinds sampleable as calibration hunks.
const SAMPLEABLE_TOP_LEVEL: &[&str] = &[
    "function_definition",
    "class_declaration",
    "interface_declaration",
    "trait_declaration",
    "enum_declaration",
];

/// Value node kinds that count as literal data for the data-dominant check.
const VALUE_LITERAL_TYPES: &[&str] = &[
    "string",
    "encapsed_string",
    "heredoc",
    "nowdoc",
    "integer",
    "float",
    "boolean",
    "null",
    "array_creation_expression",
];

/// Parse PHP `source` into a tree-sitter `Tree` (reused parser).
fn parse(source: &str) -> Tree {
    crate::scoring::ts_parse::parse(source, crate::scoring::adapters::Language::Php)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    go(node, &mut out);
    out
}

/// Direct children of `node` as a `Vec` (mirrors Python's `node.children`).
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

/// First `name`-kind descendant of `node` in pre-order, or `None`. For a
/// `namespace_use_declaration` this is always the leading namespace segment —
/// the module the import depends on — regardless of import form.
fn first_name<'a>(node: Node<'a>) -> Option<Node<'a>> {
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        if child.kind() == "name" {
            return Some(child);
        }
        if let Some(found) = first_name(child) {
            return Some(found);
        }
    }
    None
}

/// `PhpAdapter` — the language adapter for `.php` sources.
#[derive(Debug, Default)]
pub struct PhpAdapter {
    noise: HashSet<String>,
}

impl PhpAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Leading namespace segments of every `use` declaration in `source`.
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "namespace_use_declaration" {
                continue;
            }
            if let Some(name) = first_name(node) {
                out.insert(node_text(name, source).to_string());
            }
        }
        out
    }

    /// Like `extract_imports` but each module carries its `(spec, line,
    /// col_start, col_end)` span (line 1-indexed, columns 0-indexed byte
    /// offsets covering the leading segment). Sorted by `(line, col_start,
    /// spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(tree.root_node()) {
            if node.kind() != "namespace_use_declaration" {
                continue;
            }
            if let Some(name) = first_name(node) {
                let spec = node_text(name, source).to_string();
                let line = name.start_position().row + 1;
                let col_start = name.start_position().column;
                let col_end = col_start + spec.len();
                out.push((spec, line, col_start, col_end));
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// Names the source binds to callable definitions — functions, methods,
    /// classes, interfaces, traits, enums. Feeds local-binding attestation:
    /// code calling what it defines is not foreign voice.
    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            if CALLABLE_TYPES.contains(&node.kind()) {
                if let Some(name) = node.child_by_field_name("name") {
                    out.insert(node_text(name, source).to_string());
                }
            }
        }
        out
    }

    /// Every locally bound value name — assignment targets and function
    /// parameters (including constructor property-promotion). Variable names
    /// keep their `$` sigil, matching how call receivers are extracted.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "assignment_expression" | "augmented_assignment_expression" => {
                    if let Some(left) = node.child_by_field_name("left") {
                        if left.kind() == "variable_name" {
                            out.insert(node_text(left, source).to_string());
                        }
                    }
                }
                "simple_parameter" | "property_promotion_parameter" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        if name.kind() == "variable_name" {
                            out.insert(node_text(name, source).to_string());
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// PHP `use` declarations always name absolute namespaces; there is no
    /// relative-import syntax, so repo-internal neighbours can only be
    /// discovered from `extract_imports` at fit time. Empty here, matching the
    /// Python adapter's reliance on fit-time discovery.
    pub fn internal_import_bindings(&self, _source: &str) -> HashSet<String> {
        HashSet::new()
    }

    /// True if the file is overwhelmingly top-level data literals (threshold
    /// 0.65 of non-blank lines).
    pub fn is_data_dominant(&self, source: &str) -> bool {
        if source.trim().is_empty() {
            return false;
        }
        let total_nonblank = splitlines(source)
            .iter()
            .filter(|line| !line.trim().is_empty())
            .count();
        if total_nonblank == 0 {
            return false;
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_data_rows(tree.root_node(), &mut rows);
        (rows.len() as f64) / (total_nonblank as f64) > 0.65
    }

    /// 1-indexed line numbers covered by top-level data-literal statements.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        if source.trim().is_empty() {
            return HashSet::new();
        }
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        collect_data_rows(tree.root_node(), &mut rows);
        rows.into_iter().map(|r| r + 1).collect()
    }

    /// True if a comment in the first `HEADER_LINE_LIMIT` lines carries an
    /// auto-generation marker (case-insensitive), or a strong DO-NOT-EDIT
    /// marker within the first 10 lines.
    pub fn is_auto_generated(&self, source: &str) -> bool {
        if source.is_empty() {
            return false;
        }
        let tree = parse(source);
        for node in descendants(tree.root_node()) {
            if node.kind() != "comment" {
                continue;
            }
            let line_index = node.start_position().row;
            let text = node_text(node, source);
            if autogenerated::comment_indicates_generated(line_index, text, HEADER_LINE_LIMIT) {
                return true;
            }
        }
        false
    }

    /// 1-indexed inclusive `(start_line, end_line)` spans for top-level
    /// functions and class-like declarations — the sampleable calibration
    /// units. A class is a single range (mirroring the Python adapter, which
    /// keeps a whole class/def as one range rather than descending into it).
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let mut ranges = Vec::new();
        for child in children(tree.root_node()) {
            if SAMPLEABLE_TOP_LEVEL.contains(&child.kind()) {
                ranges.push((child.start_position().row + 1, child.end_position().row + 1));
            }
        }
        ranges
    }

    /// 1-indexed line numbers covered by comments (line, hash, and block).
    /// PHP has no docstring concept; all prose is in comments.
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(tree.root_node()) {
            if node.kind() == "comment" {
                for r in (node.start_position().row + 1)..=(node.end_position().row + 1) {
                    rows.insert(r);
                }
            }
        }
        rows
    }

    /// PHP keywords, magic constants, and `$this` — noise tokens that would
    /// dominate the identifier vocabulary without saying anything.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

/// True if ≥80% of the array's immediate element values are literal data.
/// Empty arrays return true (conservative — allow).
fn is_value_literal_dominant(array: Node) -> bool {
    let mut values: Vec<Node> = Vec::new();
    for child in children(array) {
        if child.kind() != "array_element_initializer" {
            continue;
        }
        // For a `key => value` element the value is the last named child; for
        // a bare element it is the only named child.
        if let Some(val) = children(child).into_iter().rfind(|c| c.is_named()) {
            values.push(val);
        }
    }
    if values.is_empty() {
        return true;
    }
    let literal_count = values
        .iter()
        .filter(|v| VALUE_LITERAL_TYPES.contains(&v.kind()))
        .count();
    (literal_count as f64) / (values.len() as f64) >= 0.8
}

/// Add row spans (0-indexed) of top-level data-literal statements to `rows`:
/// `$x = [ ... ];` assignments and `return [ ... ];` — the two dominant PHP
/// config/data-file shapes — whose array is value-literal dominant.
fn collect_data_rows(root: Node, rows: &mut HashSet<usize>) {
    for child in children(root) {
        let (target, array) = match child.kind() {
            "expression_statement" => {
                let Some(assign) = children(child)
                    .into_iter()
                    .find(|c| c.kind() == "assignment_expression")
                else {
                    continue;
                };
                let Some(rhs) = assign.child_by_field_name("right") else {
                    continue;
                };
                (child, rhs)
            }
            "return_statement" => {
                let Some(expr) = children(child).into_iter().find(|c| c.is_named()) else {
                    continue;
                };
                (child, expr)
            }
            _ => continue,
        };
        if array.kind() == "array_creation_expression" && is_value_literal_dominant(array) {
            for r in target.start_position().row..=target.end_position().row {
                rows.insert(r);
            }
        }
    }
}

impl LanguageAdapter for PhpAdapter {
    fn language(&self) -> Language {
        Language::Php
    }
    fn extract_imports(&self, source: &str) -> HashSet<String> {
        PhpAdapter::extract_imports(self, source)
    }
    fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        PhpAdapter::extract_imports_with_spans(self, source)
    }
    fn resolve_repo_modules(&self, _repo_root: &Path) -> RepoModules {
        // PHP internal namespaces are discovered via extract_imports at fit
        // time; there are no static exact/prefix rules.
        RepoModules::default()
    }
    fn is_data_dominant(&self, source: &str) -> bool {
        PhpAdapter::is_data_dominant(self, source)
    }
    fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        PhpAdapter::data_literal_lines(self, source)
    }
    fn callable_definitions(&self, source: &str) -> HashSet<String> {
        PhpAdapter::callable_definitions(self, source)
    }
    fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        PhpAdapter::internal_import_bindings(self, source)
    }
    fn value_bindings(&self, source: &str) -> HashSet<String> {
        PhpAdapter::value_bindings(self, source)
    }
    fn is_auto_generated(&self, source: &str) -> bool {
        PhpAdapter::is_auto_generated(self, source)
    }
    fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        PhpAdapter::enumerate_sampleable_ranges(self, source)
    }
    fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        PhpAdapter::prose_line_ranges(self, source)
    }
    fn identifier_noise(&self) -> &HashSet<String> {
        PhpAdapter::identifier_noise(self)
    }
    fn line_comment_prefix(&self) -> &'static str {
        "//"
    }
}

/// PHP reserved words + magic constants + `$this` — implicit/keyword tokens
/// filtered out of the repo-wide identifier vocabulary.
const NOISE: &[&str] = &[
    "abstract",
    "and",
    "array",
    "as",
    "break",
    "callable",
    "case",
    "catch",
    "class",
    "clone",
    "const",
    "continue",
    "declare",
    "default",
    "do",
    "echo",
    "else",
    "elseif",
    "empty",
    "enddeclare",
    "endfor",
    "endforeach",
    "endif",
    "endswitch",
    "endwhile",
    "enum",
    "extends",
    "false",
    "final",
    "finally",
    "fn",
    "for",
    "foreach",
    "function",
    "global",
    "goto",
    "if",
    "implements",
    "include",
    "include_once",
    "instanceof",
    "insteadof",
    "interface",
    "isset",
    "list",
    "match",
    "namespace",
    "new",
    "null",
    "or",
    "print",
    "private",
    "protected",
    "public",
    "readonly",
    "require",
    "require_once",
    "return",
    "static",
    "switch",
    "throw",
    "trait",
    "true",
    "try",
    "unset",
    "use",
    "var",
    "while",
    "xor",
    "yield",
    "$this",
    "self",
    "parent",
    "__construct",
    "__destruct",
];

#[cfg(test)]
mod tests {
    use super::*;

    const SRC: &str = r#"<?php
namespace App\Service;

use Symfony\Component\HttpFoundation\Response;
use GuzzleHttp\Client as HttpClient;
use App\Model\{User, Account};

// header comment
class UserService
{
    private int $count = 0;

    public function __construct(private HttpClient $client, string $name)
    {
        $this->name = $name;
        $total = 0;
    }

    public function fetch(int $id): ?Response
    {
        try {
            $resp = $this->client->get($id);
            return Response::fromArray($resp);
        } catch (\Throwable $e) {
            throw new RuntimeException("fail");
        }
    }
}

function helper($a, $b)
{
    return $a + $b;
}
"#;

    #[test]
    fn imports_reduce_to_leading_namespace_segment() {
        let adapter = PhpAdapter::new();
        let imports = adapter.extract_imports(SRC);
        assert!(imports.contains("Symfony"));
        assert!(imports.contains("GuzzleHttp"));
        assert!(imports.contains("App")); // grouped use App\Model\{...}
                                          // The file's own `namespace App\Service;` is not an import; only the
                                          // `use App\Model\{...}` contributes "App".
        assert!(!imports.contains("Response"));
        assert!(!imports.contains("HttpClient"));
    }

    #[test]
    fn import_spans_cover_the_leading_segment() {
        let adapter = PhpAdapter::new();
        let spans = adapter.extract_imports_with_spans(SRC);
        let symfony = spans.iter().find(|(s, ..)| s == "Symfony").unwrap();
        assert_eq!(symfony.3 - symfony.2, "Symfony".len());
        // Sorted ascending by (line, col).
        for pair in spans.windows(2) {
            assert!((pair[0].1, pair[0].2) <= (pair[1].1, pair[1].2));
        }
    }

    #[test]
    fn callable_definitions_capture_class_method_and_function() {
        let adapter = PhpAdapter::new();
        let defs = adapter.callable_definitions(SRC);
        assert!(defs.contains("UserService"));
        assert!(defs.contains("fetch"));
        assert!(defs.contains("helper"));
        assert!(defs.contains("__construct"));
    }

    #[test]
    fn value_bindings_capture_assignments_and_parameters() {
        let adapter = PhpAdapter::new();
        let binds = adapter.value_bindings(SRC);
        assert!(binds.contains("$total")); // assignment target
        assert!(binds.contains("$name")); // simple parameter
        assert!(binds.contains("$client")); // promoted constructor property
        assert!(binds.contains("$id"));
    }

    #[test]
    fn internal_import_bindings_are_empty() {
        let adapter = PhpAdapter::new();
        assert!(adapter.internal_import_bindings(SRC).is_empty());
    }

    #[test]
    fn prose_lines_cover_comments() {
        let adapter = PhpAdapter::new();
        let rows = adapter.prose_line_ranges(SRC);
        // "// header comment" sits on line 8 (1-indexed).
        assert!(rows.contains(&8));
    }

    #[test]
    fn sampleable_ranges_span_top_level_units() {
        let adapter = PhpAdapter::new();
        let ranges = adapter.enumerate_sampleable_ranges(SRC);
        // One range for `class UserService` and one for `function helper`.
        assert_eq!(ranges.len(), 2);
        // The class spans multiple lines.
        assert!(ranges.iter().any(|(s, e)| e - s > 5));
    }

    #[test]
    fn config_array_file_is_data_dominant() {
        let adapter = PhpAdapter::new();
        let src = r#"<?php
return [
    "host" => "localhost",
    "port" => 8080,
    "debug" => true,
    "name" => "argot",
    "retries" => 3,
];
"#;
        assert!(adapter.is_data_dominant(src));
        let lines = adapter.data_literal_lines(src);
        assert!(lines.contains(&3)); // "host" => "localhost"
    }

    #[test]
    fn code_file_is_not_data_dominant() {
        let adapter = PhpAdapter::new();
        assert!(!adapter.is_data_dominant(SRC));
    }

    #[test]
    fn auto_generated_header_is_detected() {
        let adapter = PhpAdapter::new();
        let src = "<?php\n/** @generated by protoc — do not edit. */\nclass Foo {}\n";
        assert!(adapter.is_auto_generated(src));
        assert!(!adapter.is_auto_generated(SRC));
    }

    #[test]
    fn identifier_noise_contains_keywords() {
        let adapter = PhpAdapter::new();
        assert!(adapter.identifier_noise().contains("function"));
        assert!(adapter.identifier_noise().contains("$this"));
        assert_eq!(adapter.identifier_noise().len(), NOISE.len());
    }
}
