//! Python language adapter — port of
//! `engine/argot/scoring/parsers/python_ts.py` +
//! `engine/argot/scoring/adapters/python_adapter.py`.
//!
//! Everything here is a behaviour-preserving port of the tree-sitter parsing
//! logic. The Python engine uses tree-sitter's Query API; we replicate the
//! same captures with manual `TreeCursor` traversal (the 0.23 streaming Query
//! API is a footgun — see `tokenize.rs` for the same manual-walk style).
//!
//! Parity notes worth keeping in mind:
//! - `import numpy as np` is NOT captured (the `dotted_name` sits under an
//!   `aliased_import`, not directly on the `name` field).
//! - Relative imports (`from . import x`) are NOT captured.
//! - `from __future__ import ...` is a distinct `future_import_statement`
//!   node → contributes the literal `"__future__"`.

use std::collections::HashSet;
use tree_sitter::{Node, Tree};

use crate::scoring::filters::{autogenerated, data_dominant};

const HEADER_LINE_LIMIT: usize = 20;

/// Parse Python `source` into a tree-sitter `Tree` (reused parser).
pub(crate) fn parse(source: &str) -> Tree {
    crate::scoring::ts_parse::parse(source, crate::scoring::adapters::Language::Python)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    for child in node.children(&mut cursor) {
        out.push(child);
        go(child, &mut out);
    }
    out
}

/// Direct children of `node` as a `Vec` (mirrors Python's `node.children`).
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

/// Direct children of `node` whose field name is `field` and kind is `kind`.
///
/// A statement can carry the same field on several children (e.g.
/// `import os, sys` has two `name` fields), which `child_by_field_name`
/// cannot express — hence the manual cursor walk.
fn field_children_of_kind<'a>(node: Node<'a>, field: &str, kind: &str) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    if cursor.goto_first_child() {
        loop {
            if cursor.field_name() == Some(field) && cursor.node().kind() == kind {
                out.push(cursor.node());
            }
            if !cursor.goto_next_sibling() {
                break;
            }
        }
    }
    out
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

fn top_level(spec: &str) -> &str {
    spec.split('.').next().unwrap_or(spec)
}

/// `_is_docstring` from `python_ts.py`, replicated with node-id equality.
fn is_docstring(node: Node) -> bool {
    let parent = match node.parent() {
        Some(p) => p,
        None => return false,
    };
    let ptype = parent.kind();

    if matches!(ptype, "module" | "class_definition" | "function_definition") {
        let body = match docstring_body(parent) {
            Some(b) => b,
            None => return false,
        };
        let stmts = expression_statements(body);
        let Some(first_stmt) = stmts.first() else {
            return false;
        };
        let fc = children(*first_stmt);
        return !fc.is_empty() && fc[0].id() == node.id();
    }

    if ptype == "expression_statement" {
        let grandparent = match parent.parent() {
            Some(g) => g,
            None => return false,
        };
        let gtype = grandparent.kind();
        if matches!(gtype, "block" | "module") {
            let stmts = expression_statements(grandparent);
            if stmts.first().is_some_and(|s| s.id() == parent.id()) {
                return true;
            }
        }
        if matches!(gtype, "module" | "class_definition" | "function_definition") {
            let body = match docstring_body(grandparent) {
                Some(b) => b,
                None => return false,
            };
            let stmts = expression_statements(body);
            if stmts.first().is_some_and(|s| s.id() == parent.id()) {
                return true;
            }
        }
    }
    false
}

/// Mirror Python's
/// `next((c for c in parent.children if c.type == "block"), parent if module else None)`.
fn docstring_body(parent: Node) -> Option<Node> {
    for c in children(parent) {
        if c.kind() == "block" {
            return Some(c);
        }
    }
    if parent.kind() == "module" {
        Some(parent)
    } else {
        None
    }
}

fn expression_statements(body: Node) -> Vec<Node> {
    children(body)
        .into_iter()
        .filter(|c| c.kind() == "expression_statement")
        .collect()
}

/// Rows (1-indexed) covered by any `interpolation` descendant of `node`.
///
/// Matches `_interpolation_rows`: each interpolation contributes
/// `range(start_row + 1, end_row + 2)`, i.e. `[start_row+1 ..= end_row+1]`.
fn interpolation_rows(node: Node) -> HashSet<usize> {
    let mut rows = HashSet::new();
    for d in descendants(node) {
        if d.kind() == "interpolation" {
            for r in (d.start_position().row + 1)..=(d.end_position().row + 1) {
                rows.insert(r);
            }
        }
    }
    rows
}

/// `PythonAdapter` — the language adapter for `.py` sources.
#[derive(Debug, Default)]
pub struct PythonAdapter {
    noise: HashSet<String>,
}

impl PythonAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Top-level module names imported in `source` (non-relative only).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() {
            return HashSet::new();
        }
        let mut out = HashSet::new();
        for node in descendants(root) {
            match node.kind() {
                "import_statement" => {
                    for name in field_children_of_kind(node, "name", "dotted_name") {
                        out.insert(top_level(node_text(name, source)).to_string());
                    }
                }
                "import_from_statement" => {
                    for name in field_children_of_kind(node, "module_name", "dotted_name") {
                        out.insert(top_level(node_text(name, source)).to_string());
                    }
                }
                "future_import_statement" => {
                    out.insert("__future__".to_string());
                }
                _ => {}
            }
        }
        out
    }

    /// Like `extract_imports` but each specifier carries its `(spec, line,
    /// col_start, col_end)` span. Line is 1-indexed; columns are 0-indexed
    /// byte offsets; `col_end - col_start` spans only the top-level piece.
    /// Sorted by `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() {
            return Vec::new();
        }
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(root) {
            match node.kind() {
                "import_statement" | "import_from_statement" => {
                    let field = if node.kind() == "import_statement" {
                        "name"
                    } else {
                        "module_name"
                    };
                    for name in field_children_of_kind(node, field, "dotted_name") {
                        let top = top_level(node_text(name, source)).to_string();
                        let line = name.start_position().row + 1;
                        let col_start = name.start_position().column;
                        let col_end = col_start + top.len();
                        out.push((top, line, col_start, col_end));
                    }
                }
                "future_import_statement" => {
                    let line = node.start_position().row + 1;
                    let col_start = node.start_position().column;
                    let col_end = col_start + "__future__".len();
                    out.push(("__future__".to_string(), line, col_start, col_end));
                }
                _ => {}
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// 1-indexed line numbers that carry prose: docstrings, multiline
    /// strings (minus interpolation rows), and comments.
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() {
            return HashSet::new();
        }
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(root) {
            match node.kind() {
                "string" => {
                    let start_row = node.start_position().row;
                    let end_row = node.end_position().row;
                    let is_multiline = end_row > start_row;
                    if !(is_multiline || is_docstring(node)) {
                        continue;
                    }
                    let interp = interpolation_rows(node);
                    for r in (start_row + 1)..=(end_row + 1) {
                        if !interp.contains(&r) {
                            rows.insert(r);
                        }
                    }
                }
                "comment" => {
                    rows.insert(node.start_position().row + 1);
                }
                _ => {}
            }
        }
        rows
    }

    /// True if the file is overwhelmingly static data literals (threshold 0.65).
    pub fn is_data_dominant(&self, source: &str) -> bool {
        data_dominant::is_data_dominant(source, 0.65)
    }

    /// True if the file header carries an auto-generation marker (head 20 lines).
    pub fn is_auto_generated(&self, source: &str) -> bool {
        autogenerated::is_auto_generated(source, HEADER_LINE_LIMIT)
    }

    /// 1-indexed inclusive `(start_line, end_line)` spans for module-level
    /// function/class definitions. Emulates `ast.parse` (empty on error);
    /// decorated definitions report the `def`/`class` line, excluding
    /// decorators, matching CPython 3.8+ `lineno`.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() {
            return Vec::new();
        }
        let mut ranges = Vec::new();
        for child in children(root) {
            match child.kind() {
                "function_definition" | "class_definition" => {
                    ranges.push((child.start_position().row + 1, child.end_position().row + 1));
                }
                "decorated_definition" => {
                    for inner in children(child) {
                        if matches!(inner.kind(), "function_definition" | "class_definition") {
                            ranges.push((
                                inner.start_position().row + 1,
                                inner.end_position().row + 1,
                            ));
                            break;
                        }
                    }
                }
                _ => {}
            }
        }
        ranges
    }

    /// Python keywords, soft keywords, singletons, and `self`/`cls` — noise
    /// tokens that would dominate `common here:` without saying anything.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

/// Python keywords + soft keywords (PEP 617) + singletons + `self`/`cls`.
const NOISE: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield", "match", "case", "self", "cls",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn aliased_and_relative_imports_are_not_captured() {
        let adapter = PythonAdapter::new();
        let src =
            "import numpy as np\nfrom . import local\nfrom ..pkg import thing\nimport a.b.c\n";
        let imports = adapter.extract_imports(src);
        assert!(imports.contains("a"));
        assert!(!imports.contains("numpy"));
        assert!(!imports.contains("np"));
        assert!(!imports.contains("pkg"));
        assert!(!imports.contains("local"));
    }

    #[test]
    fn future_import_is_literal() {
        let adapter = PythonAdapter::new();
        let imports = adapter.extract_imports("from __future__ import annotations\n");
        assert!(imports.contains("__future__"));
    }

    #[test]
    fn syntax_error_yields_empty() {
        let adapter = PythonAdapter::new();
        let src = "def broken(:\n    pass this is not python";
        assert!(adapter.extract_imports(src).is_empty());
        assert!(adapter.extract_imports_with_spans(src).is_empty());
        assert!(adapter.prose_line_ranges(src).is_empty());
        assert!(adapter.enumerate_sampleable_ranges(src).is_empty());
    }

    #[test]
    fn identifier_noise_contains_keywords() {
        let adapter = PythonAdapter::new();
        assert!(adapter.identifier_noise().contains("self"));
        assert!(adapter.identifier_noise().contains("lambda"));
        assert_eq!(adapter.identifier_noise().len(), NOISE.len());
    }
}
