//! Python language adapter — port of
//! `engine/argot/scoring/parsers/python_ts.py` +
//! `engine/argot/scoring/adapters/python_adapter.py`.
//!
//! Everything here is a behaviour-preserving port of the tree-sitter parsing
//! logic. The Python engine uses tree-sitter's Query API; we replicate the
//! same captures with manual `TreeCursor` traversal (the 0.23 streaming Query
//! API is a footgun — see `tokenize.rs` for the same manual-walk style).
//!
//! Parity notes worth keeping in mind:
//! - `import numpy as np` is NOT captured (the `dotted_name` sits under an
//!   `aliased_import`, not directly on the `name` field).
//! - Relative imports (`from . import x`) are NOT captured.
//! - `from __future__ import ...` is a distinct `future_import_statement`
//!   node → contributes the literal `"__future__"`.

use std::collections::HashSet;
use tree_sitter::{Node, Tree};

use crate::scoring::filters::{autogenerated, data_dominant};

use super::HEADER_LINE_LIMIT;

/// Parse Python `source` into a tree-sitter `Tree` (reused parser).
pub(crate) fn parse(source: &str) -> Tree {
    crate::scoring::ts_parse::parse(source, crate::scoring::adapters::Language::Python)
        .expect("tree-sitter parse never returns None without a timeout")
}

/// Collect every descendant of `node` (pre-order, excluding `node` itself).
fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    for child in node.children(&mut cursor) {
        out.push(child);
        go(child, &mut out);
    }
    out
}

/// Direct children of `node` as a `Vec` (mirrors Python's `node.children`).
fn children<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut cursor = node.walk();
    node.children(&mut cursor).collect()
}

/// Direct children of `node` whose field name is `field` and kind is `kind`.
///
/// A statement can carry the same field on several children (e.g.
/// `import os, sys` has two `name` fields), which `child_by_field_name`
/// cannot express — hence the manual cursor walk.
fn field_children_of_kind<'a>(node: Node<'a>, field: &str, kind: &str) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    if cursor.goto_first_child() {
        loop {
            if cursor.field_name() == Some(field) && cursor.node().kind() == kind {
                out.push(cursor.node());
            }
            if !cursor.goto_next_sibling() {
                break;
            }
        }
    }
    out
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

fn top_level(spec: &str) -> &str {
    spec.split('.').next().unwrap_or(spec)
}

/// Whether `node` begins at the first non-whitespace character of its line.
///
/// A genuine `import`/`from` statement always starts its logical line (modulo
/// indentation). Tree-sitter's error recovery on a mid-construct diff fragment
/// can split a relative import like `from ._compat import v2` and re-parse its
/// tail `import v2` as a standalone `import_statement` starting mid-line — which
/// would otherwise contribute the imported *symbol* (`v2`) as a phantom foreign
/// module. Requiring the node to own the start of its line rejects that
/// artifact (and semicolon-chained imports, which are vanishingly rare and not
/// worth a foreign-import fire).
fn node_starts_line(node: Node, source: &str) -> bool {
    let start = node.start_byte();
    source[..start]
        .rsplit('\n')
        .next()
        .is_none_or(|prefix| prefix.bytes().all(|b| b == b' ' || b == b'\t'))
}

/// `_is_docstring` from `python_ts.py`, replicated with node-id equality.
fn is_docstring(node: Node) -> bool {
    let parent = match node.parent() {
        Some(p) => p,
        None => return false,
    };
    let ptype = parent.kind();

    if matches!(ptype, "module" | "class_definition" | "function_definition") {
        let body = match docstring_body(parent) {
            Some(b) => b,
            None => return false,
        };
        let stmts = expression_statements(body);
        let Some(first_stmt) = stmts.first() else {
            return false;
        };
        let fc = children(*first_stmt);
        return !fc.is_empty() && fc[0].id() == node.id();
    }

    if ptype == "expression_statement" {
        let grandparent = match parent.parent() {
            Some(g) => g,
            None => return false,
        };
        let gtype = grandparent.kind();
        if matches!(gtype, "block" | "module") {
            let stmts = expression_statements(grandparent);
            if stmts.first().is_some_and(|s| s.id() == parent.id()) {
                return true;
            }
        }
        if matches!(gtype, "module" | "class_definition" | "function_definition") {
            let body = match docstring_body(grandparent) {
                Some(b) => b,
                None => return false,
            };
            let stmts = expression_statements(body);
            if stmts.first().is_some_and(|s| s.id() == parent.id()) {
                return true;
            }
        }
    }
    false
}

/// Mirror Python's
/// `next((c for c in parent.children if c.type == "block"), parent if module else None)`.
fn docstring_body(parent: Node) -> Option<Node> {
    for c in children(parent) {
        if c.kind() == "block" {
            return Some(c);
        }
    }
    if parent.kind() == "module" {
        Some(parent)
    } else {
        None
    }
}

fn expression_statements(body: Node) -> Vec<Node> {
    children(body)
        .into_iter()
        .filter(|c| c.kind() == "expression_statement")
        .collect()
}

/// Rows (1-indexed) covered by any `interpolation` descendant of `node`.
///
/// Matches `_interpolation_rows`: each interpolation contributes
/// `range(start_row + 1, end_row + 2)`, i.e. `[start_row+1 ..= end_row+1]`.
fn interpolation_rows(node: Node) -> HashSet<usize> {
    let mut rows = HashSet::new();
    for d in descendants(node) {
        if d.kind() == "interpolation" {
            for r in (d.start_position().row + 1)..=(d.end_position().row + 1) {
                rows.insert(r);
            }
        }
    }
    rows
}

/// `PythonAdapter` — the language adapter for `.py` sources.
#[derive(Debug, Default)]
pub struct PythonAdapter {
    noise: HashSet<String>,
}

impl PythonAdapter {
    pub fn new() -> Self {
        Self {
            noise: NOISE.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// Top-level module names imported in `source` (non-relative only).
    ///
    /// Error-tolerant like the TypeScript extractor: git picks hunk
    /// boundaries, so check-time fragments routinely carry root parse errors
    /// — tree-sitter still yields the well-formed import statements within,
    /// and bailing on `has_error` silently disabled the import stage on
    /// exactly the hunks check scores (measured: saleor framework-swap
    /// fixtures through the production path).
    pub fn extract_imports(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut out = HashSet::new();
        for node in descendants(root) {
            match node.kind() {
                "import_statement" if node_starts_line(node, source) => {
                    for name in field_children_of_kind(node, "name", "dotted_name") {
                        out.insert(top_level(node_text(name, source)).to_string());
                    }
                }
                "import_from_statement" if node_starts_line(node, source) => {
                    for name in field_children_of_kind(node, "module_name", "dotted_name") {
                        out.insert(top_level(node_text(name, source)).to_string());
                    }
                }
                "future_import_statement" => {
                    out.insert("__future__".to_string());
                }
                _ => {}
            }
        }
        out
    }

    /// Like `extract_imports` but each specifier carries its `(spec, line,
    /// col_start, col_end)` span. Line is 1-indexed; columns are 0-indexed
    /// byte offsets; `col_end - col_start` spans only the top-level piece.
    /// Sorted by `(line, col_start, spec)`.
    pub fn extract_imports_with_spans(&self, source: &str) -> Vec<(String, usize, usize, usize)> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut out: Vec<(String, usize, usize, usize)> = Vec::new();
        for node in descendants(root) {
            match node.kind() {
                "import_statement" | "import_from_statement" if node_starts_line(node, source) => {
                    let field = if node.kind() == "import_statement" {
                        "name"
                    } else {
                        "module_name"
                    };
                    for name in field_children_of_kind(node, field, "dotted_name") {
                        let top = top_level(node_text(name, source)).to_string();
                        let line = name.start_position().row + 1;
                        let col_start = name.start_position().column;
                        let col_end = col_start + top.len();
                        out.push((top, line, col_start, col_end));
                    }
                }
                "future_import_statement" => {
                    let line = node.start_position().row + 1;
                    let col_start = node.start_position().column;
                    let col_end = col_start + "__future__".len();
                    out.push(("__future__".to_string(), line, col_start, col_end));
                }
                _ => {}
            }
        }
        out.sort_by(|a, b| (a.1, a.2, &a.0).cmp(&(b.1, b.2, &b.0)));
        out
    }

    /// 1-indexed line numbers that carry prose: docstrings, multiline
    /// strings (minus interpolation rows), and comments.
    pub fn prose_line_ranges(&self, source: &str) -> HashSet<usize> {
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() {
            return HashSet::new();
        }
        let mut rows: HashSet<usize> = HashSet::new();
        for node in descendants(root) {
            match node.kind() {
                "string" => {
                    let start_row = node.start_position().row;
                    let end_row = node.end_position().row;
                    let is_multiline = end_row > start_row;
                    if !(is_multiline || is_docstring(node)) {
                        continue;
                    }
                    let interp = interpolation_rows(node);
                    for r in (start_row + 1)..=(end_row + 1) {
                        if !interp.contains(&r) {
                            rows.insert(r);
                        }
                    }
                }
                "comment" => {
                    rows.insert(node.start_position().row + 1);
                }
                _ => {}
            }
        }
        rows
    }

    /// True if the file is overwhelmingly static data literals (threshold 0.65).
    pub fn is_data_dominant(&self, source: &str, threshold: f64) -> bool {
        data_dominant::is_data_dominant(source, threshold)
    }

    /// 1-indexed line numbers covered by data-literal assignment spans.
    pub fn data_literal_lines(&self, source: &str) -> HashSet<usize> {
        data_dominant::data_literal_lines(source)
    }

    /// Names the source binds to callable definitions — `def`, `class`, and
    /// `name = lambda …` assignments. Feeds local-binding attestation: code
    /// calling what it defines is not foreign voice.
    pub fn callable_definitions(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "function_definition" | "class_definition" => {
                    if let Some(name) = node.child_by_field_name("name") {
                        out.insert(node_text(name, source).to_string());
                    }
                }
                "assignment" => {
                    if let (Some(left), Some(right)) = (
                        node.child_by_field_name("left"),
                        node.child_by_field_name("right"),
                    ) {
                        if left.kind() == "identifier" && right.kind() == "lambda" {
                            out.insert(node_text(left, source).to_string());
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// Every locally bound value name — assignment targets, function
    /// parameters, and `for` targets.
    pub fn value_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let mut out = HashSet::new();
        let collect_ids = |node: Node, out: &mut HashSet<String>| {
            if node.kind() == "identifier" {
                out.insert(node_text(node, source).to_string());
                return;
            }
            for d in descendants(node) {
                if d.kind() == "identifier" {
                    out.insert(node_text(d, source).to_string());
                }
            }
        };
        for node in descendants(tree.root_node()) {
            match node.kind() {
                "assignment" | "augmented_assignment" => {
                    if let Some(left) = node.child_by_field_name("left") {
                        collect_ids(left, &mut out);
                    }
                }
                "parameters" => {
                    collect_ids(node, &mut out);
                }
                "for_statement" | "for_in_clause" => {
                    if let Some(left) = node.child_by_field_name("left") {
                        collect_ids(left, &mut out);
                    }
                }
                // Imports bind names too (whether the module is in-voice is
                // the import stage's question). `import a.b` binds `a`;
                // `from m import y as z` binds `z` (else `y`).
                "import_statement" | "import_from_statement" => {
                    for name in field_children_of_kind(node, "name", "dotted_name") {
                        out.insert(top_level(node_text(name, source)).to_string());
                    }
                    for name in field_children_of_kind(node, "name", "aliased_import") {
                        if let Some(alias) = name.child_by_field_name("alias") {
                            out.insert(node_text(alias, source).to_string());
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// Names bound by relative imports (`from .x import y as z` binds `z`;
    /// `from . import x` binds `x`). Repo-internal neighbours are not
    /// foreign voice.
    pub fn internal_import_bindings(&self, source: &str) -> HashSet<String> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut out = HashSet::new();
        for node in descendants(root) {
            if node.kind() != "import_from_statement" {
                continue;
            }
            // Relative iff the module_name field is a `relative_import`.
            if field_children_of_kind(node, "module_name", "relative_import").is_empty() {
                continue;
            }
            for name in field_children_of_kind(node, "name", "dotted_name") {
                out.insert(top_level(node_text(name, source)).to_string());
            }
            for name in field_children_of_kind(node, "name", "aliased_import") {
                if let Some(alias) = name.child_by_field_name("alias") {
                    out.insert(node_text(alias, source).to_string());
                }
            }
        }
        out
    }

    /// See `LanguageAdapter::import_bindings`. Non-relative imports only, each
    /// bound name paired with its top-level module: `import numpy as np` →
    /// `(np, numpy)`, `from colorama import Fore, Style` → `(Fore, colorama),
    /// (Style, colorama)`. Relative imports are repo-internal and skipped.
    pub fn import_bindings(&self, source: &str) -> Vec<(String, String)> {
        let tree = parse(source);
        let root = tree.root_node();
        let mut out = Vec::new();
        for node in descendants(root) {
            match node.kind() {
                "import_statement" if node_starts_line(node, source) => {
                    // `import a.b` binds `a` from module `a`.
                    for name in field_children_of_kind(node, "name", "dotted_name") {
                        let top = top_level(node_text(name, source)).to_string();
                        out.push((top.clone(), top));
                    }
                    // `import numpy as np` binds `np` from module `numpy`.
                    for name in field_children_of_kind(node, "name", "aliased_import") {
                        let module = name
                            .child_by_field_name("name")
                            .map(|n| top_level(node_text(n, source)).to_string());
                        let alias = name
                            .child_by_field_name("alias")
                            .map(|a| node_text(a, source).to_string());
                        if let (Some(module), Some(alias)) = (module, alias) {
                            out.push((alias, module));
                        }
                    }
                }
                "import_from_statement" if node_starts_line(node, source) => {
                    // Relative (`from .x import y`) is repo-internal, not foreign.
                    if !field_children_of_kind(node, "module_name", "relative_import").is_empty() {
                        continue;
                    }
                    let Some(module) = field_children_of_kind(node, "module_name", "dotted_name")
                        .first()
                        .map(|m| top_level(node_text(*m, source)).to_string())
                    else {
                        continue;
                    };
                    for name in field_children_of_kind(node, "name", "dotted_name") {
                        out.push((
                            top_level(node_text(name, source)).to_string(),
                            module.clone(),
                        ));
                    }
                    for name in field_children_of_kind(node, "name", "aliased_import") {
                        if let Some(alias) = name.child_by_field_name("alias") {
                            out.push((node_text(alias, source).to_string(), module.clone()));
                        }
                    }
                }
                _ => {}
            }
        }
        out
    }

    /// True if the file header carries an auto-generation marker (head 20 lines).
    pub fn is_auto_generated(&self, source: &str, markers: &[String]) -> bool {
        autogenerated::is_auto_generated(source, HEADER_LINE_LIMIT, markers)
    }

    /// 1-indexed inclusive `(start_line, end_line)` spans for module-level
    /// function/class definitions. Emulates `ast.parse` (empty on error);
    /// decorated definitions report the `def`/`class` line, excluding
    /// decorators, matching CPython 3.8+ `lineno`.
    pub fn enumerate_sampleable_ranges(&self, source: &str) -> Vec<(usize, usize)> {
        let tree = parse(source);
        let root = tree.root_node();
        if root.has_error() {
            return Vec::new();
        }
        let mut ranges = Vec::new();
        for child in children(root) {
            match child.kind() {
                "function_definition" | "class_definition" => {
                    ranges.push((child.start_position().row + 1, child.end_position().row + 1));
                }
                "decorated_definition" => {
                    for inner in children(child) {
                        if matches!(inner.kind(), "function_definition" | "class_definition") {
                            ranges.push((
                                inner.start_position().row + 1,
                                inner.end_position().row + 1,
                            ));
                            break;
                        }
                    }
                }
                _ => {}
            }
        }
        ranges
    }

    /// Python keywords, soft keywords, singletons, and `self`/`cls` — noise
    /// tokens that would dominate `common here:` without saying anything.
    pub fn identifier_noise(&self) -> &HashSet<String> {
        &self.noise
    }
}

/// Python keywords + soft keywords (PEP 617) + singletons + `self`/`cls`.
const NOISE: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield", "match", "case", "self", "cls",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn aliased_and_relative_imports_are_not_captured() {
        let adapter = PythonAdapter::new();
        let src =
            "import numpy as np\nfrom . import local\nfrom ..pkg import thing\nimport a.b.c\n";
        let imports = adapter.extract_imports(src);
        assert!(imports.contains("a"));
        assert!(!imports.contains("numpy"));
        assert!(!imports.contains("np"));
        assert!(!imports.contains("pkg"));
        assert!(!imports.contains("local"));
    }

    /// Error-recovery guard: a diff fragment starting mid-function whose only
    /// import is relative (`from ._compat import v2`) must yield no module.
    /// Tree-sitter re-parses the tail `import v2` as a standalone
    /// `import_statement` mid-line; the phantom module `v2` used to leak
    /// through and fire the import stage on the codebase's own relative import
    /// (fastapi holdout false alarms).
    #[test]
    fn relative_import_in_error_fragment_yields_no_module() {
        let adapter = PythonAdapter::new();
        let frag = "    cloned_types: Optional[Mapping[str, str]] = None,\n) -> ModelField:\n    if PYDANTIC_V2:\n        from ._compat import v2\n\n        if isinstance(field, v2.ModelField):\n            return field\n    if cloned_types is None:";
        let imports = adapter.extract_imports(frag);
        assert!(
            !imports.contains("v2"),
            "imported symbol of a relative import leaked as a module: {imports:?}"
        );
        assert!(
            imports.is_empty(),
            "no top-level module in fragment: {imports:?}"
        );
        // A genuine top-level import in the same fragment still counts.
        let frag2 = format!("    x = 1\n{frag}\nimport requests\n");
        assert!(adapter.extract_imports(&frag2).contains("requests"));
    }

    #[test]
    fn future_import_is_literal() {
        let adapter = PythonAdapter::new();
        let imports = adapter.extract_imports("from __future__ import annotations\n");
        assert!(imports.contains("__future__"));
    }

    #[test]
    fn import_bindings_pairs_bound_names_with_modules() {
        let adapter = PythonAdapter::new();
        let src = "import numpy as np\nimport os.path\nfrom colorama import Fore, Back, Style\nfrom . import local\nfrom .pkg import thing as t\n";
        let b: std::collections::HashSet<(String, String)> =
            adapter.import_bindings(src).into_iter().collect();
        // Aliased top-level import: binding is the alias, module the real name.
        assert!(b.contains(&("np".to_string(), "numpy".to_string())));
        // Dotted import binds the crate root to itself.
        assert!(b.contains(&("os".to_string(), "os".to_string())));
        // `from m import a, b` binds each name to m.
        assert!(b.contains(&("Fore".to_string(), "colorama".to_string())));
        assert!(b.contains(&("Style".to_string(), "colorama".to_string())));
        // Relative imports are repo-internal — never surfaced as foreign bindings.
        assert!(!b
            .iter()
            .any(|(n, _)| n == "local" || n == "t" || n == "thing"));
    }

    #[test]
    fn syntax_error_yields_empty() {
        let adapter = PythonAdapter::new();
        let src = "def broken(:\n    pass this is not python";
        assert!(adapter.extract_imports(src).is_empty());
        assert!(adapter.extract_imports_with_spans(src).is_empty());
        assert!(adapter.prose_line_ranges(src).is_empty());
        assert!(adapter.enumerate_sampleable_ranges(src).is_empty());
    }

    #[test]
    fn identifier_noise_contains_keywords() {
        let adapter = PythonAdapter::new();
        assert!(adapter.identifier_noise().contains("self"));
        assert!(adapter.identifier_noise().contains("lambda"));
        assert_eq!(adapter.identifier_noise().len(), NOISE.len());
    }
}
