from __future__ import annotations

from pathlib import Path

from argot.scoring.adapters.language_adapter import LanguageAdapter
from argot.scoring.adapters.python_adapter import PythonAdapter

_CATALOG = Path(__file__).parent.parent / "acceptance" / "catalog"
_FASTAPI_FIXTURES = _CATALOG / "fastapi" / "fixtures" / "default"
_RICH_MODEL_A = _CATALOG / "rich" / "sources" / "model_a"
_FAKER_MODEL_A = _CATALOG / "faker" / "sources" / "model_a"

_CONTROL_FILES = sorted(_FASTAPI_FIXTURES.glob("control_*.py"))[:3]
_RICH_FILES = sorted(_RICH_MODEL_A.glob("*.py"))[:3]
_FAKER_FILES = sorted(_FAKER_MODEL_A.glob("*.py"))[:3]


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def test_python_adapter_implements_protocol() -> None:
    adapter = PythonAdapter()
    assert isinstance(adapter, LanguageAdapter)


def test_enumerate_sampleable_ranges_on_fastapi_fixtures() -> None:
    """enumerate_sampleable_ranges returns non-empty list of (start, end) pairs."""
    adapter = PythonAdapter()
    for f in _CONTROL_FILES:
        src = _read(f)
        ranges = adapter.enumerate_sampleable_ranges(src)
        assert isinstance(ranges, list), f"{f.name}: expected list"
        assert len(ranges) > 0, f"{f.name}: no sampleable ranges found"
        for start, end in ranges:
            assert isinstance(start, int)
            assert isinstance(end, int)
            assert start < end, f"{f.name}: start {start} >= end {end}"


def test_enumerate_sampleable_ranges_on_rich_model_a() -> None:
    adapter = PythonAdapter()
    for f in _RICH_FILES:
        src = _read(f)
        ranges = adapter.enumerate_sampleable_ranges(src)
        assert isinstance(ranges, list)


def test_enumerate_sampleable_ranges_on_faker_model_a() -> None:
    adapter = PythonAdapter()
    for f in _FAKER_FILES:
        src = _read(f)
        ranges = adapter.enumerate_sampleable_ranges(src)
        assert isinstance(ranges, list)


def test_is_data_dominant_false_for_fastapi_control_files() -> None:
    """FastAPI control files contain normal code, not data literals."""
    adapter = PythonAdapter()
    for f in _CONTROL_FILES:
        src = _read(f)
        assert not adapter.is_data_dominant(src), f"{f.name} should not be data-dominant"


def test_is_data_dominant_true_for_hand_crafted_locale_file() -> None:
    adapter = PythonAdapter()
    locale_src = (
        "# locale data\n"
        "COLORS = {\n"
        "    'red': '#FF0000',\n"
        "    'green': '#00FF00',\n"
        "    'blue': '#0000FF',\n"
        "    'yellow': '#FFFF00',\n"
        "    'cyan': '#00FFFF',\n"
        "    'magenta': '#FF00FF',\n"
        "    'orange': '#FFA500',\n"
        "    'pink': '#FFC0CB',\n"
        "    'purple': '#800080',\n"
        "    'brown': '#A52A2A',\n"
        "    'black': '#000000',\n"
        "    'white': '#FFFFFF',\n"
        "    'gray': '#808080',\n"
        "    'silver': '#C0C0C0',\n"
        "    'gold': '#FFD700',\n"
        "    'beige': '#F5F5DC',\n"
        "    'ivory': '#FFFFF0',\n"
        "    'teal': '#008080',\n"
        "    'navy': '#000080',\n"
        "    'olive': '#808000',\n"
        "}\n"
    )
    assert adapter.is_data_dominant(locale_src)


def test_is_auto_generated_for_generated_file() -> None:
    adapter = PythonAdapter()
    generated = "# This file is auto-generated by protoc. Do not edit.\nimport foo\n"
    assert adapter.is_auto_generated(generated)


def test_is_auto_generated_false_for_normal_file() -> None:
    adapter = PythonAdapter()
    normal = _read(_CONTROL_FILES[0])
    assert not adapter.is_auto_generated(normal)


def test_extract_imports_returns_set_of_strings() -> None:
    adapter = PythonAdapter()
    src = "import os\nfrom pathlib import Path\nimport sys\n"
    imports = adapter.extract_imports(src)
    assert isinstance(imports, set)
    assert "os" in imports
    assert "pathlib" in imports
    assert "sys" in imports


def test_prose_line_ranges_returns_frozenset() -> None:
    adapter = PythonAdapter()
    src = "def foo():\n    '''A docstring.'''\n    return 1\n"
    result = adapter.prose_line_ranges(src)
    assert isinstance(result, frozenset)


def test_file_extensions_includes_py() -> None:
    adapter = PythonAdapter()
    assert ".py" in adapter.file_extensions
