use super::*;

#[test]
fn callable_bodies_covers_free_and_member_fns() {
    let a = CppAdapter::new();
    let src = "int add(int a, int b) {\n    return a + b;\n}\n\nstruct S {\n    int run(int x) {\n        return x * 2;\n    }\n};\n";
    let names: Vec<String> = a
        .callable_bodies(src)
        .into_iter()
        .map(|b| b.symbol)
        .collect();
    assert!(names.contains(&"add".to_string()), "{names:?}");
    assert!(names.contains(&"run".to_string()), "{names:?}");
}

fn adapter() -> CppAdapter {
    CppAdapter::new()
}

#[test]
fn system_includes_are_imports_quoted_are_not() {
    let src = "#include <vector>\n#include \"widget.hpp\"\n#include <boost/algorithm.hpp>\n";
    let imports = adapter().extract_imports(src);
    assert!(imports.contains("vector"));
    assert!(imports.contains("boost/algorithm.hpp"));
    assert!(!imports.contains("widget.hpp"));
    assert!(!imports.contains("widget"));
}

#[test]
fn quoted_include_stem_is_internal_binding() {
    let src = "#include \"foo/widget.hpp\"\n#include <vector>\n";
    let internal = adapter().internal_import_bindings(src);
    assert!(internal.contains("widget"));
    assert!(!internal.contains("vector"));
}

#[test]
fn import_spans_point_at_header_text() {
    let src = "#include <vector>\n";
    let spans = adapter().extract_imports_with_spans(src);
    assert_eq!(spans.len(), 1);
    let (spec, line, col_start, col_end) = &spans[0];
    assert_eq!(spec, "vector");
    assert_eq!(*line, 1);
    // "#include " is 9 chars, then '<' at col 9, header starts at col 10.
    assert_eq!(*col_start, 10);
    assert_eq!(*col_end, 10 + "vector".len());
}

#[test]
fn callable_definitions_capture_functions_methods_and_types() {
    let src = "class Widget { public: int compute() { return 0; } };\n\
               void Widget::run() {}\n\
               int freefn() { return 1; }\n\
               struct Point { int x; };\n";
    let defs = adapter().callable_definitions(src);
    assert!(defs.contains("Widget"));
    assert!(defs.contains("compute"));
    assert!(defs.contains("run")); // from Widget::run
    assert!(defs.contains("freefn"));
    assert!(defs.contains("Point"));
}

#[test]
fn value_bindings_capture_locals_and_params() {
    let src = "int f(int a, const std::string& b) {\n    int y = 3;\n    double z;\n}\n";
    let vals = adapter().value_bindings(src);
    assert!(vals.contains("a"));
    assert!(vals.contains("b"));
    assert!(vals.contains("y"));
    assert!(vals.contains("z"));
}

#[test]
fn data_dominant_flags_table_files() {
    let src = "static const int table[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};\n\
               static const int more[] = {11, 12, 13, 14, 15, 16, 17, 18};\n";
    assert!(adapter().is_data_dominant(src, 0.65));
    let code = "int add(int a, int b) {\n    return a + b;\n}\n";
    assert!(!adapter().is_data_dominant(code, 0.65));
}

#[test]
fn sampleable_ranges_cover_function_bodies() {
    let src = "int add(int a, int b) {\n    return a + b;\n}\n\nvoid noop() {}\n";
    let ranges = adapter().enumerate_sampleable_ranges(src);
    assert!(ranges.contains(&(1, 3)));
    assert!(ranges.iter().any(|&(s, _)| s == 5));
}

#[test]
fn prose_ranges_cover_line_and_block_comments() {
    let src = "// header\nint x = 1;\n/* multi\n   line */\nint y = 2;\n";
    let prose = adapter().prose_line_ranges(src);
    assert!(prose.contains(&1));
    assert!(prose.contains(&3));
    assert!(prose.contains(&4));
    assert!(!prose.contains(&2));
}

#[test]
fn auto_generated_detects_do_not_edit_header() {
    let gen = "// DO NOT EDIT — generated by protoc\nint x = 1;\n";
    assert!(adapter().is_auto_generated(gen, &crate::test_support::generated_markers()));
    let hand = "// a normal header\nint x = 1;\n";
    assert!(!adapter().is_auto_generated(hand, &crate::test_support::generated_markers()));
}

#[test]
fn identifier_noise_contains_keywords() {
    let a = adapter();
    assert!(a.identifier_noise().contains("class"));
    assert!(a.identifier_noise().contains("template"));
    assert_eq!(a.identifier_noise().len(), NOISE.len());
}
