use super::*;
use crate::test_support::generated_markers;

#[test]
fn header_marker_is_detected() {
    let src = "# This file was automatically generated. Do not edit.\nimport x\n";
    assert!(is_auto_generated(src, 20, &generated_markers()));
}

#[test]
fn docstring_marker_is_ignored() {
    let src = "\"\"\"generated by this provider\"\"\"\nimport x\n";
    assert!(!is_auto_generated(src, 20, &generated_markers()));
}

#[test]
fn marker_below_head_limit_is_ignored() {
    // Comment on line 21 (row 20) is past head_lines=20.
    let mut src = String::new();
    for _ in 0..20 {
        src.push('\n');
    }
    src.push_str("# auto-generated\n");
    assert!(!is_auto_generated(&src, 20, &generated_markers()));
}

#[test]
fn empty_is_not_generated() {
    assert!(!is_auto_generated("", 20, &generated_markers()));
}

#[test]
fn custom_marker_extends_detection() {
    let src = "# built by our-inhouse-codegen\nimport x\n";
    // Not caught by the default set…
    assert!(!is_auto_generated(src, 20, &generated_markers()));
    // …but a project marker catches it.
    let markers = vec!["built by our-inhouse-codegen".to_string()];
    assert!(is_auto_generated(src, 20, &markers));
}
