//! Auto-generated file detector — port of
//! `engine/argot/scoring/filters/autogenerated.py`.
//!
//! Only comment nodes (tree-sitter `comment`, i.e. lines starting with `#`)
//! are inspected, so an "auto-generated" phrase inside a docstring cannot
//! trip a false positive. The marker set is caller-supplied — it lives in
//! `[detect].generated-markers` (default [`crate::config::DEFAULT_GENERATED_MARKERS`]),
//! so users can trim or extend it.

use tree_sitter::{Node, Parser, Tree};

/// "do not edit" / "do not modify" in the first 10 lines are sufficient on
/// their own, even without a companion generated marker. This positional rule
/// is structural (not a phrase list), so it stays in code.
const STRONG_FIRST_10_MARKERS: &[&str] = &["do not edit", "do not modify"];

fn parse(source: &str) -> Tree {
    let mut parser = Parser::new();
    parser
        .set_language(&tree_sitter_python::LANGUAGE.into())
        .expect("tree-sitter python grammar loads");
    parser
        .parse(source.as_bytes(), None)
        .expect("tree-sitter parse never returns None without a timeout")
}

fn descendants<'a>(node: Node<'a>) -> Vec<Node<'a>> {
    let mut out = Vec::new();
    let mut cursor = node.walk();
    fn go<'a>(node: Node<'a>, out: &mut Vec<Node<'a>>) {
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            out.push(child);
            go(child, out);
        }
    }
    for child in node.children(&mut cursor) {
        out.push(child);
        go(child, &mut out);
    }
    out
}

/// True if the comment `text` at 0-based `line_index` carries an
/// auto-generation marker: a strong DO-NOT-EDIT marker within the first 10
/// lines, or any of the caller-supplied `markers` within `head_lines`.
/// Language-agnostic — each adapter feeds its own grammar's comment nodes so
/// block-comment styles (`//`, `/* */`) that the Python grammar can't parse are
/// still covered. `markers` are matched case-insensitively.
pub fn comment_indicates_generated(
    line_index: usize,
    text: &str,
    head_lines: usize,
    markers: &[String],
) -> bool {
    if line_index >= head_lines {
        return false;
    }
    let ll = text.to_lowercase();
    // Strong-signal check: "do not edit" / "do not modify" in first 10 lines.
    if line_index < 10 && STRONG_FIRST_10_MARKERS.iter().any(|m| ll.contains(m)) {
        return true;
    }
    // Full marker scan against the configured set.
    markers.iter().any(|m| ll.contains(&m.to_lowercase()))
}

/// True if a comment within the first `head_lines` lines carries one of
/// `markers` (case-insensitive), or a strong DO-NOT-EDIT marker within the
/// first 10 lines. False for empty input.
pub fn is_auto_generated(source: &str, head_lines: usize, markers: &[String]) -> bool {
    if source.is_empty() {
        return false;
    }

    let tree = parse(source);
    let root = tree.root_node();

    for node in descendants(root) {
        if node.kind() != "comment" {
            continue;
        }
        let line_index = node.start_position().row; // 0-based
        let text = &source[node.byte_range()];
        if comment_indicates_generated(line_index, text, head_lines, markers) {
            return true;
        }
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::default_generated_markers;

    #[test]
    fn header_marker_is_detected() {
        let src = "# This file was automatically generated. Do not edit.\nimport x\n";
        assert!(is_auto_generated(src, 20, &default_generated_markers()));
    }

    #[test]
    fn docstring_marker_is_ignored() {
        let src = "\"\"\"generated by this provider\"\"\"\nimport x\n";
        assert!(!is_auto_generated(src, 20, &default_generated_markers()));
    }

    #[test]
    fn marker_below_head_limit_is_ignored() {
        // Comment on line 21 (row 20) is past head_lines=20.
        let mut src = String::new();
        for _ in 0..20 {
            src.push('\n');
        }
        src.push_str("# auto-generated\n");
        assert!(!is_auto_generated(&src, 20, &default_generated_markers()));
    }

    #[test]
    fn empty_is_not_generated() {
        assert!(!is_auto_generated("", 20, &default_generated_markers()));
    }

    #[test]
    fn custom_marker_extends_detection() {
        let src = "# built by our-inhouse-codegen\nimport x\n";
        // Not caught by the default set…
        assert!(!is_auto_generated(src, 20, &default_generated_markers()));
        // …but a project marker catches it.
        let markers = vec!["built by our-inhouse-codegen".to_string()];
        assert!(is_auto_generated(src, 20, &markers));
    }
}
