//! Structural file filters — port of `engine/argot/scoring/filters`.
//!
//! Language- and corpus-agnostic heuristics that decide whether a file is
//! worth sampling: data-dominant tables and auto-generated headers are
//! filtered out before scoring.

pub mod autogenerated;
pub mod data_dominant;
