# engine/argot/research/signal/phase14/filters/autogenerated.py
"""Auto-generated file detector — head-window substring match, no I/O, no regex."""

from __future__ import annotations

# Generic "generated" anchors (case-insensitive substring match)
_GENERIC_MARKERS: tuple[str, ...] = (
    "auto generated",
    "auto-generated",
    "autogenerated",
    "auto_generated",
    "automatically generated",
    "automatically-generated",
    "automatically created",
    "machine generated",
    "machine-generated",
    "machine created",
    "programmatically generated",
    "computer generated",
    "computer-generated",
    "generated by",
    "generated file",
    "generated code",
    "generated from",
    "generated source",
    "this file was generated",
    "this file is generated",
    "this file has been generated",
    "this file is auto-generated",
    "this file is autogenerated",
    "this file was automatically",
    "this file is automatically",
    "this is a generated file",
    "this file was created by",
    "this module is generated",
    "@generated",
    "@autogenerated",
    "@auto-generated",
    "@ generated",
)

# DO NOT EDIT variants — strong machine-authorship signal when near the top of a file
_DO_NOT_EDIT_MARKERS: tuple[str, ...] = (
    "do not edit",
    "do not edit this file",
    "do not modify",
    "do not modify this file",
    "do not modify by hand",
    "do not change this file",
    "please do not edit",
    "please do not modify",
    "source of this file is",
)

# Tool-specific markers — explicit catches for known code generators
_TOOL_MARKERS: tuple[str, ...] = (
    "generated by protoc",
    "generated by the protocol buffer compiler",
    "generated by the grpc",
    "generated by grpc",
    "generated by swagger",
    "generated by openapi-generator",
    "generated by openapi",
    "generated by datamodel-code-generator",
    "generated by f2py",
    "generated by swig",
    "generated by thrift",
    "generated by capnp",
    "generated by antlr",
    "generated by sqlacodegen",
    "generated by pydantic",
    "generated by sqlalchemy",
    "generated by buf",
    "generated by betterproto",
    "generated by mypy-protobuf",
    "generated by graphql",
    "generated by graphene",
    "generated by ariadne",
    "generated by strawberry",
    "generated by ctypesgen",
    "generated by schemathesis",
    "generated by alembic",
    "generated by django",
    "generated by mako",
    "generated by jinja",
    "generated by black",
    "generated by mypyc",
    "generated by nanobind",
    "generated by pybind11",
    "created by transcrypt",
    "created by pythran",
    "rendered by templite",
    "output of",
    "produced by",
    "compiled from",
    "transpiled from",
)

_ALL_MARKERS: tuple[str, ...] = _GENERIC_MARKERS + _DO_NOT_EDIT_MARKERS + _TOOL_MARKERS

# "do not edit" / "do not modify" in the first 10 lines are sufficient on their own,
# even without a companion generated marker.
_STRONG_FIRST_10_MARKERS: tuple[str, ...] = ("do not edit", "do not modify")


def is_auto_generated(file_source: str, head_lines: int = 40) -> bool:
    """Return True if the file header contains an auto-generation marker.

    Args:
        file_source: Full file content as a string.
        head_lines: Number of leading lines to inspect (default 40).

    Returns:
        True if any known auto-generation marker appears (as a substring,
        case-insensitive) within the first *head_lines* lines, or if a
        strong DO-NOT-EDIT marker appears within the first 10 lines.
        False for empty / None input.
    """
    if not file_source:
        return False

    lines = file_source.splitlines()
    head = lines[:head_lines]

    # Strong-signal check: "do not edit" / "do not modify" in first 10 lines
    # alone are enough (no companion "generated" needed).
    for line in head[:10]:
        ll = line.lower()
        for marker in _STRONG_FIRST_10_MARKERS:
            if marker in ll:
                return True

    # Full marker scan over head window
    for line in head:
        ll = line.lower()
        for marker in _ALL_MARKERS:
            if marker in ll:
                return True

    return False
