//! Ignore-candidate suggestions — the *statistical* half of "what should this
//! repo not learn from".
//!
//! `argot init --suggest` surfaces directories whose files argot's structural
//! filters already skip individually — files carrying an auto-generation marker
//! (`@generated`, "Code generated by …") or dominated by static data literals
//! (fixtures, locale tables, generated lookups). When such files cluster in a
//! directory, lifting the whole directory into an explicit `.argotignore`
//! entry documents intent, speeds up fit, and catches sibling files the
//! per-file markers miss.
//!
//! The binary reports only *evidence* — counts, ratios, and the exact reason a
//! directory qualifies. The decision of what to actually ignore stays with the
//! human (or the LLM driving setup), who can also name the vendored, legacy, or
//! third-party directories a purely statistical pass cannot recognise. argot
//! proposes; the reader disposes. Nothing here embeds a framework- or
//! corpus-specific literal.

use crate::inspect::adapter_for;
use crate::scoring::adapters::{Language, LanguageAdapter};
use crate::scoring::calibration::language_for_filename;
use crate::text::read_text_lossy;
use serde::Serialize;
use std::collections::{BTreeMap, HashMap};
use std::path::Path;

/// A directory must hold at least this many supported files before it is worth
/// suggesting — a one- or two-file directory is noise, and the reader can
/// eyeball it faster than argot can justify a rule.
const MIN_DIR_FILES: usize = 3;

/// A directory qualifies when this fraction (or more) of its supported files
/// are structurally skipped (auto-generated or data-dominant). Set high on
/// purpose: below this, ignoring the directory would drop real code from the
/// voice, which is a judgement call argot must not make for the reader.
const SKIP_RATIO: f64 = 0.8;

/// Directories that are never a repo's authored source — build output, package
/// caches, vendored dependencies, tooling state. Pruned from the walk purely for
/// speed (mirrors [`crate::scoring::adapters::walk_files_with_suffix`]); their
/// files are not corpus and a big one like `target/` can hold hundreds of
/// thousands of entries. This is a traversal optimization, not a user-facing
/// scope rule — that stays in `argot:recommended` + `.argotignore`.
const SKIP_TRAVERSAL_DIRS: &[&str] = &[
    "node_modules",
    "vendor",
    "third_party",
    "third-party",
    "target",
    ".venv",
    "venv",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".turbo",
    ".gradle",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
];

/// How a directory's files break down between the two structural filters.
#[derive(Serialize, Debug, Clone, Default)]
struct DirTally {
    auto_generated: usize,
    data_dominant: usize,
    /// Files that would shape the voice if the directory were kept.
    included: usize,
}

impl DirTally {
    fn supported(&self) -> usize {
        self.auto_generated + self.data_dominant + self.included
    }
    fn skipped(&self) -> usize {
        self.auto_generated + self.data_dominant
    }
    fn skip_ratio(&self) -> f64 {
        let s = self.supported();
        if s == 0 {
            0.0
        } else {
            self.skipped() as f64 / s as f64
        }
    }
    fn qualifies(&self) -> bool {
        self.supported() >= MIN_DIR_FILES && self.skip_ratio() >= SKIP_RATIO
    }
}

/// One suggested `.argotignore` entry, with the evidence behind it.
#[derive(Serialize, Debug, Clone)]
pub struct IgnoreCandidate {
    /// Directory path relative to the repo root, forward-slashed (e.g.
    /// `src/generated`). Suitable as-is for an `.argotignore` line.
    pub path: String,
    /// Supported-language files under this directory (recursively).
    pub supported_files: usize,
    /// Of those, how many carry an auto-generation marker.
    pub auto_generated: usize,
    /// Of those, how many are dominated by static data literals.
    pub data_dominant: usize,
    /// Of those, how many are ordinary code that *would* shape the voice — the
    /// cost of ignoring the whole directory, surfaced so the reader can weigh it.
    pub included: usize,
    /// The dominant reason, for terse labelling: `auto-generated`,
    /// `data-dominant`, or `generated + data`.
    pub reason: String,
    /// A one-line human summary of the counts.
    pub detail: String,
}

/// The `argot init --suggest` report (serialized as-is by `--format json`).
#[derive(Serialize, Debug, Clone)]
pub struct IgnoreSuggestions {
    pub repo: String,
    pub candidates: Vec<IgnoreCandidate>,
}

/// Walk `repo_dir` and propose directories to add to `[exclude].paths`, based
/// solely on how densely the repo's own structural filters skip their files.
///
/// Files already excluded by the resolved path-suppression set (built-in
/// `argot:recommended` plus any existing `[exclude].paths`) are not re-counted,
/// so re-running after writing entries converges — a suggested directory stops
/// appearing once it is ignored.
pub fn suggest_ignores(repo_dir: &Path) -> IgnoreSuggestions {
    let config = crate::config::ArgotConfig::load(repo_dir);
    let path_suppressions = config.path_suppressions();
    let detect = &config.detect;
    let mut adapters: HashMap<Language, Box<dyn LanguageAdapter>> = HashMap::new();
    // Recursive per-directory tallies, keyed by forward-slashed relative path.
    // The repo root ("") is tallied but never emitted.
    let mut dirs: BTreeMap<String, DirTally> = BTreeMap::new();

    let mut stack = vec![repo_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().into_owned();
            match entry.file_type() {
                Ok(t) if t.is_dir() => {
                    // Don't descend into `.git`, argot's own model dir, or any
                    // directory the resolved suppression set (recommended +
                    // `.argotignore`) already excludes wholesale — its files
                    // aren't candidates and the subtree can be huge (build
                    // output, vendored deps). A synthetic child path probes the
                    // directory-level rule.
                    // A virtualenv (any name) is third-party Python, never the
                    // repo's voice — detect it structurally by its `pyvenv.cfg`
                    // marker rather than guessing names like `.venv-work`.
                    let build_dir = SKIP_TRAVERSAL_DIRS.contains(&name.as_str())
                        || path.join("pyvenv.cfg").is_file();
                    let excluded_dir = !build_dir
                        && path_suppressions
                            .is_suppressed_abs(&path.join(".argot-probe"), repo_dir);
                    if name != ".git" && name != ".argot" && !build_dir && !excluded_dir {
                        stack.push(path);
                    }
                }
                Ok(t) if t.is_file() => {
                    let Some(language) = language_for_filename(&name) else {
                        continue; // unsupported extension — not corpus
                    };
                    // Already handled by recommended/.argotignore — not a *new*
                    // candidate, and re-counting it would re-suggest a rule the
                    // reader already wrote.
                    if path_suppressions.is_suppressed_abs(&path, repo_dir) {
                        continue;
                    }
                    let Ok(source) = read_text_lossy(&path) else {
                        continue;
                    };
                    let adapter = adapters
                        .entry(language)
                        .or_insert_with(|| adapter_for(language));
                    let classify = |t: &mut DirTally| {
                        if adapter.is_auto_generated(&source, &detect.generated_markers) {
                            t.auto_generated += 1;
                        } else if adapter.is_data_dominant(&source, detect.data_threshold) {
                            t.data_dominant += 1;
                        } else {
                            t.included += 1;
                        }
                    };
                    // Attribute the file to every ancestor directory so a tally
                    // reflects everything beneath it.
                    for ancestor in ancestor_dirs(repo_dir, &path) {
                        classify(dirs.entry(ancestor).or_default());
                    }
                }
                _ => {}
            }
        }
    }

    let qualifying: std::collections::HashSet<String> = dirs
        .iter()
        .filter(|(_, t)| t.qualifies())
        .map(|(k, _)| k.clone())
        .collect();

    // Collapse each qualifying directory to the shallowest ancestor that adds
    // *no* extra real code — so a wholly-generated `src/gen` (and its subdirs)
    // reports once, but a `src` that merely contains `src/gen` plus real code
    // is never promoted over it (ignoring `src` would drop that real code).
    let mut targets: std::collections::HashSet<String> = qualifying
        .iter()
        .map(|k| emit_target(k, &dirs, &qualifying))
        .collect();
    // Drop any target that is an ancestor of another target: a diluted parent
    // climbs to itself, but its purer descendant is the one to suggest.
    let ancestors: Vec<String> = targets
        .iter()
        .filter(|t| {
            let prefix = format!("{t}/");
            targets.iter().any(|s| s != *t && s.starts_with(&prefix))
        })
        .cloned()
        .collect();
    for a in ancestors {
        targets.remove(&a);
    }

    let mut candidates: Vec<IgnoreCandidate> = targets
        .iter()
        .filter_map(|key| dirs.get(key).map(|t| (key, t)))
        .map(|(key, t)| IgnoreCandidate {
            path: key.clone(),
            supported_files: t.supported(),
            auto_generated: t.auto_generated,
            data_dominant: t.data_dominant,
            included: t.included,
            reason: reason_label(t),
            detail: detail_line(t),
        })
        .collect();

    // Largest first — the highest-signal directories lead.
    candidates.sort_by(|a, b| {
        b.supported_files
            .cmp(&a.supported_files)
            .then_with(|| a.path.cmp(&b.path))
    });

    IgnoreSuggestions {
        repo: repo_dir.display().to_string(),
        candidates,
    }
}

/// The forward-slashed relative keys of every directory that contains `path`,
/// excluding the repo root (`""`, never emitted) — for `repo/a/b/c.py` this is
/// `["a", "a/b"]`.
fn ancestor_dirs(repo_dir: &Path, path: &Path) -> Vec<String> {
    let rel = match path.strip_prefix(repo_dir) {
        Ok(r) => r,
        Err(_) => return Vec::new(),
    };
    let comps: Vec<String> = rel
        .parent()
        .map(|p| {
            p.components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect()
        })
        .unwrap_or_default();
    (1..=comps.len()).map(|i| comps[..i].join("/")).collect()
}

/// The parent directory key of a forward-slashed key, or `None` at the top
/// level (whose parent is the never-emitted repo root).
fn parent_key(key: &str) -> Option<&str> {
    key.rsplit_once('/').map(|(parent, _)| parent)
}

/// Climb from a qualifying directory to the shallowest ancestor that is still
/// qualifying *and introduces no additional real code* (same recursive
/// `included` count). This collapses `src/gen/inner` → `src/gen` while refusing
/// to climb into a `src` whose own real files would be swallowed.
fn emit_target(
    key: &str,
    dirs: &BTreeMap<String, DirTally>,
    qualifying: &std::collections::HashSet<String>,
) -> String {
    let mut cur = key.to_string();
    while let Some(parent) = parent_key(&cur) {
        let promotable = qualifying.contains(parent)
            && dirs.get(parent).map(|t| t.included) == dirs.get(&cur).map(|t| t.included);
        if promotable {
            cur = parent.to_string();
        } else {
            break;
        }
    }
    cur
}

fn reason_label(t: &DirTally) -> String {
    match (t.auto_generated > 0, t.data_dominant > 0) {
        (true, true) => "generated + data".to_string(),
        (false, true) => "data-dominant".to_string(),
        _ => "auto-generated".to_string(),
    }
}

fn detail_line(t: &DirTally) -> String {
    let mut parts: Vec<String> = Vec::new();
    if t.auto_generated > 0 {
        parts.push(format!("{} auto-generated", t.auto_generated));
    }
    if t.data_dominant > 0 {
        parts.push(format!("{} data-dominant", t.data_dominant));
    }
    let pct = (t.skip_ratio() * 100.0).round() as u64;
    let mut detail = format!("{} files · {} ({pct}%)", t.supported(), parts.join(", "));
    if t.included > 0 {
        detail.push_str(&format!(
            " · {} non-generated file{} here would be dropped",
            t.included,
            if t.included == 1 { "" } else { "s" }
        ));
    }
    detail
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;

    fn temp_repo(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("argot_suggest_{name}_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn py_fn(i: usize) -> String {
        format!("def compute_{i}(a, b):\n    x = a + b\n    y = x * 2\n    return y - b\n")
    }

    fn generated_py(i: usize) -> String {
        format!("# Code generated by protoc. DO NOT EDIT.\n{}", py_fn(i))
    }

    fn data_py(i: usize) -> String {
        format!(
            "TABLE_{i} = {{\n    \"a\": 1,\n    \"b\": 2,\n    \"c\": 3,\n    \"d\": 4,\n    \"e\": 5,\n    \"f\": 6,\n}}\n"
        )
    }

    #[test]
    fn generated_directory_is_suggested() {
        let dir = temp_repo("gen");
        fs::create_dir_all(dir.join("src/gen")).unwrap();
        for i in 0..4 {
            fs::write(dir.join(format!("src/gen/mod_{i}.py")), generated_py(i)).unwrap();
        }
        // Real code elsewhere must NOT be suggested.
        fs::write(dir.join("src/app.py"), py_fn(0)).unwrap();

        let s = suggest_ignores(&dir);
        assert_eq!(s.candidates.len(), 1, "only the generated dir");
        let c = &s.candidates[0];
        assert_eq!(c.path, "src/gen");
        assert_eq!(c.auto_generated, 4);
        assert_eq!(c.included, 0);
        assert_eq!(c.reason, "auto-generated");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn data_directory_is_suggested_with_reason() {
        // `locales` is not in argot:recommended, so a data-heavy one surfaces as
        // a candidate (a `fixtures/` dir, by contrast, is already excluded).
        let dir = temp_repo("data");
        fs::create_dir_all(dir.join("locales")).unwrap();
        for i in 0..3 {
            fs::write(dir.join(format!("locales/data_{i}.py")), data_py(i)).unwrap();
        }
        let s = suggest_ignores(&dir);
        let c = s
            .candidates
            .iter()
            .find(|c| c.path == "locales")
            .expect("locales candidate");
        assert_eq!(c.data_dominant, 3);
        assert_eq!(c.reason, "data-dominant");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn mixed_directory_below_ratio_is_not_suggested() {
        // 2 generated + 3 real code → 40% skipped, below SKIP_RATIO: ignoring it
        // would drop real voice, so argot stays silent and leaves the call to
        // the reader.
        let dir = temp_repo("mixed");
        fs::create_dir_all(dir.join("pkg")).unwrap();
        for i in 0..2 {
            fs::write(dir.join(format!("pkg/gen_{i}.py")), generated_py(i)).unwrap();
        }
        for i in 0..3 {
            fs::write(dir.join(format!("pkg/real_{i}.py")), py_fn(i)).unwrap();
        }
        let s = suggest_ignores(&dir);
        assert!(s.candidates.is_empty(), "mixed dir not suggested");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn topmost_qualifying_directory_wins() {
        // Every file under src/gen (and its subdirs) is generated, while src
        // also holds real code → collapse the generated subtree to src/gen
        // once, and never promote to src (which would drop the real code).
        let dir = temp_repo("topmost");
        fs::create_dir_all(dir.join("src/gen/inner")).unwrap();
        for i in 0..3 {
            fs::write(dir.join(format!("src/gen/a_{i}.py")), generated_py(i)).unwrap();
            fs::write(dir.join(format!("src/gen/inner/b_{i}.py")), generated_py(i)).unwrap();
        }
        fs::write(dir.join("src/app.py"), py_fn(0)).unwrap();
        let s = suggest_ignores(&dir);
        assert_eq!(s.candidates.len(), 1);
        assert_eq!(s.candidates[0].path, "src/gen");
        assert_eq!(s.candidates[0].supported_files, 6);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn tiny_directory_below_min_files_is_ignored() {
        let dir = temp_repo("tiny");
        fs::create_dir_all(dir.join("g")).unwrap();
        for i in 0..2 {
            fs::write(dir.join(format!("g/x_{i}.py")), generated_py(i)).unwrap();
        }
        let s = suggest_ignores(&dir);
        assert!(s.candidates.is_empty(), "2-file dir below MIN_DIR_FILES");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn build_directories_are_not_traversed() {
        // Generated files inside node_modules/target must never surface — those
        // trees are pruned wholesale (speed), and are never authored source.
        let dir = temp_repo("builddir");
        fs::create_dir_all(dir.join("node_modules/pkg")).unwrap();
        fs::create_dir_all(dir.join("target/gen")).unwrap();
        for i in 0..4 {
            fs::write(
                dir.join(format!("node_modules/pkg/m_{i}.py")),
                generated_py(i),
            )
            .unwrap();
            fs::write(dir.join(format!("target/gen/g_{i}.py")), generated_py(i)).unwrap();
        }
        let s = suggest_ignores(&dir);
        assert!(
            s.candidates.is_empty(),
            "build/dep dirs pruned, not suggested"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn virtualenvs_are_pruned_by_marker() {
        // A virtualenv with a non-standard name is still pruned via its
        // `pyvenv.cfg` marker — structural, not name-based.
        let dir = temp_repo("venv");
        fs::create_dir_all(dir.join(".venv-work/site")).unwrap();
        fs::write(dir.join(".venv-work/pyvenv.cfg"), "home = /usr/bin\n").unwrap();
        for i in 0..4 {
            fs::write(
                dir.join(format!(".venv-work/site/m_{i}.py")),
                generated_py(i),
            )
            .unwrap();
        }
        let s = suggest_ignores(&dir);
        assert!(s.candidates.is_empty(), "venv pruned by pyvenv.cfg marker");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn already_ignored_directory_is_not_resuggested() {
        let dir = temp_repo("already");
        fs::create_dir_all(dir.join("gen")).unwrap();
        for i in 0..4 {
            fs::write(dir.join(format!("gen/mod_{i}.py")), generated_py(i)).unwrap();
        }
        fs::write(dir.join("argot.toml"), "[exclude]\npaths = [\"gen/\"]\n").unwrap();
        let s = suggest_ignores(&dir);
        assert!(
            s.candidates.iter().all(|c| c.path != "gen"),
            "gen/ already ignored → not re-suggested"
        );
        let _ = fs::remove_dir_all(&dir);
    }
}
