use super::*;

#[test]
fn callable_bodies_covers_free_and_impl_fns() {
    let a = RustAdapter::new();
    let src = "fn parse(s: &str) -> usize {\n    let n = s.len();\n    n + 1\n}\n\nstruct T;\nimpl T {\n    fn run(&self, x: i32) -> i32 {\n        x * 2\n    }\n}\n";
    let names: Vec<String> = a
        .callable_bodies(src)
        .into_iter()
        .map(|b| b.symbol)
        .collect();
    assert!(names.contains(&"parse".to_string()), "{names:?}");
    assert!(names.contains(&"run".to_string()), "{names:?}");
}

#[test]
fn imports_are_crate_roots() {
    let adapter = RustAdapter::new();
    let src = "use serde::Serialize;\nuse std::collections::HashMap;\n";
    let imports = adapter.extract_imports(src);
    assert!(imports.contains("serde"));
    assert!(imports.contains("std"));
    // Crate root only, not the leaf.
    assert!(!imports.contains("Serialize"));
    assert!(!imports.contains("HashMap"));
}

#[test]
fn use_list_shares_one_crate_root() {
    let adapter = RustAdapter::new();
    let src = "use tokio::{spawn, select};\n";
    let imports = adapter.extract_imports(src);
    assert!(imports.contains("tokio"));
    assert_eq!(imports.len(), 1);
}

#[test]
fn relative_use_is_not_a_foreign_import() {
    let adapter = RustAdapter::new();
    let src = "use crate::foo::Bar;\nuse super::baz;\nuse self::inner::Thing;\n";
    let imports = adapter.extract_imports(src);
    assert!(imports.is_empty());
    // …it lands in internal bindings instead.
    let internal = adapter.internal_import_bindings(src);
    assert!(internal.contains("Bar"));
    assert!(internal.contains("baz"));
    assert!(internal.contains("Thing"));
}

#[test]
fn callable_definitions_cover_fns_and_closure_bindings() {
    let adapter = RustAdapter::new();
    let src = "fn foo() {}\n\nstruct S;\nimpl S {\n    fn bar(&self) {}\n}\n\nfn make() {\n    let baz = |x: i32| x + 1;\n}\n";
    let defs = adapter.callable_definitions(src);
    assert!(defs.contains("foo"));
    assert!(defs.contains("bar"));
    assert!(defs.contains("baz"));
}

#[test]
fn value_bindings_cover_let_and_params() {
    let adapter = RustAdapter::new();
    let src = "fn f(a: i32, b: String) {\n    let x = a;\n    let (y, z) = (1, 2);\n}\n";
    let binds = adapter.value_bindings(src);
    assert!(binds.contains("a"));
    assert!(binds.contains("b"));
    assert!(binds.contains("x"));
    assert!(binds.contains("y"));
    assert!(binds.contains("z"));
}

#[test]
fn sampleable_ranges_cover_top_level_fns_and_impl_methods() {
    let adapter = RustAdapter::new();
    let src = "fn a() {\n    let _ = 1;\n}\n\nstruct S;\nimpl S {\n    fn b(&self) {\n        let _ = 2;\n    }\n}\n";
    let ranges = adapter.enumerate_sampleable_ranges(src);
    // top-level `a` plus method `b`.
    assert_eq!(ranges.len(), 2);
}

#[test]
fn generated_header_is_detected() {
    let adapter = RustAdapter::new();
    let gen = "// @generated by prost-build\n\npub struct M {}\n";
    assert!(adapter.is_auto_generated(gen, &crate::test_support::generated_markers()));
    let marker = "// Code generated by tonic. DO NOT EDIT.\n\npub fn f() {}\n";
    assert!(adapter.is_auto_generated(marker, &crate::test_support::generated_markers()));
    let hand = "// A normal comment.\n\npub fn f() {}\n";
    assert!(!adapter.is_auto_generated(hand, &crate::test_support::generated_markers()));
}

#[test]
fn top_level_data_tables_are_data_dominant() {
    let adapter = RustAdapter::new();
    let src = "static CITIES: [&str; 5] = [\n    \"a\",\n    \"b\",\n    \"c\",\n    \"d\",\n    \"e\",\n];\n";
    assert!(adapter.is_data_dominant(src, 0.65));
    assert!(!adapter.data_literal_lines(src).is_empty());
}

#[test]
fn code_is_not_data_dominant() {
    let adapter = RustAdapter::new();
    let src = "fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n";
    assert!(!adapter.is_data_dominant(src, 0.65));
}

#[test]
fn prose_ranges_cover_line_and_block_comments() {
    let adapter = RustAdapter::new();
    let src = "// line\nfn f() {}\n/* block */\n";
    let rows = adapter.prose_line_ranges(src);
    assert!(rows.contains(&1));
    assert!(rows.contains(&3));
}

#[test]
fn identifier_noise_contains_keywords_and_builtins() {
    let adapter = RustAdapter::new();
    assert!(adapter.identifier_noise().contains("fn"));
    assert!(adapter.identifier_noise().contains("impl"));
    assert!(adapter.identifier_noise().contains("Vec"));
    assert_eq!(adapter.identifier_noise().len(), NOISE.len());
}
