//! `SequentialImportBpeScorer` — the production composite scorer.
//!
//! Port of `engine/argot/scoring/scorers/sequential_import_bpe.py`. Composes:
//! typicality short-circuit → import-graph stage → BPE surprise stage →
//! call-receiver contribution → multi-reason resolution. Evidence collection
//! is deferred (returns `None`) until the evidence layer is ported.

use crate::bpe::BpeTokenizer;
use crate::scoring::adapters::LanguageAdapter;
use crate::scoring::bpe_scorer::BpeScorer;
use crate::scoring::call_receiver::{CallReceiverScorer, RarityWeighting};
use crate::scoring::conventions::ConventionScorer;
use crate::scoring::evidence::types::{Evidence, EvidenceCorpus, SourceSpan};
use crate::scoring::evidence::{
    collect_bpe_evidence, collect_call_receiver_evidence, collect_import_evidence,
};
use crate::scoring::import_graph::ImportGraphScorer;
use crate::scoring::model::LanguageModel;
use crate::scoring::shape_primitive::ShapePrimitiveRegistry;
use crate::scoring::typicality::TypicalityModel;
use crate::text::splitlines_keepends;
use anyhow::Result;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

const EPSILON: f64 = 1e-7;
const IMPORT_THRESHOLD: f64 = 1.0;
/// A hunk whose non-blank rows lie mostly inside the host file's static
/// data-literal spans is data, not phrasing — skipped like the file-level
/// data filters, but at row granularity (same 0.65 share the file-level
/// data-dominant filter uses). Code rows in data-heavy files stay judged.
const DATA_ROW_SHARE_CUTOFF: f64 = 0.65;

/// Winning reason for a scored hunk (`Reason` literal in Python).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    Import,
    CallReceiver,
    Bpe,
    Convention,
    None,
    AutoGenerated,
    Atypical,
    AtypicalFile,
}

impl Reason {
    pub fn as_str(&self) -> &'static str {
        match self {
            Reason::Import => "import",
            Reason::CallReceiver => "call_receiver",
            Reason::Bpe => "bpe",
            Reason::Convention => "convention",
            Reason::None => "none",
            Reason::AutoGenerated => "auto_generated",
            Reason::Atypical => "atypical",
            Reason::AtypicalFile => "atypical_file",
        }
    }
}

/// Raw per-stage scores.
#[derive(Debug, Clone, Copy)]
pub struct StageScores {
    pub import_score: f64,
    pub bpe_score: f64,
    pub call_receiver_contribution: f64,
    /// Convention-rarity bonus (0.0 unless a convention cleared its bar).
    pub convention_contribution: f64,
}

/// One hunk's verdict.
#[derive(Debug, Clone)]
pub struct ScoredHunk {
    pub score: f64,
    pub threshold: f64,
    pub flagged: bool,
    pub reason: Reason,
    pub stages: StageScores,
    /// Per-reason evidence for the winning reason, populated by the collectors
    /// when the scorer was built with an [`EvidenceCorpus`]; `None` otherwise
    /// (and for non-flagged / short-circuited hunks).
    pub evidence: Option<Evidence>,
}

/// Blank the 1-indexed prose lines in `ranges`, preserving line count
/// (`_blank_prose_lines`).
fn blank_prose_lines(src: &str, ranges: &HashSet<usize>) -> String {
    if ranges.is_empty() {
        return src.to_string();
    }
    let lines = splitlines_keepends(src);
    let mut result = String::with_capacity(src.len());
    for (i, line) in lines.iter().enumerate() {
        let ln = i + 1;
        if ranges.contains(&ln) {
            if line.ends_with('\n') {
                result.push('\n');
            }
        } else {
            result.push_str(line);
        }
    }
    result
}

/// Construction config (check-time: threshold + snapshot provided).
pub struct SequentialConfig {
    pub bpe_threshold: f64,
    pub enable_typicality: bool,
    pub exclude_data_dominant: bool,
    pub call_receiver_alpha: f64,
    pub call_receiver_cap: usize,
    pub call_receiver_root_bonus: f64,
    pub call_receiver_n_clusters: usize,
    pub call_receiver_cluster_seed: u64,
    pub call_receiver_cluster_bonus: f64,
    pub call_receiver_cluster_rare_threshold: usize,
    pub call_receiver_cluster_size_min: usize,
    /// Rarity weighting for the cluster branches (default `Off`).
    pub call_receiver_rarity_weighting: RarityWeighting,
    /// Registered shape-primitive names to enable (empty = none).
    pub call_receiver_shape_primitive_names: Vec<String>,
    /// Parse-error host fallback: when true, a hunk whose bare parse has root
    /// errors gets its callees from its region within the host AST instead of
    /// contributing 0. Production check runs with this ON: git picks hunk
    /// boundaries, not the parser, so mid-construct fragments are the norm at
    /// check time, and calibration always applied the fallback on its side.
    /// An earlier FP flood was measured with a forced cluster-rare rule;
    /// production auto-detects that rule per corpus. The bench's catalog mode
    /// keeps it off for baseline continuity.
    pub call_receiver_parse_error_host_fallback: bool,
    /// Fitted convention-rarity model (frequencies + calibrated bars);
    /// `None` disables the stage.
    pub conventions: Option<crate::scoring::model::ConventionModel>,
    /// Score added when a convention clears its bar (the stage's whole
    /// contribution — features do not stack).
    pub convention_bonus: f64,
    pub import_modules: Vec<String>,
    pub import_module_prefixes: Vec<String>,
    /// Pre-computed evidence corpus parsed from the config's `evidence_corpus`
    /// block. `None` disables evidence collection (matching a config without
    /// the block); the scorer then behaves exactly as before.
    pub evidence_corpus: Option<EvidenceCorpus>,
}

/// Per-file derived state that every hunk of the same file shares. Hunks
/// arrive batched per file, so a single-entry cache keyed by a content hash
/// removes the repeated file parses (bindings, data rows, prose ranges).
/// Pure memoization — scoring is byte-identical with or without it.
#[derive(Default)]
struct FileDerivedCache {
    key: u64,
    data_rows: HashSet<usize>,
    prose_rows: HashSet<usize>,
    file_bindings: crate::scoring::call_receiver::LocalBindings,
    /// Whether the file reaches into a module foreign to the repo (a foreign
    /// namespace-qualified or bare-foreign callee anywhere in the file) —
    /// the file-level half of the call-receiver foreign-context gate.
    foreign_reach: bool,
}

fn content_key(source: &str) -> u64 {
    use std::hash::{Hash, Hasher};
    let mut h = std::collections::hash_map::DefaultHasher::new();
    source.hash(&mut h);
    h.finish()
}

pub struct SequentialImportBpeScorer {
    adapter: Box<dyn LanguageAdapter>,
    /// Callable names defined anywhere in the change being checked (all
    /// files of the changeset) — new code naming its own neighbourhood.
    changeset_bindings: HashSet<String>,
    /// Single-entry per-file cache (see [`FileDerivedCache`]).
    file_cache: Option<FileDerivedCache>,
    typicality: Option<TypicalityModel>,
    import_scorer: ImportGraphScorer,
    bpe: BpeScorer,
    call_receiver: Option<CallReceiverScorer>,
    conventions: Option<ConventionScorer>,
    convention_bonus: f64,
    root_bonus: f64,
    cluster_bonus: f64,
    parse_error_host_fallback: bool,
    pub bpe_threshold: f64,
    evidence_corpus: Option<EvidenceCorpus>,
}

impl SequentialImportBpeScorer {
    /// Build a check-time scorer: BPE threshold and import-module snapshot come
    /// from `scorer-config.json`. `repo_files` are (path, source) pairs from
    /// repo-corpus.txt.
    pub fn from_config(
        repo_files: &[(PathBuf, String)],
        generic_baseline_json: &[u8],
        adapter: Box<dyn LanguageAdapter>,
        cfg: SequentialConfig,
    ) -> Result<Self> {
        let language = adapter.language();

        // exclude_data_dominant: filter the corpus once; the filtered list
        // feeds both the BPE corpus and the call-receiver.
        let filtered: Vec<(PathBuf, String)> = if cfg.exclude_data_dominant {
            repo_files
                .iter()
                .filter(|(_, src)| !adapter.is_data_dominant(src))
                .cloned()
                .collect()
        } else {
            repo_files.to_vec()
        };
        let corpus = if filtered.is_empty() {
            repo_files
        } else {
            &filtered
        };

        let typicality = if cfg.enable_typicality {
            Some(TypicalityModel::new(language))
        } else {
            None
        };

        let mut import_scorer = ImportGraphScorer::new();
        import_scorer.load_snapshot(
            cfg.import_modules.clone(),
            cfg.import_module_prefixes.clone(),
        );

        let sources: Vec<String> = corpus.iter().map(|(_, s)| s.clone()).collect();
        let bpe = BpeScorer::new(BpeTokenizer::load(), generic_baseline_json, &sources)?;

        let call_receiver = if cfg.call_receiver_alpha > 0.0 {
            Some(
                CallReceiverScorer::new(
                    corpus,
                    language,
                    cfg.call_receiver_alpha,
                    cfg.call_receiver_cap,
                    adapter.as_ref(),
                    cfg.call_receiver_n_clusters,
                    cfg.call_receiver_cluster_seed,
                    cfg.call_receiver_cluster_rare_threshold,
                    cfg.call_receiver_cluster_size_min,
                )
                .map_err(anyhow::Error::msg)?
                .with_rarity_weighting(cfg.call_receiver_rarity_weighting)
                .with_shape_primitives(
                    ShapePrimitiveRegistry::with_builtins()
                        .build(&cfg.call_receiver_shape_primitive_names)
                        .map_err(anyhow::Error::msg)?,
                    corpus,
                    adapter.as_ref(),
                ),
            )
        } else {
            None
        };

        let conventions = cfg.conventions.map(|m| ConventionScorer::new(m, language));

        Ok(Self {
            adapter,
            changeset_bindings: HashSet::new(),
            file_cache: None,
            typicality,
            import_scorer,
            bpe,
            call_receiver,
            conventions,
            convention_bonus: cfg.convention_bonus,
            root_bonus: cfg.call_receiver_root_bonus,
            cluster_bonus: cfg.call_receiver_cluster_bonus,
            parse_error_host_fallback: cfg.call_receiver_parse_error_host_fallback,
            bpe_threshold: cfg.bpe_threshold,
            evidence_corpus: cfg.evidence_corpus,
        })
    }

    /// Build a check-time scorer from the fit-time [`LanguageModel`] snapshot
    /// instead of re-reading the corpus. Attestation, cluster membership, and
    /// the repo BPE token distribution are pinned to fit time, so new code is
    /// scored against the voice as learned — it cannot attest itself (#79).
    ///
    /// Shape primitives are not supported on this path: their per-cluster
    /// baselines are corpus-fitted state that the artifact does not carry
    /// (they are default-off research substrate; the bench builds them from
    /// a live corpus).
    pub fn from_model(
        model: &LanguageModel,
        generic_baseline_json: &[u8],
        adapter: Box<dyn LanguageAdapter>,
        cfg: SequentialConfig,
    ) -> Result<Self> {
        if !cfg.call_receiver_shape_primitive_names.is_empty() {
            anyhow::bail!("shape primitives require a live corpus, not a model snapshot");
        }
        let language = adapter.language();

        let typicality = if cfg.enable_typicality {
            Some(TypicalityModel::new(language))
        } else {
            None
        };

        let mut import_scorer = ImportGraphScorer::new();
        import_scorer.load_snapshot(
            cfg.import_modules.clone(),
            cfg.import_module_prefixes.clone(),
        );

        let bpe = BpeScorer::from_stats(BpeTokenizer::load(), generic_baseline_json, &model.bpe)?;

        let call_receiver = if cfg.call_receiver_alpha > 0.0 {
            Some(
                CallReceiverScorer::from_model(
                    &model.call_receiver,
                    language,
                    cfg.call_receiver_alpha,
                    cfg.call_receiver_cap,
                    cfg.call_receiver_cluster_rare_threshold,
                    cfg.call_receiver_cluster_size_min,
                )
                .map_err(anyhow::Error::msg)?
                .with_rarity_weighting(cfg.call_receiver_rarity_weighting),
            )
        } else {
            None
        };

        let conventions = model
            .conventions
            .clone()
            .map(|m| ConventionScorer::new(m, language));

        Ok(Self {
            adapter,
            changeset_bindings: HashSet::new(),
            file_cache: None,
            typicality,
            import_scorer,
            bpe,
            call_receiver,
            conventions,
            convention_bonus: cfg.convention_bonus,
            root_bonus: cfg.call_receiver_root_bonus,
            cluster_bonus: cfg.call_receiver_cluster_bonus,
            parse_error_host_fallback: cfg.call_receiver_parse_error_host_fallback,
            bpe_threshold: cfg.bpe_threshold,
            evidence_corpus: cfg.evidence_corpus,
        })
    }

    /// Install the changeset-wide callable definitions for this check run —
    /// names any file in the change defines. Cleared by passing an empty set.
    pub fn set_changeset_bindings(&mut self, bindings: HashSet<String>) {
        self.changeset_bindings = bindings;
    }

    /// Whether `path` (repo-relative) was in the fit corpus. A path the model
    /// never saw is a new file, judged by `check` against the new-file threshold
    /// rather than the existing-file one (issue #92 new-file flooding). Falls
    /// back to `true` (treat as existing) when there is no call-receiver model,
    /// so a call-receiver-less config keeps its single-threshold behaviour.
    pub fn is_fit_file(&self, path: &std::path::Path) -> bool {
        self.call_receiver
            .as_ref()
            .is_none_or(|cr| cr.knows_file(path))
    }

    /// Per-primitive fire counts from the call-receiver (bench observability).
    pub fn primitive_fire_counts(&self) -> Option<&std::collections::HashMap<String, usize>> {
        self.call_receiver
            .as_ref()
            .map(|cr| &cr.primitive_fire_count)
    }

    /// The per-file derived state for `source`, recomputing only when the
    /// content differs from the cached entry.
    fn file_derived(&mut self, source: &str) -> &FileDerivedCache {
        let key = content_key(source);
        let hit = self.file_cache.as_ref().is_some_and(|c| c.key == key);
        if !hit {
            let mut file_bindings = crate::scoring::call_receiver::LocalBindings::default();
            file_bindings
                .callables
                .extend(self.adapter.callable_definitions(source));
            file_bindings
                .callables
                .extend(self.adapter.internal_import_bindings(source));
            file_bindings
                .values
                .extend(self.adapter.value_bindings(source));
            // File-level foreign reach: the change's callable/value bindings
            // (host file + changeset) mark the code's own new symbols, so only
            // genuinely foreign callees count.
            let mut reach_bindings = file_bindings.clone();
            reach_bindings
                .callables
                .extend(self.changeset_bindings.iter().cloned());
            let foreign_reach = self
                .call_receiver
                .as_ref()
                .is_some_and(|cr| cr.file_reaches_foreign(source, &reach_bindings));
            self.file_cache = Some(FileDerivedCache {
                key,
                data_rows: self.adapter.data_literal_lines(source),
                prose_rows: self.adapter.prose_line_ranges(source),
                file_bindings,
                foreign_reach,
            });
        }
        self.file_cache.as_ref().expect("just populated")
    }

    /// Share of the hunk's non-blank rows that fall inside the host file's
    /// static data-literal spans (1-indexed inclusive hunk bounds). 0.0 when
    /// the hunk has no non-blank rows or the file has no data spans.
    fn hunk_data_row_share(
        &mut self,
        hunk_content: &str,
        file_source: &str,
        hunk_start_line: usize,
        hunk_end_line: usize,
    ) -> f64 {
        let data_rows = &self.file_derived(file_source).data_rows;
        if data_rows.is_empty() {
            return 0.0;
        }
        let mut nonblank = 0usize;
        let mut in_data = 0usize;
        for (i, line) in splitlines_keepends(hunk_content).iter().enumerate() {
            if line.trim().is_empty() {
                continue;
            }
            let file_line = hunk_start_line + i;
            if file_line > hunk_end_line {
                break;
            }
            nonblank += 1;
            if data_rows.contains(&file_line) {
                in_data += 1;
            }
        }
        if nonblank == 0 {
            0.0
        } else {
            in_data as f64 / nonblank as f64
        }
    }

    /// Whether `source` (a full file) declares an import the fit corpus never
    /// used — a foreign dependency at the file level. Backs the call-receiver
    /// foreign-context gate: a bare unattested callee (`event_base_new`) is
    /// foreign only when its file pulls a foreign `#include`/import, which can
    /// sit in a different hunk than the call itself.
    fn file_has_foreign_import(&self, source: Option<&str>) -> bool {
        match source {
            Some(src) => self
                .adapter
                .extract_imports(src)
                .into_iter()
                .any(|spec| self.import_scorer.is_foreign(&spec)),
            None => false,
        }
    }

    fn zero_stage(reason: Reason, threshold: f64) -> ScoredHunk {
        ScoredHunk {
            score: 0.0,
            threshold,
            flagged: false,
            reason,
            stages: StageScores {
                import_score: 0.0,
                bpe_score: 0.0,
                call_receiver_contribution: 0.0,
                convention_contribution: 0.0,
            },
            evidence: None,
        }
    }

    /// Score a hunk through both stages (`score_hunk`). `file_path` is `None`
    /// at check time (non-cluster contribution); the bench passes it.
    ///
    /// When `file_source` + line bounds are given, they double as the
    /// parse-error host context: a hunk whose bare parse has root errors gets
    /// its callees from its region within the file AST instead of contributing 0.
    pub fn score_hunk(
        &mut self,
        hunk_content: &str,
        file_source: Option<&str>,
        hunk_start_line: Option<usize>,
        hunk_end_line: Option<usize>,
        file_path: Option<&Path>,
    ) -> ScoredHunk {
        self.score_hunk_with_host_context(
            hunk_content,
            file_source,
            hunk_start_line,
            hunk_end_line,
            file_path,
            None,
        )
    }

    /// [`Self::score_hunk`] with an explicit host context for the parse-error
    /// callee fallback — used by the benchmark's catalog fixtures,
    /// where the synthesized hunk-in-host content must NOT be passed as
    /// `file_source` (it would poison prose-blanking and file-level
    /// typicality) but should still back callee extraction on parse failure.
    /// `host_context` is `(host_source, start_line, end_line)`, 1-indexed
    /// inclusive.
    pub fn score_hunk_with_host_context(
        &mut self,
        hunk_content: &str,
        file_source: Option<&str>,
        hunk_start_line: Option<usize>,
        hunk_end_line: Option<usize>,
        file_path: Option<&Path>,
        host_context: Option<(&str, usize, usize)>,
    ) -> ScoredHunk {
        // 1. Typicality / auto-generated short-circuits.
        if let Some(typ) = &self.typicality {
            if typ.is_atypical(hunk_content).0 {
                return Self::zero_stage(Reason::Atypical, self.bpe_threshold);
            }
        } else if let Some(fs) = file_source {
            if self.adapter.is_auto_generated(fs) {
                return Self::zero_stage(Reason::AutoGenerated, self.bpe_threshold);
            }
        }

        // 1b. Row-granular data scope: a hunk sitting mostly inside the host
        // file's data-literal spans is data, not phrasing. Replaces the old
        // file-level vetoes (data-dominant batch drop, atypical-file
        // fallback), which also silenced *code* planted in data-heavy files —
        // the exact class of subtle break this scorer exists to judge.
        if let (Some(fs), Some(hs), Some(he)) = (file_source, hunk_start_line, hunk_end_line) {
            if self.hunk_data_row_share(hunk_content, fs, hs, he) > DATA_ROW_SHARE_CUTOFF {
                return Self::zero_stage(Reason::AtypicalFile, self.bpe_threshold);
            }
        }

        // 2. Import stage (over the hunk's own imports).
        let foreign: HashSet<String> = self
            .adapter
            .extract_imports(hunk_content)
            .into_iter()
            .filter(|spec| self.import_scorer.is_foreign(spec))
            .collect();
        let import_score = foreign.len() as f64;

        // 3. BPE stage (optionally blank prose lines within the hunk span).
        let mut bpe_input = hunk_content.to_string();
        if let (Some(fs), Some(hs), Some(he)) = (file_source, hunk_start_line, hunk_end_line) {
            let file_prose = &self.file_derived(fs).prose_rows;
            let hunk_prose_local: HashSet<usize> = file_prose
                .iter()
                .copied()
                .filter(|&ln| hs <= ln && ln <= he)
                .map(|ln| ln - hs + 1)
                .collect();
            bpe_input = blank_prose_lines(hunk_content, &hunk_prose_local);
        }
        let bpe_score = self.bpe.bpe_score(&bpe_input);

        // 4. Call-receiver contribution (always computed when configured).
        // Parse-error host context: an explicit one wins; otherwise the file
        // source + hunk bounds serve as the host (real-PR path). Gated by the
        // parse-error host fallback flag (default off — see SequentialConfig).
        let cr_host_context: Option<(&str, usize, usize)> = if self.parse_error_host_fallback {
            host_context.or(match (file_source, hunk_start_line, hunk_end_line) {
                (Some(fs), Some(hs), Some(he)) => Some((fs, hs, he)),
                _ => None,
            })
        } else {
            None
        };
        // Local-binding attestation: what this change defines (host file or
        // fragment) plus what it imports from repo-internal paths plus the
        // changeset-wide definitions — its own neighbourhood, not foreign.
        // Value bindings (destructured names, consts, parameters) attest
        // bare calls only; callables and import bindings also attest via
        // their root.
        let binding_source: &str = file_source
            .or(host_context.map(|(h, _, _)| h))
            .unwrap_or(hunk_content);
        let derived = self.file_derived(binding_source);
        let file_foreign_reach = derived.foreign_reach;
        let mut local_bindings = derived.file_bindings.clone();
        local_bindings
            .callables
            .extend(self.changeset_bindings.iter().cloned());

        let contribution = if let Some(cr) = &mut self.call_receiver {
            let alpha = cr.alpha;
            let cap = cr.cap as f64;
            match file_path {
                Some(_) => cr.weighted_contribution_for_file(
                    hunk_content,
                    file_path,
                    alpha,
                    self.root_bonus,
                    self.cluster_bonus,
                    cap,
                    file_source,
                    cr_host_context,
                    &local_bindings,
                ),
                None => cr.weighted_contribution(
                    hunk_content,
                    alpha,
                    self.root_bonus,
                    cap,
                    cr_host_context,
                    &local_bindings,
                ),
            }
        } else {
            0.0
        };

        // 4c. Convention rarity: a construct or naming shape the corpus does
        // not use, past its calibrated bar. Shares the phase-D host-context
        // discipline (host region consulted only on bare-parse errors).
        let convention_contribution = match &self.conventions {
            Some(conv) => {
                let host: Option<(&str, usize, usize)> =
                    host_context.or(match (file_source, hunk_start_line, hunk_end_line) {
                        (Some(fs), Some(hs), Some(he)) => Some((fs, hs, he)),
                        _ => None,
                    });
                if conv.fires(&conv.scores(hunk_content, host)) {
                    self.convention_bonus
                } else {
                    0.0
                }
            }
            None => 0.0,
        };

        let stages = StageScores {
            import_score,
            bpe_score,
            call_receiver_contribution: contribution,
            convention_contribution,
        };

        // 5. Multi-reason resolution.
        let adjusted_bpe = bpe_score + contribution;
        let cr_active = self.call_receiver.is_some();
        let bpe_side_score = if cr_active { adjusted_bpe } else { bpe_score };

        let import_fired = import_score >= IMPORT_THRESHOLD;
        let bpe_fired = bpe_score > self.bpe_threshold;
        // Foreign-context gate for the call-receiver reason: a call-receiver
        // contribution may flag a hunk on its own only when the hunk reaches
        // into a module foreign to the repo — a foreign import in the hunk or
        // its file, or an unattested callee whose namespace the repo has never
        // used. A bare unattested callee with no foreign association is the
        // codebase's own new code (a fresh local function/method), not foreign
        // voice, and must not cry wolf. Evaluated lazily, only when the
        // contribution would otherwise win.
        let cr_would_fire = cr_active && !bpe_fired && bpe_side_score > self.bpe_threshold;
        let cr_fired = cr_would_fire
            && (import_score >= IMPORT_THRESHOLD
                || file_foreign_reach
                || self.file_has_foreign_import(file_source.or(host_context.map(|(h, _, _)| h))));
        let conv_side_score = bpe_score + convention_contribution;
        let conv_fired =
            convention_contribution > 0.0 && !bpe_fired && conv_side_score > self.bpe_threshold;
        let denom = self.bpe_threshold.max(EPSILON);

        // (reason, score, threshold, ratio)
        let mut candidates: Vec<(Reason, f64, f64, f64)> = Vec::new();
        if import_fired {
            candidates.push((
                Reason::Import,
                import_score,
                IMPORT_THRESHOLD,
                import_score / IMPORT_THRESHOLD,
            ));
        }
        if bpe_fired {
            candidates.push((
                Reason::Bpe,
                bpe_score,
                self.bpe_threshold,
                bpe_score / denom,
            ));
        }
        if cr_fired {
            candidates.push((
                Reason::CallReceiver,
                adjusted_bpe,
                self.bpe_threshold,
                adjusted_bpe / denom,
            ));
        }
        if conv_fired {
            candidates.push((
                Reason::Convention,
                conv_side_score,
                self.bpe_threshold,
                conv_side_score / denom,
            ));
        }

        if !candidates.is_empty() {
            let tiebreak = |r: Reason| match r {
                Reason::CallReceiver => 0,
                Reason::Import => 1,
                Reason::Convention => 2,
                _ => 3,
            };
            candidates.sort_by(|a, b| {
                b.3.partial_cmp(&a.3)
                    .unwrap_or(std::cmp::Ordering::Equal)
                    .then_with(|| tiebreak(a.0).cmp(&tiebreak(b.0)))
            });
            let winner = candidates[0];
            let evidence = self.collect_evidence(
                winner.0,
                hunk_content,
                &bpe_input,
                file_path,
                file_source,
                &foreign,
                &local_bindings,
            );
            return ScoredHunk {
                score: winner.1,
                threshold: winner.2,
                flagged: true,
                reason: winner.0,
                stages,
                evidence,
            };
        }

        ScoredHunk {
            score: bpe_side_score,
            threshold: self.bpe_threshold,
            flagged: false,
            reason: Reason::None,
            stages,
            evidence: None,
        }
    }

    /// Dispatch to the per-reason evidence collector after a hunk fires
    /// (`_collect_evidence`). Returns `None` when the scorer wasn't built with
    /// an [`EvidenceCorpus`] — the renderer then skips the evidence block,
    /// matching the unflagged path.
    #[allow(clippy::too_many_arguments)]
    fn collect_evidence(
        &self,
        winning_reason: Reason,
        hunk_content: &str,
        bpe_input: &str,
        file_path: Option<&Path>,
        file_source: Option<&str>,
        foreign: &HashSet<String>,
        local_bindings: &crate::scoring::call_receiver::LocalBindings,
    ) -> Option<Evidence> {
        let corpus = self.evidence_corpus.as_ref()?;
        match winning_reason {
            Reason::Import => {
                // Preserve the order the imports appear in the hunk, and capture
                // each foreign specifier's first-occurrence span so the formatter
                // can annotate (`msgspec (L7)`), the truncator can keep the line
                // visible, and the renderer can draw carets.
                let imports_with_spans = self.adapter.extract_imports_with_spans(hunk_content);
                let mut ordered_foreign: Vec<String> = Vec::new();
                let mut seen_foreign: HashSet<String> = HashSet::new();
                let mut foreign_spans: Vec<(String, SourceSpan)> = Vec::new();
                for (spec, line, col_start, col_end) in imports_with_spans {
                    if !foreign.contains(&spec) {
                        continue;
                    }
                    if seen_foreign.insert(spec.clone()) {
                        ordered_foreign.push(spec.clone());
                        foreign_spans.push((
                            spec,
                            SourceSpan {
                                line,
                                col_start,
                                col_end,
                            },
                        ));
                    }
                }
                Some(Evidence::Import(collect_import_evidence(
                    ordered_foreign,
                    foreign_spans,
                    corpus,
                )))
            }
            Reason::CallReceiver => {
                let cr = self.call_receiver.as_ref()?;
                let cluster_id = cr.cluster_id_for_hunk_file(file_path, file_source);
                Some(Evidence::CallReceiver(collect_call_receiver_evidence(
                    cr.distinct_unattested_excluding(hunk_content, local_bindings),
                    cluster_id,
                    corpus,
                )))
            }
            Reason::Bpe => {
                let score_fn = |id: u32| self.bpe.token_surprise(id);
                let is_meaningful = |id: u32| self.bpe.is_meaningful_token_id(id);
                Some(Evidence::Bpe(collect_bpe_evidence(
                    bpe_input,
                    self.bpe.tokenizer(),
                    &score_fn,
                    Some(&is_meaningful),
                    corpus,
                )))
            }
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scoring::adapters::python::PythonAdapter;
    use crate::train::GENERIC_BASELINE_JSON;

    fn config(threshold: f64) -> SequentialConfig {
        SequentialConfig {
            bpe_threshold: threshold,
            enable_typicality: true,
            exclude_data_dominant: true,
            call_receiver_alpha: 2.0,
            call_receiver_cap: 5,
            call_receiver_root_bonus: 2.0,
            call_receiver_n_clusters: 2,
            call_receiver_cluster_seed: 0,
            call_receiver_cluster_bonus: 5.0,
            call_receiver_cluster_rare_threshold: 0,
            call_receiver_cluster_size_min: 0,
            call_receiver_rarity_weighting: RarityWeighting::Off,
            call_receiver_shape_primitive_names: Vec::new(),
            call_receiver_parse_error_host_fallback: false,
            conventions: None,
            convention_bonus: 0.0,
            import_modules: vec!["math".to_string()],
            import_module_prefixes: Vec::new(),
            evidence_corpus: None,
        }
    }

    fn toy_scorer() -> SequentialImportBpeScorer {
        let files: Vec<(PathBuf, String)> = (0..4)
            .map(|i| {
                (
                    PathBuf::from(format!("m{i}.py")),
                    "import math\n\n\ndef mean(xs):\n    total = math.fsum(xs)\n    return total / len(xs)\n".to_string(),
                )
            })
            .collect();
        SequentialImportBpeScorer::from_config(
            &files,
            GENERIC_BASELINE_JSON,
            Box::new(PythonAdapter::new()),
            config(100.0),
        )
        .unwrap()
    }

    /// The row-granular data gate: a hunk sitting inside the host file's
    /// data-literal span is skipped, while a *code* hunk in the very same
    /// data-dominant file is still scored (the old file-level vetoes zeroed
    /// both).
    #[test]
    fn data_rows_are_skipped_but_code_rows_in_data_files_are_scored() {
        let mut scorer = toy_scorer();
        // A data-dominant host: one long table plus one function.
        let mut file = String::from("NAMES = [\n");
        for i in 0..40 {
            file.push_str(&format!("    \"entry_{i}\",\n"));
        }
        file.push_str("]\n\n\ndef helper(xs):\n    acc = process_batch(xs)\n    return acc\n");
        let file_lines: Vec<&str> = file.lines().collect();

        // Two rows inside the table — small enough to evade the hunk-level
        // typicality gate, previously only caught by the file-level fallback.
        let data_hunk = file_lines[4..6].join("\n");
        let scored = scorer.score_hunk(&data_hunk, Some(&file), Some(5), Some(6), None);
        assert_eq!(scored.reason, Reason::AtypicalFile, "data rows skipped");
        assert_eq!(scored.score, 0.0);

        // The function at the bottom of the same file: judged, not vetoed.
        let n = file_lines.len();
        let code_hunk = file_lines[n - 3..n].join("\n");
        let scored = scorer.score_hunk(&code_hunk, Some(&file), Some(n - 2), Some(n), None);
        assert!(
            !matches!(scored.reason, Reason::Atypical | Reason::AtypicalFile),
            "code hunk in a data file must be judged, got {:?}",
            scored.reason
        );
        assert!(
            scored.stages.call_receiver_contribution > 0.0,
            "unattested callee in the planted code fires: {:?}",
            scored.stages
        );
    }

    /// Hunks without file context (bare fragments) are unaffected by the gate.
    #[test]
    fn bare_hunks_skip_the_data_row_gate() {
        let mut scorer = toy_scorer();
        let scored = scorer.score_hunk("def f(x):\n    return x + 1", None, None, None, None);
        assert!(!matches!(
            scored.reason,
            Reason::Atypical | Reason::AtypicalFile
        ));
    }

    /// Local-binding attestation: callees the change itself defines (in the
    /// host file or the changeset) or imports from repo-internal paths do not
    /// count as unattested — only truly neighbourhood-less callees fire.
    #[test]
    fn locally_bound_callees_are_not_foreign() {
        let mut scorer = toy_scorer();

        // Self-defined: the hunk defines process_batch and calls it.
        let hunk =
            "def process_batch(xs):\n    return xs\n\n\ndef run(xs):\n    return process_batch(xs)";
        let scored = scorer.score_hunk(hunk, None, None, None, None);
        assert_eq!(
            scored.stages.call_receiver_contribution, 0.0,
            "self-defined callee attested: {:?}",
            scored.stages
        );

        // Changeset-defined: another file in the same change defines it.
        let hunk = "def run(xs):\n    return shared_new_helper(xs)";
        let scored = scorer.score_hunk(hunk, None, None, None, None);
        assert!(
            scored.stages.call_receiver_contribution > 0.0,
            "unknown callee fires before the changeset binds it"
        );
        scorer.set_changeset_bindings(HashSet::from(["shared_new_helper".to_string()]));
        let scored = scorer.score_hunk(hunk, None, None, None, None);
        assert_eq!(
            scored.stages.call_receiver_contribution, 0.0,
            "changeset-defined callee attested"
        );
        scorer.set_changeset_bindings(HashSet::new());

        // Relative-imported: the host file imports it from a repo-internal
        // path (python relative import).
        let file = "from .helpers import shared_new_helper\n\n\ndef run(xs):\n    return shared_new_helper(xs)\n";
        let hunk = "def run(xs):\n    return shared_new_helper(xs)";
        let scored = scorer.score_hunk(hunk, Some(file), Some(4), Some(5), None);
        assert_eq!(
            scored.stages.call_receiver_contribution, 0.0,
            "relative-imported callee attested: {:?}",
            scored.stages
        );

        // A truly foreign callee keeps firing under all of the above.
        let hunk = "def run(xs):\n    return totally_alien_call(xs)";
        let scored = scorer.score_hunk(hunk, Some(file), Some(4), Some(5), None);
        assert!(
            scored.stages.call_receiver_contribution > 0.0,
            "neighbourhood-less callee still fires"
        );
    }

    /// Foreign-context gate: the call-receiver reason may only *flag* a hunk
    /// when the hunk reaches into a foreign module. A bare unattested callee
    /// (the codebase's own new function) contributes but must not cry wolf; a
    /// namespace-qualified callee into an unknown module (or a foreign import)
    /// does flag.
    #[test]
    fn call_receiver_flags_only_with_foreign_context() {
        // Threshold above both hunks' BPE surprisal, contribution (uncapped
        // here) large enough to cross it on its own: isolates the firing
        // decision to the gate.
        let mut cfg = config(12.0);
        cfg.call_receiver_alpha = 25.0;
        cfg.call_receiver_cap = 25;
        cfg.call_receiver_root_bonus = 0.0;
        let files: Vec<(PathBuf, String)> = (0..4)
            .map(|i| {
                (
                    PathBuf::from(format!("m{i}.py")),
                    "import math\n\n\ndef mean(xs):\n    total = math.fsum(xs)\n    return total / len(xs)\n".to_string(),
                )
            })
            .collect();
        let mut scorer = SequentialImportBpeScorer::from_config(
            &files,
            GENERIC_BASELINE_JSON,
            Box::new(PythonAdapter::new()),
            cfg,
        )
        .unwrap();

        // New method on a KNOWN module (`math` is attested via `math.fsum`):
        // the repo's own new code reaching into a module it already uses —
        // contributes, but the file reaches no foreign module, so it does not
        // flag under the call-receiver reason.
        let known = "def run(xs):\n    return math.newhelper(xs)";
        let scored = scorer.score_hunk(known, None, None, None, None);
        assert!(
            scored.stages.call_receiver_contribution > 0.0,
            "new method on a known module still contributes"
        );
        assert!(
            !scored.flagged,
            "new API on a known module (no foreign reach) must not flag: {scored:?}"
        );

        // Namespace-qualified callee into a module the repo never uses: foreign
        // voice — flags under the call-receiver reason.
        let foreign = "def run(xs):\n    return foreignlib.connect(xs)";
        let scored = scorer.score_hunk(foreign, None, None, None, None);
        assert_eq!(
            scored.reason,
            Reason::CallReceiver,
            "namespace-foreign callee flags: {scored:?}"
        );
    }
}
