//! `SequentialImportBpeScorer` — the production composite scorer.
//!
//! Port of `engine/argot/scoring/scorers/sequential_import_bpe.py`. Composes:
//! typicality short-circuit → import-graph stage → BPE surprise stage →
//! call-receiver contribution → multi-reason resolution. Evidence collection
//! is deferred (returns `None`) until the evidence layer is ported.

use crate::bpe::BpeTokenizer;
use crate::scoring::adapters::LanguageAdapter;
use crate::scoring::bpe_scorer::BpeScorer;
use crate::scoring::call_receiver::{CallReceiverScorer, RarityWeighting};
use crate::scoring::evidence::types::{Evidence, EvidenceCorpus, SourceSpan};
use crate::scoring::evidence::{
    collect_bpe_evidence, collect_call_receiver_evidence, collect_import_evidence,
};
use crate::scoring::import_graph::ImportGraphScorer;
use crate::scoring::typicality::TypicalityModel;
use crate::text::splitlines_keepends;
use anyhow::Result;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

const EPSILON: f64 = 1e-7;
const IMPORT_THRESHOLD: f64 = 1.0;

/// Winning reason for a scored hunk (`Reason` literal in Python).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    Import,
    CallReceiver,
    Bpe,
    None,
    AutoGenerated,
    Atypical,
    AtypicalFile,
}

impl Reason {
    pub fn as_str(&self) -> &'static str {
        match self {
            Reason::Import => "import",
            Reason::CallReceiver => "call_receiver",
            Reason::Bpe => "bpe",
            Reason::None => "none",
            Reason::AutoGenerated => "auto_generated",
            Reason::Atypical => "atypical",
            Reason::AtypicalFile => "atypical_file",
        }
    }
}

/// Raw per-stage scores.
#[derive(Debug, Clone, Copy)]
pub struct StageScores {
    pub import_score: f64,
    pub bpe_score: f64,
    pub call_receiver_contribution: f64,
}

/// One hunk's verdict.
#[derive(Debug, Clone)]
pub struct ScoredHunk {
    pub score: f64,
    pub threshold: f64,
    pub flagged: bool,
    pub reason: Reason,
    pub stages: StageScores,
    /// Per-reason evidence for the winning reason, populated by the collectors
    /// when the scorer was built with an [`EvidenceCorpus`]; `None` otherwise
    /// (and for non-flagged / short-circuited hunks).
    pub evidence: Option<Evidence>,
}

/// Blank the 1-indexed prose lines in `ranges`, preserving line count
/// (`_blank_prose_lines`).
fn blank_prose_lines(src: &str, ranges: &HashSet<usize>) -> String {
    if ranges.is_empty() {
        return src.to_string();
    }
    let lines = splitlines_keepends(src);
    let mut result = String::with_capacity(src.len());
    for (i, line) in lines.iter().enumerate() {
        let ln = i + 1;
        if ranges.contains(&ln) {
            if line.ends_with('\n') {
                result.push('\n');
            }
        } else {
            result.push_str(line);
        }
    }
    result
}

/// Construction config (check-time: threshold + snapshot provided).
pub struct SequentialConfig {
    pub bpe_threshold: f64,
    pub enable_typicality: bool,
    pub exclude_data_dominant: bool,
    pub call_receiver_alpha: f64,
    pub call_receiver_cap: usize,
    pub call_receiver_root_bonus: f64,
    pub call_receiver_n_clusters: usize,
    pub call_receiver_cluster_seed: u64,
    pub call_receiver_cluster_bonus: f64,
    pub call_receiver_cluster_rare_threshold: usize,
    pub call_receiver_cluster_size_min: usize,
    /// Era-14 rarity weighting for the cluster branches (default `Off`).
    pub call_receiver_rarity_weighting: RarityWeighting,
    pub import_modules: Vec<String>,
    pub import_module_prefixes: Vec<String>,
    /// Pre-computed evidence corpus parsed from the config's `evidence_corpus`
    /// block. `None` disables evidence collection (matching a config without
    /// the block); the scorer then behaves exactly as before.
    pub evidence_corpus: Option<EvidenceCorpus>,
}

pub struct SequentialImportBpeScorer {
    adapter: Box<dyn LanguageAdapter>,
    typicality: Option<TypicalityModel>,
    import_scorer: ImportGraphScorer,
    bpe: BpeScorer,
    call_receiver: Option<CallReceiverScorer>,
    root_bonus: f64,
    cluster_bonus: f64,
    pub bpe_threshold: f64,
    evidence_corpus: Option<EvidenceCorpus>,
}

impl SequentialImportBpeScorer {
    /// Build a check-time scorer: BPE threshold and import-module snapshot come
    /// from `scorer-config.json`. `repo_files` are (path, source) pairs from
    /// repo-corpus.txt.
    pub fn from_config(
        repo_files: &[(PathBuf, String)],
        generic_baseline_json: &[u8],
        adapter: Box<dyn LanguageAdapter>,
        cfg: SequentialConfig,
    ) -> Result<Self> {
        let language = adapter.language();

        // exclude_data_dominant: filter the corpus once; the filtered list
        // feeds both the BPE corpus and the call-receiver.
        let filtered: Vec<(PathBuf, String)> = if cfg.exclude_data_dominant {
            repo_files
                .iter()
                .filter(|(_, src)| !adapter.is_data_dominant(src))
                .cloned()
                .collect()
        } else {
            repo_files.to_vec()
        };
        let corpus = if filtered.is_empty() {
            repo_files
        } else {
            &filtered
        };

        let typicality = if cfg.enable_typicality {
            Some(TypicalityModel::new(language))
        } else {
            None
        };

        let mut import_scorer = ImportGraphScorer::new();
        import_scorer.load_snapshot(
            cfg.import_modules.clone(),
            cfg.import_module_prefixes.clone(),
        );

        let sources: Vec<String> = corpus.iter().map(|(_, s)| s.clone()).collect();
        let bpe = BpeScorer::new(BpeTokenizer::load(), generic_baseline_json, &sources)?;

        let call_receiver = if cfg.call_receiver_alpha > 0.0 {
            Some(
                CallReceiverScorer::new(
                    corpus,
                    language,
                    cfg.call_receiver_alpha,
                    cfg.call_receiver_cap,
                    adapter.as_ref(),
                    cfg.call_receiver_n_clusters,
                    cfg.call_receiver_cluster_seed,
                    cfg.call_receiver_cluster_rare_threshold,
                    cfg.call_receiver_cluster_size_min,
                )
                .map_err(anyhow::Error::msg)?
                .with_rarity_weighting(cfg.call_receiver_rarity_weighting),
            )
        } else {
            None
        };

        Ok(Self {
            adapter,
            typicality,
            import_scorer,
            bpe,
            call_receiver,
            root_bonus: cfg.call_receiver_root_bonus,
            cluster_bonus: cfg.call_receiver_cluster_bonus,
            bpe_threshold: cfg.bpe_threshold,
            evidence_corpus: cfg.evidence_corpus,
        })
    }

    fn zero_stage(reason: Reason, threshold: f64) -> ScoredHunk {
        ScoredHunk {
            score: 0.0,
            threshold,
            flagged: false,
            reason,
            stages: StageScores {
                import_score: 0.0,
                bpe_score: 0.0,
                call_receiver_contribution: 0.0,
            },
            evidence: None,
        }
    }

    /// Score a hunk through both stages (`score_hunk`). `file_path` is `None`
    /// at check time (non-cluster contribution); the bench passes it.
    ///
    /// When `file_source` + line bounds are given, they double as the era-14
    /// phase D host context: a hunk whose bare parse has root errors gets its
    /// callees from its region within the file AST instead of contributing 0.
    pub fn score_hunk(
        &mut self,
        hunk_content: &str,
        file_source: Option<&str>,
        hunk_start_line: Option<usize>,
        hunk_end_line: Option<usize>,
        file_path: Option<&Path>,
    ) -> ScoredHunk {
        self.score_hunk_with_host_context(
            hunk_content,
            file_source,
            hunk_start_line,
            hunk_end_line,
            file_path,
            None,
        )
    }

    /// [`Self::score_hunk`] with an explicit host context for the phase D
    /// parse-error callee fallback — used by the benchmark's catalog fixtures,
    /// where the synthesized hunk-in-host content must NOT be passed as
    /// `file_source` (it would poison prose-blanking and file-level
    /// typicality) but should still back callee extraction on parse failure.
    /// `host_context` is `(host_source, start_line, end_line)`, 1-indexed
    /// inclusive.
    pub fn score_hunk_with_host_context(
        &mut self,
        hunk_content: &str,
        file_source: Option<&str>,
        hunk_start_line: Option<usize>,
        hunk_end_line: Option<usize>,
        file_path: Option<&Path>,
        host_context: Option<(&str, usize, usize)>,
    ) -> ScoredHunk {
        // 1. Typicality / auto-generated short-circuits.
        if let Some(typ) = &self.typicality {
            if typ.is_atypical(hunk_content).0 {
                return Self::zero_stage(Reason::Atypical, self.bpe_threshold);
            }
            if let Some(fs) = file_source {
                if typ.is_atypical_file(fs).0 {
                    return Self::zero_stage(Reason::AtypicalFile, self.bpe_threshold);
                }
            }
        } else if let Some(fs) = file_source {
            if self.adapter.is_auto_generated(fs) {
                return Self::zero_stage(Reason::AutoGenerated, self.bpe_threshold);
            }
        }

        // 2. Import stage (over the hunk's own imports).
        let foreign: HashSet<String> = self
            .adapter
            .extract_imports(hunk_content)
            .into_iter()
            .filter(|spec| self.import_scorer.is_foreign(spec))
            .collect();
        let import_score = foreign.len() as f64;

        // 3. BPE stage (optionally blank prose lines within the hunk span).
        let mut bpe_input = hunk_content.to_string();
        if let (Some(fs), Some(hs), Some(he)) = (file_source, hunk_start_line, hunk_end_line) {
            let file_prose = self.adapter.prose_line_ranges(fs);
            let hunk_prose_local: HashSet<usize> = file_prose
                .into_iter()
                .filter(|&ln| hs <= ln && ln <= he)
                .map(|ln| ln - hs + 1)
                .collect();
            bpe_input = blank_prose_lines(hunk_content, &hunk_prose_local);
        }
        let bpe_score = self.bpe.bpe_score(&bpe_input);

        // 4. Call-receiver contribution (always computed when configured).
        // Phase D host context: an explicit one wins; otherwise the file
        // source + hunk bounds serve as the host (real-PR path).
        let cr_host_context: Option<(&str, usize, usize)> =
            host_context.or(match (file_source, hunk_start_line, hunk_end_line) {
                (Some(fs), Some(hs), Some(he)) => Some((fs, hs, he)),
                _ => None,
            });
        let contribution = if let Some(cr) = &mut self.call_receiver {
            let alpha = cr.alpha;
            let cap = cr.cap as f64;
            match file_path {
                Some(_) => cr.weighted_contribution_for_file(
                    hunk_content,
                    file_path,
                    alpha,
                    self.root_bonus,
                    self.cluster_bonus,
                    cap,
                    file_source,
                    cr_host_context,
                ),
                None => cr.weighted_contribution(
                    hunk_content,
                    alpha,
                    self.root_bonus,
                    cap,
                    cr_host_context,
                ),
            }
        } else {
            0.0
        };

        let stages = StageScores {
            import_score,
            bpe_score,
            call_receiver_contribution: contribution,
        };

        // 5. Multi-reason resolution.
        let adjusted_bpe = bpe_score + contribution;
        let cr_active = self.call_receiver.is_some();
        let bpe_side_score = if cr_active { adjusted_bpe } else { bpe_score };

        let import_fired = import_score >= IMPORT_THRESHOLD;
        let bpe_fired = bpe_score > self.bpe_threshold;
        let cr_fired = cr_active && !bpe_fired && bpe_side_score > self.bpe_threshold;
        let denom = self.bpe_threshold.max(EPSILON);

        // (reason, score, threshold, ratio)
        let mut candidates: Vec<(Reason, f64, f64, f64)> = Vec::new();
        if import_fired {
            candidates.push((
                Reason::Import,
                import_score,
                IMPORT_THRESHOLD,
                import_score / IMPORT_THRESHOLD,
            ));
        }
        if bpe_fired {
            candidates.push((
                Reason::Bpe,
                bpe_score,
                self.bpe_threshold,
                bpe_score / denom,
            ));
        }
        if cr_fired {
            candidates.push((
                Reason::CallReceiver,
                adjusted_bpe,
                self.bpe_threshold,
                adjusted_bpe / denom,
            ));
        }

        if !candidates.is_empty() {
            let tiebreak = |r: Reason| match r {
                Reason::CallReceiver => 0,
                Reason::Import => 1,
                _ => 2,
            };
            candidates.sort_by(|a, b| {
                b.3.partial_cmp(&a.3)
                    .unwrap_or(std::cmp::Ordering::Equal)
                    .then_with(|| tiebreak(a.0).cmp(&tiebreak(b.0)))
            });
            let winner = candidates[0];
            let evidence = self.collect_evidence(
                winner.0,
                hunk_content,
                &bpe_input,
                file_path,
                file_source,
                &foreign,
            );
            return ScoredHunk {
                score: winner.1,
                threshold: winner.2,
                flagged: true,
                reason: winner.0,
                stages,
                evidence,
            };
        }

        ScoredHunk {
            score: bpe_side_score,
            threshold: self.bpe_threshold,
            flagged: false,
            reason: Reason::None,
            stages,
            evidence: None,
        }
    }

    /// Dispatch to the per-reason evidence collector after a hunk fires
    /// (`_collect_evidence`). Returns `None` when the scorer wasn't built with
    /// an [`EvidenceCorpus`] — the renderer then skips the evidence block,
    /// matching the unflagged path.
    fn collect_evidence(
        &self,
        winning_reason: Reason,
        hunk_content: &str,
        bpe_input: &str,
        file_path: Option<&Path>,
        file_source: Option<&str>,
        foreign: &HashSet<String>,
    ) -> Option<Evidence> {
        let corpus = self.evidence_corpus.as_ref()?;
        match winning_reason {
            Reason::Import => {
                // Preserve the order the imports appear in the hunk, and capture
                // each foreign specifier's first-occurrence span so the formatter
                // can annotate (`msgspec (L7)`), the truncator can keep the line
                // visible, and the renderer can draw carets.
                let imports_with_spans = self.adapter.extract_imports_with_spans(hunk_content);
                let mut ordered_foreign: Vec<String> = Vec::new();
                let mut seen_foreign: HashSet<String> = HashSet::new();
                let mut foreign_spans: Vec<(String, SourceSpan)> = Vec::new();
                for (spec, line, col_start, col_end) in imports_with_spans {
                    if !foreign.contains(&spec) {
                        continue;
                    }
                    if seen_foreign.insert(spec.clone()) {
                        ordered_foreign.push(spec.clone());
                        foreign_spans.push((
                            spec,
                            SourceSpan {
                                line,
                                col_start,
                                col_end,
                            },
                        ));
                    }
                }
                Some(Evidence::Import(collect_import_evidence(
                    ordered_foreign,
                    foreign_spans,
                    corpus,
                )))
            }
            Reason::CallReceiver => {
                let cr = self.call_receiver.as_ref()?;
                let cluster_id = cr.cluster_id_for_hunk_file(file_path, file_source);
                Some(Evidence::CallReceiver(collect_call_receiver_evidence(
                    cr.distinct_unattested(hunk_content),
                    cluster_id,
                    corpus,
                )))
            }
            Reason::Bpe => {
                let score_fn = |id: u32| self.bpe.token_surprise(id);
                let is_meaningful = |id: u32| self.bpe.is_meaningful_token_id(id);
                Some(Evidence::Bpe(collect_bpe_evidence(
                    bpe_input,
                    self.bpe.tokenizer(),
                    &score_fn,
                    Some(&is_meaningful),
                    corpus,
                )))
            }
            _ => None,
        }
    }
}
