//! Ignore-candidate suggestions — the *statistical* half of "what should this
//! repo not learn from".
//!
//! `argot init --suggest` surfaces directories on two independent grounds.
//!
//! **What the repo generates.** Directories whose files argot's structural
//! filters already skip individually — files carrying an auto-generation marker
//! (`@generated`, "Code generated by …") or dominated by static data literals
//! (fixtures, locale tables, generated lookups). When such files cluster in a
//! directory, lifting the whole directory into an explicit `[exclude].paths`
//! entry documents intent, speeds up fit, and catches sibling files the
//! per-file markers miss.
//!
//! **What the repo never wrote.** Directories the repository stores but does
//! not author: a vendored library, a forked upstream copy, a machine-translated
//! binding, a generated tree. No content filter can see these — imported source
//! is ordinary hand-written code carrying no marker, in whatever language the
//! repo happens to use — but their *history* gives them away in every language
//! alike: they arrive in one drop and are then left alone, while the repo edits
//! its own code over and over. This is the larger category by far, and until it
//! is named the voice is learned partly from a codebase nobody here writes.
//!
//! The binary reports only *evidence* — counts, ratios, and the exact reason a
//! directory qualifies. The decision of what to actually ignore stays with the
//! human (or the LLM driving setup). argot proposes; the reader disposes.
//! Nothing here embeds a framework- or corpus-specific literal.

use crate::inspect::adapter_for;
use crate::scoring::adapters::{Language, LanguageAdapter};
use crate::scoring::calibration::language_for_filename;
use argot_lang::text::read_text_lossy;
use serde::Serialize;
use std::collections::{BTreeMap, HashMap};
use std::path::Path;

/// A directory must hold at least this many supported files before it is worth
/// suggesting — a one- or two-file directory is noise, and the reader can
/// eyeball it faster than argot can justify a rule.
const MIN_DIR_FILES: usize = 3;

/// A directory qualifies when this fraction (or more) of its supported files
/// are structurally skipped (auto-generated or data-dominant). Set high on
/// purpose: below this, ignoring the directory would drop real code from the
/// voice, which is a judgement call argot must not make for the reader.
const SKIP_RATIO: f64 = 0.8;

/// Build output, package caches and tooling state — never a repo's authored
/// source, and a big one like `target/` can hold hundreds of thousands of
/// entries. Pruned from the walk purely for speed. This is a traversal
/// optimization, not a user-facing scope rule — that stays in
/// `argot:recommended` + `argot.toml [exclude].paths`.
///
/// A vendored tree (`vendor/`, `third_party/`, or whatever this repo calls it)
/// is deliberately **not** here. Those are committed source that the corpus
/// walk reads and the voice learns from, so a scan that refused to look at
/// them could never report the one thing the reader most needs to hear.
const SKIP_TRAVERSAL_DIRS: &[&str] = &[
    "node_modules",
    "target",
    ".venv",
    "venv",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".turbo",
    ".gradle",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
];

/// A directory must hold at least this many files whose history argot can read
/// before "this repo never edits it" means anything — under a handful of files
/// the ratio is noise.
const MIN_IMPORTED_DIR_FILES: usize = 8;

/// … and at least this many lines of source. Ignoring a directory is a
/// permanent line in a committed config; a few hundred lines is not worth one,
/// whoever wrote them. The categories this rule exists to catch — a vendored
/// library, a forked runtime, a generated tree — are never small.
const MIN_IMPORTED_DIR_LINES: usize = 2_000;

/// How much colder than the repo's own average a directory must be: its files
/// are edited at most this fraction as often as the average file here.
/// Measured as a ratio, never in absolute commits, so a repo with twenty years
/// of history and one with six months are judged by the same rule.
const IMPORTED_CHURN_RATIO: f64 = 0.15;

/// … *and* it must have arrived the way imported code arrives: this share of
/// its files introduced by one single commit …
const IMPORTED_BULK_SHARE: f64 = 0.85;

/// … or this share of its files never touched again after the commit that
/// introduced them. Either shape is enough — a library dropped in whole, or one
/// that was re-synced a few times and otherwise left alone.
const IMPORTED_UNTOUCHED_SHARE: f64 = 0.80;

/// The repository needs this much history before any of the above can be
/// judged. In a young repo nothing has been edited twice yet, so every
/// directory would read as imported; below the bar the signal abstains
/// entirely rather than reporting the whole tree.
const MIN_REPO_EDITS_PER_FILE: f64 = 3.0;

/// How a directory's files break down between the two structural filters, plus
/// the history shape of the same files.
#[derive(Debug, Clone, Default)]
struct DirTally {
    auto_generated: usize,
    data_dominant: usize,
    /// Files that would shape the voice if the directory were kept.
    included: usize,
    /// Non-blank lines of supported source under this directory.
    lines: usize,
    /// Commits that touched each file here whose history argot could read.
    edits: Vec<u32>,
    /// How many of those files each introducing commit brought in, keyed by an
    /// index into the run's interned commit ids.
    introductions: HashMap<usize, usize>,
}

impl DirTally {
    fn supported(&self) -> usize {
        self.auto_generated + self.data_dominant + self.included
    }
    fn skipped(&self) -> usize {
        self.auto_generated + self.data_dominant
    }
    fn skip_ratio(&self) -> f64 {
        let s = self.supported();
        if s == 0 {
            0.0
        } else {
            self.skipped() as f64 / s as f64
        }
    }
    fn qualifies(&self) -> bool {
        self.supported() >= MIN_DIR_FILES && self.skip_ratio() >= SKIP_RATIO
    }

    /// Mean commits per file here, over the files whose history was readable.
    fn mean_edits(&self) -> f64 {
        if self.edits.is_empty() {
            return 0.0;
        }
        self.edits.iter().map(|&e| e as f64).sum::<f64>() / self.edits.len() as f64
    }
    /// Share of those files never edited after the commit that introduced them.
    fn untouched_share(&self) -> f64 {
        if self.edits.is_empty() {
            return 0.0;
        }
        let untouched = self.edits.iter().filter(|&&e| e <= 1).count();
        untouched as f64 / self.edits.len() as f64
    }
    /// Share of those files introduced by the single most prolific commit —
    /// 1.0 when the whole directory landed at once.
    fn bulk_share(&self) -> f64 {
        if self.edits.is_empty() {
            return 0.0;
        }
        let biggest = self.introductions.values().copied().max().unwrap_or(0);
        biggest as f64 / self.edits.len() as f64
    }
    /// True when this directory looks stored rather than written: big enough to
    /// matter, far colder than the repo's own average, and arrived in bulk.
    /// `repo_mean_edits` is the same average over the whole repo.
    fn not_authored_here(&self, repo_mean_edits: f64) -> bool {
        self.edits.len() >= MIN_IMPORTED_DIR_FILES
            && self.lines >= MIN_IMPORTED_DIR_LINES
            && self.mean_edits() <= repo_mean_edits * IMPORTED_CHURN_RATIO
            && (self.bulk_share() >= IMPORTED_BULK_SHARE
                || self.untouched_share() >= IMPORTED_UNTOUCHED_SHARE)
    }
}

/// One suggested `[exclude].paths` entry, with the evidence behind it.
#[derive(Serialize, Debug, Clone)]
pub struct IgnoreCandidate {
    /// Directory path relative to the repo root, forward-slashed (e.g.
    /// `src/generated`). Suitable as-is for an `[exclude].paths` entry.
    pub path: String,
    /// Supported-language files under this directory (recursively).
    pub supported_files: usize,
    /// Of those, how many carry an auto-generation marker.
    pub auto_generated: usize,
    /// Of those, how many are dominated by static data literals.
    pub data_dominant: usize,
    /// Of those, how many are ordinary code that *would* shape the voice — the
    /// cost of ignoring the whole directory, surfaced so the reader can weigh it.
    pub included: usize,
    /// Non-blank lines of supported source under this directory — how much of
    /// the voice this entry would remove.
    pub source_lines: usize,
    /// How often this directory is edited compared with the average file in
    /// this repo: `0.04` means its files are touched a twenty-fifth as often.
    /// `None` when the repo has too little history to compare against.
    pub edit_ratio: Option<f64>,
    /// The dominant reason, for terse labelling: `not-authored-here`,
    /// `auto-generated`, `data-dominant`, or `generated + data`.
    pub reason: String,
    /// A one-line human summary of the counts.
    pub detail: String,
}

/// The `argot init --suggest` report (serialized as-is by `--format json`).
#[derive(Serialize, Debug, Clone)]
pub struct IgnoreSuggestions {
    pub repo: String,
    pub candidates: Vec<IgnoreCandidate>,
}

/// Walk `repo_dir` and propose directories to add to `[exclude].paths`: the
/// ones whose files argot's structural filters already skip, and the ones the
/// repository's own history says it stores rather than writes.
///
/// Files already excluded by the resolved path-suppression set (built-in
/// `argot:recommended` plus any existing `[exclude].paths`) are not re-counted,
/// so re-running after writing entries converges — a suggested directory stops
/// appearing once it is ignored.
pub fn suggest_ignores(repo_dir: &Path) -> IgnoreSuggestions {
    let config = argot_engine::config::ArgotConfig::load(repo_dir);
    let path_suppressions = config.path_suppressions();
    let detect = &config.detect;
    // Same git scope as the fit: a gitignored tree is already outside the
    // corpus, so proposing an `[exclude].paths` entry for it would be a
    // permanent, misleading line in a committed config that changes nothing.
    let git_scope = argot_engine::corpus::GitScope::open(repo_dir);
    let mut adapters: HashMap<Language, Box<dyn LanguageAdapter>> = HashMap::new();
    // Recursive per-directory tallies, keyed by forward-slashed relative path.
    // The repo root ("") is tallied but never emitted.
    let mut dirs: BTreeMap<String, DirTally> = BTreeMap::new();

    // How often the repo has edited each of the files it tracks, scoped exactly
    // like the tally below. Empty when there is no readable history, in which
    // case the not-authored-here signal abstains rather than guessing.
    let history = argot_engine::git_walk::path_edit_history(&repo_dir.to_string_lossy(), &|rel| {
        !path_suppressions.is_suppressed_abs(&repo_dir.join(rel), repo_dir)
    });
    let mut commit_ids: HashMap<String, usize> = HashMap::new();

    let mut stack = vec![repo_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().into_owned();
            match entry.file_type() {
                Ok(t) if t.is_dir() => {
                    // Don't descend into `.git`, argot's own model dir, or any
                    // directory the resolved suppression set (recommended +
                    // `[exclude].paths`) already excludes wholesale — its files
                    // aren't candidates and the subtree can be huge (build
                    // output, vendored deps). A synthetic child path probes the
                    // directory-level rule.
                    // A virtualenv (any name) is third-party Python, never the
                    // repo's voice — detect it structurally by its `pyvenv.cfg`
                    // marker rather than guessing names like `.venv-work`.
                    let build_dir = SKIP_TRAVERSAL_DIRS.contains(&name.as_str())
                        || path.join("pyvenv.cfg").is_file();
                    let excluded_dir = !build_dir
                        && path_suppressions
                            .is_suppressed_abs(&path.join(".argot-probe"), repo_dir);
                    let outside_repo = git_scope.as_ref().is_some_and(|scope| {
                        argot_engine::suppress::rel_string(&path, repo_dir)
                            .is_some_and(|rel| scope.excludes_dir(&rel))
                    });
                    if name != ".git"
                        && name != ".argot"
                        && !build_dir
                        && !excluded_dir
                        && !outside_repo
                    {
                        stack.push(path);
                    }
                }
                Ok(t) if t.is_file() => {
                    let Some(language) = language_for_filename(&name) else {
                        continue; // unsupported extension — not corpus
                    };
                    let outside_repo = git_scope.as_ref().is_some_and(|scope| {
                        argot_engine::suppress::rel_string(&path, repo_dir)
                            .is_some_and(|rel| scope.excludes_file(&rel))
                    });
                    if outside_repo {
                        continue; // git already puts it outside the repo
                    }
                    // Already handled by recommended/[exclude].paths — not a *new*
                    // candidate, and re-counting it would re-suggest a rule the
                    // reader already wrote.
                    if path_suppressions.is_suppressed_abs(&path, repo_dir) {
                        continue;
                    }
                    let Ok(source) = read_text_lossy(&path) else {
                        continue;
                    };
                    let adapter = adapters
                        .entry(language)
                        .or_insert_with(|| adapter_for(language));
                    let generated = adapter.is_auto_generated(&source, &detect.generated_markers);
                    let data =
                        !generated && adapter.is_data_dominant(&source, detect.data_threshold);
                    let lines = source.lines().filter(|l| !l.trim().is_empty()).count();
                    // Files git has never seen (untracked, or added since HEAD)
                    // have no history to read; they still count towards the
                    // directory's size, just not towards how often it is edited.
                    let edits = argot_engine::suppress::rel_string(&path, repo_dir)
                        .and_then(|rel| history.get(&rel).cloned());
                    let introduced =
                        edits
                            .as_ref()
                            .and_then(|e| e.introduced_in.clone())
                            .map(|sha| {
                                let next = commit_ids.len();
                                *commit_ids.entry(sha).or_insert(next)
                            });
                    // Attribute the file to every ancestor directory so a tally
                    // reflects everything beneath it.
                    for ancestor in ancestor_dirs(repo_dir, &path) {
                        let t = dirs.entry(ancestor).or_default();
                        if generated {
                            t.auto_generated += 1;
                        } else if data {
                            t.data_dominant += 1;
                        } else {
                            t.included += 1;
                        }
                        t.lines += lines;
                        if let Some(e) = &edits {
                            t.edits.push(e.edits);
                            if let Some(idx) = introduced {
                                *t.introductions.entry(idx).or_default() += 1;
                            }
                        }
                    }
                }
                _ => {}
            }
        }
    }

    let qualifying: std::collections::HashSet<String> = dirs
        .iter()
        .filter(|(_, t)| t.qualifies())
        .map(|(k, _)| k.clone())
        .collect();

    // Collapse each qualifying directory to the shallowest ancestor that adds
    // *no* extra real code — so a wholly-generated `src/gen` (and its subdirs)
    // reports once, but a `src` that merely contains `src/gen` plus real code
    // is never promoted over it (ignoring `src` would drop that real code).
    let mut targets: std::collections::HashSet<String> = qualifying
        .iter()
        .map(|k| emit_target(k, &dirs, &qualifying))
        .collect();
    // Drop any target that is an ancestor of another target: a diluted parent
    // climbs to itself, but its purer descendant is the one to suggest.
    let ancestors: Vec<String> = targets
        .iter()
        .filter(|t| {
            let prefix = format!("{t}/");
            targets.iter().any(|s| s != *t && s.starts_with(&prefix))
        })
        .cloned()
        .collect();
    for a in ancestors {
        targets.remove(&a);
    }

    // The repo's own editing rate, the yardstick every directory is measured
    // against. Below the history bar the comparison means nothing and the
    // signal stays out of the report entirely.
    let repo_mean_edits = mean_edits(&history);
    let imported: std::collections::HashSet<String> = if repo_mean_edits >= MIN_REPO_EDITS_PER_FILE
    {
        let qualifying: Vec<&String> = dirs
            .iter()
            .filter(|(_, t)| t.not_authored_here(repo_mean_edits))
            .map(|(k, _)| k)
            .collect();
        // Keep the shallowest qualifying directory of each nested chain: a
        // vendored library is one entry, not one per subdirectory.
        qualifying
            .iter()
            .filter(|k| {
                !qualifying
                    .iter()
                    .any(|other| other != *k && k.starts_with(&format!("{other}/")))
            })
            .map(|k| (*k).clone())
            .collect()
    } else {
        std::collections::HashSet::new()
    };
    targets.extend(imported.iter().cloned());
    // One entry per tree, whichever ground each was found on: a directory an
    // ancestor in the list already covers asks the reader to decide the same
    // thing twice.
    let nested: Vec<String> = targets
        .iter()
        .filter(|t| {
            targets
                .iter()
                .any(|other| other != *t && t.starts_with(&format!("{other}/")))
        })
        .cloned()
        .collect();
    for n in nested {
        targets.remove(&n);
    }

    let mut candidates: Vec<IgnoreCandidate> = targets
        .iter()
        .filter_map(|key| dirs.get(key).map(|t| (key, t)))
        .map(|(key, t)| {
            let not_authored = imported.contains(key);
            IgnoreCandidate {
                path: key.clone(),
                supported_files: t.supported(),
                auto_generated: t.auto_generated,
                data_dominant: t.data_dominant,
                included: t.included,
                source_lines: t.lines,
                edit_ratio: (repo_mean_edits > 0.0 && !t.edits.is_empty())
                    .then(|| t.mean_edits() / repo_mean_edits),
                reason: if not_authored {
                    "not-authored-here".to_string()
                } else {
                    reason_label(t)
                },
                detail: if not_authored {
                    imported_detail_line(t, repo_mean_edits)
                } else {
                    detail_line(t)
                },
            }
        })
        .collect();

    // Largest first — the highest-signal directories lead.
    candidates.sort_by(|a, b| {
        b.supported_files
            .cmp(&a.supported_files)
            .then_with(|| a.path.cmp(&b.path))
    });

    IgnoreSuggestions {
        repo: repo_dir.display().to_string(),
        candidates,
    }
}

/// The forward-slashed relative keys of every directory that contains `path`,
/// excluding the repo root (`""`, never emitted) — for `repo/a/b/c.py` this is
/// `["a", "a/b"]`.
fn ancestor_dirs(repo_dir: &Path, path: &Path) -> Vec<String> {
    let rel = match path.strip_prefix(repo_dir) {
        Ok(r) => r,
        Err(_) => return Vec::new(),
    };
    let comps: Vec<String> = rel
        .parent()
        .map(|p| {
            p.components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect()
        })
        .unwrap_or_default();
    (1..=comps.len()).map(|i| comps[..i].join("/")).collect()
}

/// The parent directory key of a forward-slashed key, or `None` at the top
/// level (whose parent is the never-emitted repo root).
fn parent_key(key: &str) -> Option<&str> {
    key.rsplit_once('/').map(|(parent, _)| parent)
}

/// Climb from a qualifying directory to the shallowest ancestor that is still
/// qualifying *and introduces no additional real code* (same recursive
/// `included` count). This collapses `src/gen/inner` → `src/gen` while refusing
/// to climb into a `src` whose own real files would be swallowed.
fn emit_target(
    key: &str,
    dirs: &BTreeMap<String, DirTally>,
    qualifying: &std::collections::HashSet<String>,
) -> String {
    let mut cur = key.to_string();
    while let Some(parent) = parent_key(&cur) {
        let promotable = qualifying.contains(parent)
            && dirs.get(parent).map(|t| t.included) == dirs.get(&cur).map(|t| t.included);
        if promotable {
            cur = parent.to_string();
        } else {
            break;
        }
    }
    cur
}

/// Mean commits per file across everything the repo tracks — the baseline a
/// directory's own rate is compared against. Zero when there is no history.
fn mean_edits(history: &HashMap<String, argot_engine::git_walk::PathEdits>) -> f64 {
    if history.is_empty() {
        return 0.0;
    }
    history.values().map(|e| e.edits as f64).sum::<f64>() / history.len() as f64
}

fn imported_detail_line(t: &DirTally, repo_mean_edits: f64) -> String {
    let mut detail = format!("{} files · {} lines", t.edits.len(), t.lines);
    let mean = t.mean_edits();
    if mean > 0.0 && repo_mean_edits > 0.0 {
        let times = repo_mean_edits / mean;
        detail.push_str(&format!(
            " · edited {times:.0}× less often than this repo's average file"
        ));
    }
    let bulk = t.bulk_share();
    let untouched = t.untouched_share();
    if bulk >= IMPORTED_BULK_SHARE {
        detail.push_str(&format!(
            " · {:.0}% of it arrived in a single commit",
            bulk * 100.0
        ));
    }
    if untouched >= IMPORTED_UNTOUCHED_SHARE {
        detail.push_str(&format!(" · {:.0}% never edited since", untouched * 100.0));
    }
    detail
}

fn reason_label(t: &DirTally) -> String {
    match (t.auto_generated > 0, t.data_dominant > 0) {
        (true, true) => "generated + data".to_string(),
        (false, true) => "data-dominant".to_string(),
        _ => "auto-generated".to_string(),
    }
}

fn detail_line(t: &DirTally) -> String {
    let mut parts: Vec<String> = Vec::new();
    if t.auto_generated > 0 {
        parts.push(format!("{} auto-generated", t.auto_generated));
    }
    if t.data_dominant > 0 {
        parts.push(format!("{} data-dominant", t.data_dominant));
    }
    let pct = (t.skip_ratio() * 100.0).round() as u64;
    let mut detail = format!("{} files · {} ({pct}%)", t.supported(), parts.join(", "));
    if t.included > 0 {
        detail.push_str(&format!(
            " · {} non-generated file{} here would be dropped",
            t.included,
            if t.included == 1 { "" } else { "s" }
        ));
    }
    detail
}

#[cfg(test)]
mod tests;
