use super::*;
use std::fs;
use std::io::ErrorKind;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};

static NEXT_TEMP_REPO: AtomicU64 = AtomicU64::new(0);

fn temp_repo(name: &str) -> PathBuf {
    loop {
        let id = NEXT_TEMP_REPO.fetch_add(1, Ordering::Relaxed);
        let dir =
            std::env::temp_dir().join(format!("argot_suggest_{name}_{}_{id}", std::process::id()));
        match fs::create_dir(&dir) {
            Ok(()) => return dir,
            Err(error) if error.kind() == ErrorKind::AlreadyExists => continue,
            Err(error) => panic!("create temporary repository {dir:?}: {error}"),
        }
    }
}

#[test]
fn temporary_repositories_with_the_same_label_are_isolated() {
    let first = temp_repo("isolation");
    fs::write(first.join("sentinel"), "still here").unwrap();

    let second = temp_repo("isolation");

    assert_ne!(first, second);
    assert_eq!(
        fs::read_to_string(first.join("sentinel")).unwrap(),
        "still here"
    );
    let _ = fs::remove_dir_all(&first);
    let _ = fs::remove_dir_all(&second);
}

fn py_fn(i: usize) -> String {
    format!("def compute_{i}(a, b):\n    x = a + b\n    y = x * 2\n    return y - b\n")
}

fn generated_py(i: usize) -> String {
    format!("# Code generated by protoc. DO NOT EDIT.\n{}", py_fn(i))
}

fn data_py(i: usize) -> String {
    format!(
        "TABLE_{i} = {{\n    \"a\": 1,\n    \"b\": 2,\n    \"c\": 3,\n    \"d\": 4,\n    \"e\": 5,\n    \"f\": 6,\n}}\n"
    )
}

#[test]
fn generated_directory_is_suggested() {
    let dir = temp_repo("gen");
    fs::create_dir_all(dir.join("src/gen")).unwrap();
    for i in 0..4 {
        fs::write(dir.join(format!("src/gen/mod_{i}.py")), generated_py(i)).unwrap();
    }
    // Real code elsewhere must NOT be suggested.
    fs::write(dir.join("src/app.py"), py_fn(0)).unwrap();

    let s = suggest_ignores(&dir);
    assert_eq!(s.candidates.len(), 1, "only the generated dir");
    let c = &s.candidates[0];
    assert_eq!(c.path, "src/gen");
    assert_eq!(c.auto_generated, 4);
    assert_eq!(c.included, 0);
    assert_eq!(c.reason, "auto-generated");
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn data_directory_is_suggested_with_reason() {
    // `locales` is not in argot:recommended, so a data-heavy one surfaces as
    // a candidate (a `fixtures/` dir, by contrast, is already excluded).
    let dir = temp_repo("data");
    fs::create_dir_all(dir.join("locales")).unwrap();
    for i in 0..3 {
        fs::write(dir.join(format!("locales/data_{i}.py")), data_py(i)).unwrap();
    }
    let s = suggest_ignores(&dir);
    let c = s
        .candidates
        .iter()
        .find(|c| c.path == "locales")
        .expect("locales candidate");
    assert_eq!(c.data_dominant, 3);
    assert_eq!(c.reason, "data-dominant");
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn mixed_directory_below_ratio_is_not_suggested() {
    // 2 generated + 3 real code → 40% skipped, below SKIP_RATIO: ignoring it
    // would drop real voice, so argot stays silent and leaves the call to
    // the reader.
    let dir = temp_repo("mixed");
    fs::create_dir_all(dir.join("pkg")).unwrap();
    for i in 0..2 {
        fs::write(dir.join(format!("pkg/gen_{i}.py")), generated_py(i)).unwrap();
    }
    for i in 0..3 {
        fs::write(dir.join(format!("pkg/real_{i}.py")), py_fn(i)).unwrap();
    }
    let s = suggest_ignores(&dir);
    assert!(s.candidates.is_empty(), "mixed dir not suggested");
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn topmost_qualifying_directory_wins() {
    // Every file under src/gen (and its subdirs) is generated, while src
    // also holds real code → collapse the generated subtree to src/gen
    // once, and never promote to src (which would drop the real code).
    let dir = temp_repo("topmost");
    fs::create_dir_all(dir.join("src/gen/inner")).unwrap();
    for i in 0..3 {
        fs::write(dir.join(format!("src/gen/a_{i}.py")), generated_py(i)).unwrap();
        fs::write(dir.join(format!("src/gen/inner/b_{i}.py")), generated_py(i)).unwrap();
    }
    fs::write(dir.join("src/app.py"), py_fn(0)).unwrap();
    let s = suggest_ignores(&dir);
    assert_eq!(s.candidates.len(), 1);
    assert_eq!(s.candidates[0].path, "src/gen");
    assert_eq!(s.candidates[0].supported_files, 6);
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn tiny_directory_below_min_files_is_ignored() {
    let dir = temp_repo("tiny");
    fs::create_dir_all(dir.join("g")).unwrap();
    for i in 0..2 {
        fs::write(dir.join(format!("g/x_{i}.py")), generated_py(i)).unwrap();
    }
    let s = suggest_ignores(&dir);
    assert!(s.candidates.is_empty(), "2-file dir below MIN_DIR_FILES");
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn build_directories_are_not_traversed() {
    // Generated files inside node_modules/target must never surface — those
    // trees are pruned wholesale (speed), and are never authored source.
    let dir = temp_repo("builddir");
    fs::create_dir_all(dir.join("node_modules/pkg")).unwrap();
    fs::create_dir_all(dir.join("target/gen")).unwrap();
    for i in 0..4 {
        fs::write(
            dir.join(format!("node_modules/pkg/m_{i}.py")),
            generated_py(i),
        )
        .unwrap();
        fs::write(dir.join(format!("target/gen/g_{i}.py")), generated_py(i)).unwrap();
    }
    let s = suggest_ignores(&dir);
    assert!(
        s.candidates.is_empty(),
        "build/dep dirs pruned, not suggested"
    );
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn virtualenvs_are_pruned_by_marker() {
    // A virtualenv with a non-standard name is still pruned via its
    // `pyvenv.cfg` marker — structural, not name-based.
    let dir = temp_repo("venv");
    fs::create_dir_all(dir.join(".venv-work/site")).unwrap();
    fs::write(dir.join(".venv-work/pyvenv.cfg"), "home = /usr/bin\n").unwrap();
    for i in 0..4 {
        fs::write(
            dir.join(format!(".venv-work/site/m_{i}.py")),
            generated_py(i),
        )
        .unwrap();
    }
    let s = suggest_ignores(&dir);
    assert!(s.candidates.is_empty(), "venv pruned by pyvenv.cfg marker");
    let _ = fs::remove_dir_all(&dir);
}

/// A file long enough to clear [`MIN_IMPORTED_DIR_LINES`] when a directory
/// holds a handful of them.
fn long_py(i: usize) -> String {
    (0..60).map(|n| py_fn(i * 100 + n)).collect()
}

fn git(dir: &std::path::Path, args: &[&str]) {
    let out = std::process::Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .expect("run git");
    assert!(
        out.status.success(),
        "git {args:?}: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

fn git_repo(name: &str) -> PathBuf {
    let dir = temp_repo(name);
    git(&dir, &["init", "-q"]);
    git(&dir, &["config", "user.email", "test@example.com"]);
    git(&dir, &["config", "user.name", "Test"]);
    dir
}

/// A repository that writes `src/` and merely stores `imported/`: the imported
/// tree lands in one commit and is never touched again, while the repo's own
/// files are edited over and over.
fn repo_with_an_imported_tree(name: &str, edit_imported: bool) -> PathBuf {
    let dir = git_repo(name);
    fs::create_dir_all(dir.join("imported")).unwrap();
    fs::create_dir_all(dir.join("src")).unwrap();
    for i in 0..10 {
        fs::write(dir.join(format!("imported/lib_{i}.py")), long_py(i)).unwrap();
    }
    for i in 0..4 {
        fs::write(dir.join(format!("src/app_{i}.py")), py_fn(i)).unwrap();
    }
    git(&dir, &["add", "-A"]);
    git(&dir, &["commit", "-q", "-m", "import"]);
    for round in 1..=25 {
        for i in 0..4 {
            fs::write(dir.join(format!("src/app_{i}.py")), py_fn(i + round * 10)).unwrap();
            if edit_imported {
                fs::write(
                    dir.join(format!("imported/lib_{i}.py")),
                    format!("{}{}", long_py(i), py_fn(round)),
                )
                .unwrap();
            }
        }
        git(&dir, &["add", "-A"]);
        git(&dir, &["commit", "-q", "-m", &format!("work {round}")]);
    }
    dir
}

#[test]
fn a_directory_the_repo_stores_but_never_writes_is_suggested() {
    let dir = repo_with_an_imported_tree("imported", false);
    let s = suggest_ignores(&dir);
    let c = s
        .candidates
        .iter()
        .find(|c| c.path == "imported")
        .expect("the imported tree is a candidate");
    assert_eq!(c.reason, "not-authored-here");
    assert!(
        c.edit_ratio.is_some_and(|r| r < IMPORTED_CHURN_RATIO),
        "reported far colder than the repo's own code, got {:?}",
        c.edit_ratio
    );
    assert!(
        s.candidates.iter().all(|c| c.path != "src"),
        "code the repo actually writes is never suggested"
    );
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn a_directory_the_repo_keeps_editing_is_not_suggested() {
    // Same shape, same bulk arrival — but the repo maintains it. Code that is
    // edited here speaks in this repo's voice, whoever wrote it first.
    let dir = repo_with_an_imported_tree("maintained", true);
    let s = suggest_ignores(&dir);
    assert!(
        s.candidates.iter().all(|c| c.path != "imported"),
        "a maintained directory is not imported: {:?}",
        s.candidates.iter().map(|c| &c.path).collect::<Vec<_>>()
    );
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn a_repo_too_young_to_compare_against_abstains() {
    // Everything was added once and nothing edited yet, so every directory
    // looks equally cold. Reporting the whole tree would be worse than
    // reporting nothing.
    let dir = git_repo("young");
    fs::create_dir_all(dir.join("imported")).unwrap();
    for i in 0..10 {
        fs::write(dir.join(format!("imported/lib_{i}.py")), long_py(i)).unwrap();
    }
    git(&dir, &["add", "-A"]);
    git(&dir, &["commit", "-q", "-m", "initial"]);
    let s = suggest_ignores(&dir);
    assert!(
        s.candidates.iter().all(|c| c.reason != "not-authored-here"),
        "no history to compare against → the signal stays silent"
    );
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn a_small_untouched_directory_is_below_the_size_floor() {
    // Cold and bulk-arrived, but a few hundred lines: not worth a permanent
    // line in a committed config.
    let dir = git_repo("smallimport");
    fs::create_dir_all(dir.join("imported")).unwrap();
    fs::create_dir_all(dir.join("src")).unwrap();
    for i in 0..10 {
        fs::write(dir.join(format!("imported/lib_{i}.py")), py_fn(i)).unwrap();
    }
    for i in 0..4 {
        fs::write(dir.join(format!("src/app_{i}.py")), py_fn(i)).unwrap();
    }
    git(&dir, &["add", "-A"]);
    git(&dir, &["commit", "-q", "-m", "import"]);
    for round in 1..=25 {
        for i in 0..4 {
            fs::write(dir.join(format!("src/app_{i}.py")), py_fn(i + round * 10)).unwrap();
        }
        git(&dir, &["add", "-A"]);
        git(&dir, &["commit", "-q", "-m", &format!("work {round}")]);
    }
    let s = suggest_ignores(&dir);
    assert!(
        s.candidates.iter().all(|c| c.path != "imported"),
        "below the line floor → not suggested"
    );
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn already_ignored_directory_is_not_resuggested() {
    let dir = temp_repo("already");
    fs::create_dir_all(dir.join("gen")).unwrap();
    for i in 0..4 {
        fs::write(dir.join(format!("gen/mod_{i}.py")), generated_py(i)).unwrap();
    }
    fs::write(dir.join("argot.toml"), "[exclude]\npaths = [\"gen/\"]\n").unwrap();
    let s = suggest_ignores(&dir);
    assert!(
        s.candidates.iter().all(|c| c.path != "gen"),
        "gen/ already ignored → not re-suggested"
    );
    let _ = fs::remove_dir_all(&dir);
}
