//! `SequentialImportBpeScorer` — the production composite scorer.
//!
//! Composes: typicality short-circuit → import-graph stage → BPE surprise
//! stage → call-receiver contribution → multi-reason resolution. Per-reason
//! evidence is collected for the winning reason when the scorer is built with
//! an `EvidenceCorpus`.

use crate::scoring::adapters::LanguageAdapter;
use crate::scoring::bpe_scorer::BpeScorer;
use crate::scoring::call_receiver::{CallReceiverScorer, RarityWeighting};
use crate::scoring::conventions::ConventionScorer;
use crate::scoring::evidence::types::{Evidence, EvidenceCorpus, SourceSpan};
use crate::scoring::evidence::{
    collect_bpe_evidence, collect_call_receiver_evidence, collect_import_evidence,
};
use crate::scoring::import_graph::ImportGraphScorer;
use crate::scoring::model::LanguageModel;
use crate::scoring::shape_primitive::ShapePrimitiveRegistry;
use crate::scoring::typicality::TypicalityModel;
use anyhow::Result;
use argot_engine::suppress::PathSuppressions;
use argot_lang::bpe::BpeTokenizer;
use argot_lang::text::splitlines_keepends;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

const EPSILON: f64 = 1e-7;
const IMPORT_THRESHOLD: f64 = 1.0;
/// A hunk whose non-blank rows lie mostly inside the host file's static
/// data-literal spans is data, not phrasing — skipped like the file-level
/// data filters, but at row granularity (same 0.65 share the file-level
/// data-dominant filter uses). Code rows in data-heavy files stay judged.
const DATA_ROW_SHARE_CUTOFF: f64 = 0.65;

/// Winning reason for a scored hunk (`Reason` literal in Python).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    Import,
    CallReceiver,
    Bpe,
    Convention,
    None,
    AutoGenerated,
    Atypical,
    AtypicalFile,
}

impl Reason {
    pub fn as_str(&self) -> &'static str {
        match self {
            Reason::Import => "import",
            Reason::CallReceiver => "call_receiver",
            Reason::Bpe => "bpe",
            Reason::Convention => "convention",
            Reason::None => "none",
            Reason::AutoGenerated => "auto_generated",
            Reason::Atypical => "atypical",
            Reason::AtypicalFile => "atypical_file",
        }
    }
}

/// Raw per-stage scores.
#[derive(Debug, Clone, Copy)]
pub struct StageScores {
    pub import_score: f64,
    pub bpe_score: f64,
    pub call_receiver_contribution: f64,
    /// Convention-rarity bonus (0.0 unless a convention cleared its bar).
    pub convention_contribution: f64,
}

/// One hunk's verdict.
#[derive(Debug, Clone)]
pub struct ScoredHunk {
    pub score: f64,
    pub threshold: f64,
    pub flagged: bool,
    pub reason: Reason,
    pub stages: StageScores,
    /// Per-reason evidence for the winning reason, populated by the collectors
    /// when the scorer was built with an [`EvidenceCorpus`]; `None` otherwise
    /// (and for non-flagged / short-circuited hunks).
    pub evidence: Option<Evidence>,
    /// Top-level modules this hunk imports that are foreign to the repo (sorted,
    /// deduped). Backs the check-time per-changeset novel-import dedup: the same
    /// foreign dependency added across many files of one change (a mechanical
    /// migration) should alert once, not once per file. Empty unless the hunk
    /// carries a foreign import.
    pub foreign_import_modules: Vec<String>,
}

/// Blank the 1-indexed prose lines in `ranges`, preserving line count
/// (`_blank_prose_lines`).
fn blank_prose_lines(
    src: &str,
    ranges: &HashSet<usize>,
    spans: &[(usize, usize, usize)],
) -> String {
    if ranges.is_empty() && spans.is_empty() {
        return src.to_string();
    }
    let lines = splitlines_keepends(src);
    let mut result = String::with_capacity(src.len());
    for (i, line) in lines.iter().enumerate() {
        let ln = i + 1;
        if ranges.contains(&ln) {
            if line.ends_with('\n') {
                result.push('\n');
            }
            continue;
        }
        let mut masked = line.to_string();
        for (_, a, b) in spans.iter().filter(|(r, ..)| *r == ln) {
            let (a, b) = ((*a).min(masked.len()), (*b).min(masked.len()));
            if a < b && masked.is_char_boundary(a) && masked.is_char_boundary(b) {
                masked.replace_range(a..b, &" ".repeat(b - a));
            }
        }
        result.push_str(&masked);
    }
    result
}

/// Construction config (check-time: threshold + snapshot provided).
pub struct SequentialConfig {
    pub bpe_threshold: f64,
    pub enable_typicality: bool,
    pub exclude_data_dominant: bool,
    pub call_receiver_alpha: f64,
    pub call_receiver_cap: usize,
    pub call_receiver_root_bonus: f64,
    pub call_receiver_n_clusters: usize,
    pub call_receiver_cluster_seed: u64,
    pub call_receiver_cluster_bonus: f64,
    pub call_receiver_cluster_rare_threshold: usize,
    pub call_receiver_cluster_size_min: usize,
    /// Rarity weighting for the cluster branches (default `Off`).
    pub call_receiver_rarity_weighting: RarityWeighting,
    /// Registered shape-primitive names to enable (empty = none).
    pub call_receiver_shape_primitive_names: Vec<String>,
    /// Parse-error host fallback: when true, a hunk whose bare parse has root
    /// errors gets its callees from its region within the host AST instead of
    /// contributing 0. Production check runs with this ON: git picks hunk
    /// boundaries, not the parser, so mid-construct fragments are the norm at
    /// check time, and calibration always applied the fallback on its side.
    /// An earlier FP flood was measured with a forced cluster-rare rule;
    /// production auto-detects that rule per corpus. The bench's catalog mode
    /// keeps it off for baseline continuity.
    pub call_receiver_parse_error_host_fallback: bool,
    /// Fitted convention-rarity model (frequencies + calibrated bars);
    /// `None` disables the stage.
    pub conventions: Option<crate::scoring::model::ConventionModel>,
    /// Score added when a convention clears its bar (the stage's whole
    /// contribution — features do not stack).
    pub convention_bonus: f64,
    pub import_modules: Vec<String>,
    pub import_module_prefixes: Vec<String>,
    /// Modules imported only by `[exclude].check-only` files, from the fit.
    /// Consulted for those files alone — a test-only dependency never becomes
    /// familiar in production code.
    pub check_only_import_modules: Vec<String>,
    /// The live `[exclude].check-only` globs. Live rather than fitted because
    /// this is a scope decision, not learned state; a pattern added without a
    /// refit simply has no vocabulary yet, which withholds findings rather
    /// than inventing them.
    pub check_only_patterns: Vec<String>,
    /// Pre-computed evidence corpus parsed from the config's `evidence_corpus`
    /// block. `None` disables evidence collection (matching a config without
    /// the block); the scorer then behaves exactly as before.
    pub evidence_corpus: Option<EvidenceCorpus>,
    /// Generated/data detection heuristics (`[detect]`): the data-dominance
    /// threshold and generated-comment markers used to keep generated/data
    /// files out of the corpus and skip them at check time.
    pub detect: argot_engine::config::DetectConfig,
}

/// Per-file derived state that every hunk of the same file shares. Hunks
/// arrive batched per file, so a single-entry cache keyed by a content hash
/// removes the repeated file parses (bindings, data rows, prose ranges).
/// Pure memoization — scoring is byte-identical with or without it.
#[derive(Default)]
struct FileDerivedCache {
    key: u64,
    data_rows: HashSet<usize>,
    prose_rows: HashSet<usize>,
    prose_spans: Vec<(usize, usize, usize)>,
    file_bindings: crate::scoring::call_receiver::LocalBindings,
}

fn content_key(source: &str) -> u64 {
    use std::hash::{Hash, Hasher};
    let mut h = std::collections::hash_map::DefaultHasher::new();
    source.hash(&mut h);
    h.finish()
}

/// Identifier-like tokens in `src` (maximal `[A-Za-z0-9_]` runs). Language
/// agnostic: used only to test whether a hunk mentions a known import binding,
/// so `Fore.BLUE` yields `Fore` and `np.ndarray` yields `np`.
fn identifier_tokens(src: &str) -> impl Iterator<Item = &str> {
    src.split(|c: char| !(c.is_alphanumeric() || c == '_'))
        .filter(|t| !t.is_empty())
}

pub struct SequentialImportBpeScorer {
    adapter: Box<dyn LanguageAdapter>,
    /// Callable names defined anywhere in the change being checked (all
    /// files of the changeset) — new code naming its own neighbourhood.
    changeset_bindings: HashSet<String>,
    /// Single-entry per-file cache (see [`FileDerivedCache`]).
    file_cache: Option<FileDerivedCache>,
    typicality: Option<TypicalityModel>,
    import_scorer: ImportGraphScorer,
    bpe: BpeScorer,
    call_receiver: Option<CallReceiverScorer>,
    conventions: Option<ConventionScorer>,
    convention_bonus: f64,
    root_bonus: f64,
    cluster_bonus: f64,
    parse_error_host_fallback: bool,
    pub bpe_threshold: f64,
    evidence_corpus: Option<EvidenceCorpus>,
    /// Generated-file comment markers, for the check-time auto-generated skip.
    generated_markers: Vec<String>,
    /// `[exclude].check-only` matcher. A hunk in one of these files is judged
    /// on its dependencies alone: the voice never learned their style, so
    /// surprisal, callee and convention candidates are withheld and only the
    /// import reason can carry the hunk. `None` when no pattern is configured
    /// — then this is inert and scoring is byte-identical.
    check_only: Option<PathSuppressions>,
}

/// Does `file_path` name a `[exclude].check-only` file? `None` (the bench's
/// path-less scoring) and a scorer with no configured patterns are never
/// check-only, so the default path is untouched.
fn is_check_only_path(check_only: Option<&PathSuppressions>, file_path: Option<&Path>) -> bool {
    match (check_only, file_path) {
        (Some(scope), Some(path)) => {
            scope.is_check_only(&path.to_string_lossy().replace('\\', "/"))
        }
        _ => false,
    }
}

/// Build the check-only matcher, or `None` when no pattern is configured (then
/// every check-only branch is dead and scoring is byte-identical).
fn check_only_scope(patterns: &[String]) -> Option<PathSuppressions> {
    (!patterns.is_empty()).then(|| PathSuppressions::from_parts(&[], &[], patterns, true))
}

impl SequentialImportBpeScorer {
    /// Build a check-time scorer: BPE threshold and import-module snapshot come
    /// from `scorer-config.json`. `repo_files` are (path, source) pairs from
    /// repo-corpus.txt.
    pub fn from_config(
        repo_files: &[(PathBuf, String)],
        generic_baseline_json: &[u8],
        adapter: Box<dyn LanguageAdapter>,
        cfg: SequentialConfig,
    ) -> Result<Self> {
        let language = adapter.language();

        // exclude_data_dominant: filter the corpus once; the filtered list
        // feeds both the BPE corpus and the call-receiver.
        let filtered: Vec<(PathBuf, String)> = if cfg.exclude_data_dominant {
            repo_files
                .iter()
                .filter(|(_, src)| !adapter.is_data_dominant(src, cfg.detect.data_threshold))
                .cloned()
                .collect()
        } else {
            repo_files.to_vec()
        };
        let corpus = if filtered.is_empty() {
            repo_files
        } else {
            &filtered
        };

        let typicality = if cfg.enable_typicality {
            Some(TypicalityModel::new(language))
        } else {
            None
        };

        let mut import_scorer = ImportGraphScorer::new();
        import_scorer.load_snapshot(
            cfg.import_modules.clone(),
            cfg.import_module_prefixes.clone(),
        );
        import_scorer.load_check_only(cfg.check_only_import_modules.clone());
        let check_only = check_only_scope(&cfg.check_only_patterns);

        let sources: Vec<String> = corpus.iter().map(|(_, s)| s.clone()).collect();
        let bpe = BpeScorer::new(BpeTokenizer::load(), generic_baseline_json, &sources)?;

        let call_receiver = if cfg.call_receiver_alpha > 0.0 {
            Some(
                CallReceiverScorer::new(
                    corpus,
                    language,
                    cfg.call_receiver_alpha,
                    cfg.call_receiver_cap,
                    adapter.as_ref(),
                    cfg.call_receiver_n_clusters,
                    cfg.call_receiver_cluster_seed,
                    cfg.call_receiver_cluster_rare_threshold,
                    cfg.call_receiver_cluster_size_min,
                    cfg.detect.data_threshold,
                )
                .map_err(anyhow::Error::msg)?
                .with_rarity_weighting(cfg.call_receiver_rarity_weighting)
                .with_shape_primitives(
                    ShapePrimitiveRegistry::with_builtins()
                        .build(&cfg.call_receiver_shape_primitive_names)
                        .map_err(anyhow::Error::msg)?,
                    corpus,
                    adapter.as_ref(),
                    cfg.detect.data_threshold,
                ),
            )
        } else {
            None
        };

        let conventions = cfg.conventions.map(|m| ConventionScorer::new(m, language));

        Ok(Self {
            adapter,
            changeset_bindings: HashSet::new(),
            file_cache: None,
            typicality,
            import_scorer,
            bpe,
            call_receiver,
            conventions,
            convention_bonus: cfg.convention_bonus,
            root_bonus: cfg.call_receiver_root_bonus,
            cluster_bonus: cfg.call_receiver_cluster_bonus,
            parse_error_host_fallback: cfg.call_receiver_parse_error_host_fallback,
            bpe_threshold: cfg.bpe_threshold,
            evidence_corpus: cfg.evidence_corpus,
            generated_markers: cfg.detect.generated_markers,
            check_only,
        })
    }

    /// Build a check-time scorer from the fit-time [`LanguageModel`] snapshot
    /// instead of re-reading the corpus. Attestation, cluster membership, and
    /// the repo BPE token distribution are pinned to fit time, so new code is
    /// scored against the voice as learned — it cannot attest itself (#79).
    ///
    /// Shape primitives are not supported on this path: their per-cluster
    /// baselines are corpus-fitted state that the artifact does not carry
    /// (they are default-off research substrate; the bench builds them from
    /// a live corpus).
    pub fn from_model(
        model: &LanguageModel,
        generic_baseline_json: &[u8],
        adapter: Box<dyn LanguageAdapter>,
        cfg: SequentialConfig,
    ) -> Result<Self> {
        if !cfg.call_receiver_shape_primitive_names.is_empty() {
            anyhow::bail!("shape primitives require a live corpus, not a model snapshot");
        }
        let language = adapter.language();

        let typicality = if cfg.enable_typicality {
            Some(TypicalityModel::new(language))
        } else {
            None
        };

        let mut import_scorer = ImportGraphScorer::new();
        import_scorer.load_snapshot(
            cfg.import_modules.clone(),
            cfg.import_module_prefixes.clone(),
        );
        import_scorer.load_check_only(cfg.check_only_import_modules.clone());
        let check_only = check_only_scope(&cfg.check_only_patterns);

        let bpe = BpeScorer::from_stats(BpeTokenizer::load(), generic_baseline_json, &model.bpe)?;

        let call_receiver = if cfg.call_receiver_alpha > 0.0 {
            Some(
                CallReceiverScorer::from_model(
                    &model.call_receiver,
                    language,
                    cfg.call_receiver_alpha,
                    cfg.call_receiver_cap,
                    cfg.call_receiver_cluster_rare_threshold,
                    cfg.call_receiver_cluster_size_min,
                )
                .map_err(anyhow::Error::msg)?
                .with_rarity_weighting(cfg.call_receiver_rarity_weighting),
            )
        } else {
            None
        };

        let conventions = model
            .conventions
            .clone()
            .map(|m| ConventionScorer::new(m, language));

        Ok(Self {
            adapter,
            changeset_bindings: HashSet::new(),
            file_cache: None,
            typicality,
            import_scorer,
            bpe,
            call_receiver,
            conventions,
            convention_bonus: cfg.convention_bonus,
            root_bonus: cfg.call_receiver_root_bonus,
            cluster_bonus: cfg.call_receiver_cluster_bonus,
            parse_error_host_fallback: cfg.call_receiver_parse_error_host_fallback,
            bpe_threshold: cfg.bpe_threshold,
            evidence_corpus: cfg.evidence_corpus,
            generated_markers: cfg.detect.generated_markers,
            check_only,
        })
    }

    /// Install the changeset-wide callable definitions for this check run —
    /// names any file in the change defines. Cleared by passing an empty set.
    /// Widen the fit-time attestation with replacement-side patterns (mined
    /// supersessions at load, declared `[[migration]]` targets at check —
    /// the latter apply without a refit). What the repo is moving *to* must
    /// never read as foreign.
    pub fn attest_replacements(&mut self, imports: &[String], callees: &[String]) {
        self.import_scorer.extend_known(imports.iter().cloned());
        if let Some(cr) = self.call_receiver.as_mut() {
            cr.extend_attested(callees);
        }
    }

    pub fn set_changeset_bindings(&mut self, bindings: HashSet<String>) {
        self.changeset_bindings = bindings;
    }

    /// Modules the changeset itself declares — a file in the change carrying
    /// `unit foo` / `package foo`. Adding a module and importing it is one
    /// act, and the fit-time snapshot cannot know about it: without this a
    /// backend port that adds three units and wires them into six files reads
    /// as six foreign dependencies, which is the opposite of the signal.
    ///
    /// This does not reopen the hole `load_snapshot` exists to close. A new
    /// third-party dependency is never *declared* by a file in the diff — it
    /// arrives as a bare name resolved from outside the repository.
    pub fn attest_changeset_modules<I: IntoIterator<Item = String>>(&mut self, modules: I) {
        self.import_scorer.extend_known(modules);
    }

    /// Whether `path` (repo-relative) was in the fit corpus. A path the model
    /// never saw is a new file, judged by `check` against the new-file threshold
    /// rather than the existing-file one (issue #92 new-file flooding). Falls
    /// back to `true` (treat as existing) when there is no call-receiver model,
    /// so a call-receiver-less config keeps its single-threshold behaviour.
    pub fn is_fit_file(&self, path: &std::path::Path) -> bool {
        self.call_receiver
            .as_ref()
            .is_none_or(|cr| cr.knows_file(path))
    }

    /// Is `path` in the `[exclude].check-only` scope — checked, but never part
    /// of the voice corpus? A caller that re-decides `flagged` against a
    /// threshold must ask: every threshold argot calibrates describes
    /// production phrasing, and these files were never measured against it.
    pub fn is_check_only_file(&self, path: &Path) -> bool {
        is_check_only_path(self.check_only.as_ref(), Some(path))
    }

    /// Per-primitive fire counts from the call-receiver (bench observability).
    pub fn primitive_fire_counts(&self) -> Option<&std::collections::HashMap<String, usize>> {
        self.call_receiver
            .as_ref()
            .map(|cr| &cr.primitive_fire_count)
    }

    /// The per-file derived state for `source`, recomputing only when the
    /// content differs from the cached entry.
    fn file_derived(&mut self, source: &str) -> &FileDerivedCache {
        let key = content_key(source);
        let hit = self.file_cache.as_ref().is_some_and(|c| c.key == key);
        if !hit {
            let mut file_bindings = crate::scoring::call_receiver::LocalBindings::default();
            file_bindings
                .callables
                .extend(self.adapter.callable_definitions(source));
            file_bindings
                .callables
                .extend(self.adapter.internal_import_bindings(source));
            file_bindings
                .values
                .extend(self.adapter.value_bindings(source));
            self.file_cache = Some(FileDerivedCache {
                key,
                data_rows: self.adapter.data_literal_lines(source),
                prose_rows: self.adapter.prose_line_ranges(source),
                prose_spans: self.adapter.prose_spans(source),
                file_bindings,
            });
        }
        self.file_cache.as_ref().expect("just populated")
    }

    /// Share of the hunk's non-blank rows that fall inside the host file's
    /// static data-literal spans (1-indexed inclusive hunk bounds). 0.0 when
    /// the hunk has no non-blank rows or the file has no data spans.
    fn hunk_data_row_share(
        &mut self,
        hunk_content: &str,
        file_source: &str,
        hunk_start_line: usize,
        hunk_end_line: usize,
    ) -> f64 {
        let data_rows = &self.file_derived(file_source).data_rows;
        if data_rows.is_empty() {
            return 0.0;
        }
        let mut nonblank = 0usize;
        let mut in_data = 0usize;
        for (i, line) in splitlines_keepends(hunk_content).iter().enumerate() {
            if line.trim().is_empty() {
                continue;
            }
            let file_line = hunk_start_line + i;
            if file_line > hunk_end_line {
                break;
            }
            nonblank += 1;
            if data_rows.contains(&file_line) {
                in_data += 1;
            }
        }
        if nonblank == 0 {
            0.0
        } else {
            in_data as f64 / nonblank as f64
        }
    }

    /// Whether `hunk_content` references a name bound by a *foreign* import in
    /// `binding_source` (the file). Scopes the file-level foreign-import signal
    /// to hunks that actually use the foreign dependency's symbols, so a hunk
    /// of the repo's own code in a file that merely imports something foreign
    /// stays quiet. Bindings come from the adapter (`import numpy as np` → `np`,
    /// `from colorama import Fore` → `Fore`); foreignness from the import scorer.
    fn hunk_uses_foreign_import_binding(
        &self,
        hunk_content: &str,
        binding_source: &str,
        check_only: bool,
    ) -> bool {
        let foreign_names: HashSet<String> = self
            .adapter
            .import_bindings(binding_source)
            .into_iter()
            .filter(|(_, module)| self.import_scorer.is_foreign_in(module, check_only))
            .map(|(name, _)| name)
            .collect();
        if foreign_names.is_empty() {
            return false;
        }
        identifier_tokens(hunk_content).any(|tok| foreign_names.contains(tok))
    }

    fn zero_stage(reason: Reason, threshold: f64) -> ScoredHunk {
        ScoredHunk {
            score: 0.0,
            threshold,
            flagged: false,
            reason,
            stages: StageScores {
                import_score: 0.0,
                bpe_score: 0.0,
                call_receiver_contribution: 0.0,
                convention_contribution: 0.0,
            },
            evidence: None,
            foreign_import_modules: Vec::new(),
        }
    }

    /// Score a hunk through both stages (`score_hunk`). `file_path` is `None`
    /// at check time (non-cluster contribution); the bench passes it.
    ///
    /// When `file_source` + line bounds are given, they double as the
    /// parse-error host context: a hunk whose bare parse has root errors gets
    /// its callees from its region within the file AST instead of contributing 0.
    pub fn score_hunk(
        &mut self,
        hunk_content: &str,
        file_source: Option<&str>,
        hunk_start_line: Option<usize>,
        hunk_end_line: Option<usize>,
        file_path: Option<&Path>,
    ) -> ScoredHunk {
        self.score_hunk_with_host_context(
            hunk_content,
            file_source,
            hunk_start_line,
            hunk_end_line,
            file_path,
            None,
        )
    }

    /// [`Self::score_hunk`] with an explicit host context for the parse-error
    /// callee fallback — used by the benchmark's catalog fixtures,
    /// where the synthesized hunk-in-host content must NOT be passed as
    /// `file_source` (it would poison prose-blanking and file-level
    /// typicality) but should still back callee extraction on parse failure.
    /// `host_context` is `(host_source, start_line, end_line)`, 1-indexed
    /// inclusive.
    pub fn score_hunk_with_host_context(
        &mut self,
        hunk_content: &str,
        file_source: Option<&str>,
        hunk_start_line: Option<usize>,
        hunk_end_line: Option<usize>,
        file_path: Option<&Path>,
        host_context: Option<(&str, usize, usize)>,
    ) -> ScoredHunk {
        // 1. Typicality / auto-generated short-circuits.
        if let Some(typ) = &self.typicality {
            if typ.is_atypical(hunk_content).0 {
                return Self::zero_stage(Reason::Atypical, self.bpe_threshold);
            }
        } else if let Some(fs) = file_source {
            if self.adapter.is_auto_generated(fs, &self.generated_markers) {
                return Self::zero_stage(Reason::AutoGenerated, self.bpe_threshold);
            }
        }

        // 1b. Row-granular data scope: a hunk sitting mostly inside the host
        // file's data-literal spans is data, not phrasing. Replaces the old
        // file-level vetoes (data-dominant batch drop, atypical-file
        // fallback), which also silenced *code* planted in data-heavy files —
        // the exact class of subtle break this scorer exists to judge.
        if let (Some(fs), Some(hs), Some(he)) = (file_source, hunk_start_line, hunk_end_line) {
            if self.hunk_data_row_share(hunk_content, fs, hs, he) > DATA_ROW_SHARE_CUTOFF {
                return Self::zero_stage(Reason::AtypicalFile, self.bpe_threshold);
            }
        }

        // Blank the hunk's prose lines (docstring/comment rows, identified from
        // full-file context) once — shared by the import and BPE stages. An
        // `import` that lives inside a docstring or comment is not real code:
        // on the range/commit path the hunk arrives as a fragment whose opening
        // `"""` may lie above the window, so tree-sitter would otherwise reparse
        // the interior `import x` line as a genuine statement and flag it
        // foreign (B1). Masking prose rows first removes that false positive
        // while leaving real code untouched. Falls back to the raw fragment only
        // when there's no file context (the bench synthetic path).
        let prose_blanked: Option<String> =
            if let (Some(fs), Some(hs), Some(he)) = (file_source, hunk_start_line, hunk_end_line) {
                let derived = self.file_derived(fs);
                let hunk_prose_local: HashSet<usize> = derived
                    .prose_rows
                    .iter()
                    .copied()
                    .filter(|&ln| hs <= ln && ln <= he)
                    .map(|ln| ln - hs + 1)
                    .collect();
                let spans_local: Vec<(usize, usize, usize)> = derived
                    .prose_spans
                    .iter()
                    .filter(|(ln, ..)| hs <= *ln && *ln <= he)
                    .map(|(ln, a, b)| (ln - hs + 1, *a, *b))
                    .collect();
                Some(blank_prose_lines(
                    hunk_content,
                    &hunk_prose_local,
                    &spans_local,
                ))
            } else {
                None
            };
        let masked_input: &str = prose_blanked.as_deref().unwrap_or(hunk_content);

        // A `[exclude].check-only` file is judged on its dependencies alone:
        // the voice never learned its style, but it did learn which libraries
        // live there.
        let check_only = is_check_only_path(self.check_only.as_ref(), file_path);

        // 2. Import stage (over the hunk's own imports, prose lines blanked).
        let foreign: HashSet<String> = self
            .adapter
            .extract_imports(masked_input)
            .into_iter()
            .filter(|spec| self.import_scorer.is_foreign_in(spec, check_only))
            .collect();
        let import_score = foreign.len() as f64;

        // 3. BPE stage (same prose-blanked input).
        let bpe_score = self.bpe.bpe_score(masked_input);

        // 4. Call-receiver contribution (always computed when configured).
        // Parse-error host context: an explicit one wins; otherwise the file
        // source + hunk bounds serve as the host (real-PR path). Gated by the
        // parse-error host fallback flag (default off — see SequentialConfig).
        let cr_host_context: Option<(&str, usize, usize)> = if self.parse_error_host_fallback {
            host_context.or(match (file_source, hunk_start_line, hunk_end_line) {
                (Some(fs), Some(hs), Some(he)) => Some((fs, hs, he)),
                _ => None,
            })
        } else {
            None
        };
        // Local-binding attestation: what this change defines (host file or
        // fragment) plus what it imports from repo-internal paths plus the
        // changeset-wide definitions — its own neighbourhood, not foreign.
        // Value bindings (destructured names, consts, parameters) attest
        // bare calls only; callables and import bindings also attest via
        // their root.
        let binding_source: &str = file_source
            .or(host_context.map(|(h, _, _)| h))
            .unwrap_or(hunk_content);
        let derived = self.file_derived(binding_source);
        let mut local_bindings = derived.file_bindings.clone();
        local_bindings
            .callables
            .extend(self.changeset_bindings.iter().cloned());

        let contribution = if let Some(cr) = &mut self.call_receiver {
            let alpha = cr.alpha;
            let cap = cr.cap as f64;
            match file_path {
                Some(_) => cr.weighted_contribution_for_file(
                    hunk_content,
                    file_path,
                    alpha,
                    self.root_bonus,
                    self.cluster_bonus,
                    cap,
                    file_source,
                    cr_host_context,
                    &local_bindings,
                ),
                None => cr.weighted_contribution(
                    hunk_content,
                    alpha,
                    self.root_bonus,
                    cap,
                    cr_host_context,
                    &local_bindings,
                ),
            }
        } else {
            0.0
        };

        // 4c. Convention rarity: a construct or naming shape the corpus does
        // not use, past its calibrated bar. Shares the phase-D host-context
        // discipline (host region consulted only on bare-parse errors).
        let convention_contribution = match &self.conventions {
            Some(conv) => {
                let host: Option<(&str, usize, usize)> =
                    host_context.or(match (file_source, hunk_start_line, hunk_end_line) {
                        (Some(fs), Some(hs), Some(he)) => Some((fs, hs, he)),
                        _ => None,
                    });
                if conv.fires(&conv.scores(hunk_content, host)) {
                    self.convention_bonus
                } else {
                    0.0
                }
            }
            None => 0.0,
        };

        let stages = StageScores {
            import_score,
            bpe_score,
            call_receiver_contribution: contribution,
            convention_contribution,
        };

        // 5. Multi-reason resolution.
        let adjusted_bpe = bpe_score + contribution;
        let cr_active = self.call_receiver.is_some();
        let bpe_side_score = if cr_active { adjusted_bpe } else { bpe_score };

        let import_fired = import_score >= IMPORT_THRESHOLD;
        let bpe_fired = bpe_score > self.bpe_threshold;
        // Foreign-context gate for the call-receiver reason: a call-receiver
        // contribution may flag a hunk on its own only when the hunk reaches
        // into a module foreign to the repo — a foreign import in the hunk or
        // its file, or an unattested callee whose namespace the repo has never
        // used. A bare unattested callee with no foreign association is the
        // codebase's own new code (a fresh local function/method), not foreign
        // voice, and must not cry wolf. Evaluated lazily, only when the
        // contribution would otherwise win.
        let cr_would_fire = cr_active && !bpe_fired && bpe_side_score > self.bpe_threshold;
        // Foreign reach is checked at HUNK granularity, not file: a file that
        // reaches a foreign module in one hunk must not flag every *other* hunk
        // whose new code is entirely the repo's own. A file-level foreign import
        // is deliberately NOT enough on its own — a benign refactor hunk in a
        // file that merely *has* a foreign `#include`/dependency (ink pulling
        // `terminal-size`, a rocksdb `.cc` with one new dep) must stay quiet.
        // Every genuine foreign symbol a break introduces (`event_base_new`,
        // `boost::`, jQuery `$`) sits in the scored hunk itself, so hunk-level
        // reach catches it; the hunk's own foreign import opens the gate too.
        let hunk_foreign_reach = cr_would_fire
            && self.call_receiver.as_ref().is_some_and(|cr| {
                cr.hunk_reaches_foreign(hunk_content, cr_host_context, &local_bindings)
            });
        // A file-level foreign import (in a hunk other than this one) colours
        // this hunk only when the hunk actually *uses* a name that import bound
        // — colorama's `Fore`/`Style`, numpy's `np`/`default_rng`, `httpx` —
        // reached through a receiver the hunk itself doesn't re-import. A
        // benign refactor whose callees are all the repo's own attested code
        // (ink's `performance.now`, bat's `.canonicalize`) never matches, so it
        // stays quiet.
        let hunk_uses_foreign_binding = cr_would_fire
            && !hunk_foreign_reach
            && import_score < IMPORT_THRESHOLD
            && self.hunk_uses_foreign_import_binding(hunk_content, binding_source, check_only);
        // An explicit foreign namespace (`\Respect\Validation\Validator::key`,
        // `tokio::spawn`) is an unambiguous foreign-dependency reference — as
        // strong a signal as a foreign import — so it fires regardless of the
        // surprisal threshold. A tiny edit that reaches a namespace the repo
        // has never used must not slip under the bar (the laravel PHP-FQN
        // breaks). On real commits such a fire is a correct novel-pattern
        // *detection* (a new namespaced dependency), not an over-fire.
        let explicit_foreign = cr_active
            && self.call_receiver.as_ref().is_some_and(|cr| {
                cr.hunk_names_explicit_foreign_namespace(
                    hunk_content,
                    cr_host_context,
                    &local_bindings,
                )
            });
        // The call-receiver *reason* carries a hunk only on a genuine foreign
        // callee signal (reach / foreign binding / explicit namespace). A foreign
        // *import* in the hunk opens the surprisal gate, but the Import reason
        // already names that dependency — so it must NOT also make call-receiver a
        // competing candidate. Otherwise an import-gated call-receiver, riding on
        // the repo's own attested callees (a Django view that imports `django`
        // AND calls `self.repo.find`), wins the ratio tiebreak yet resolves to
        // empty callee evidence, dropping the whole hit and losing the valid
        // foreign-import flag. Genuine foreign callees are caught by hunk reach.
        let cr_fired = (cr_would_fire && (hunk_foreign_reach || hunk_uses_foreign_binding))
            || explicit_foreign;
        let conv_side_score = bpe_score + convention_contribution;
        let conv_fired =
            convention_contribution > 0.0 && !bpe_fired && conv_side_score > self.bpe_threshold;
        let denom = self.bpe_threshold.max(EPSILON);

        // (reason, score, threshold, ratio)
        let mut candidates: Vec<(Reason, f64, f64, f64)> = Vec::new();
        if import_fired {
            candidates.push((
                Reason::Import,
                import_score,
                IMPORT_THRESHOLD,
                import_score / IMPORT_THRESHOLD,
            ));
        }
        if bpe_fired {
            candidates.push((
                Reason::Bpe,
                bpe_score,
                self.bpe_threshold,
                bpe_score / denom,
            ));
        }
        if cr_fired {
            // An explicit foreign namespace clears the bar on its own (foreign
            // reference, threshold-independent); otherwise the surprisal-side
            // score already exceeded it.
            let cr_score = if explicit_foreign {
                adjusted_bpe.max(self.bpe_threshold)
            } else {
                adjusted_bpe
            };
            candidates.push((
                Reason::CallReceiver,
                cr_score,
                self.bpe_threshold,
                cr_score / denom,
            ));
        }
        if conv_fired {
            candidates.push((
                Reason::Convention,
                conv_side_score,
                self.bpe_threshold,
                conv_side_score / denom,
            ));
        }

        let foreign_import_modules: Vec<String> = {
            let mut v: Vec<String> = foreign.iter().cloned().collect();
            v.sort();
            v
        };

        // A check-only file is scored by a model that never read one. Its
        // surprisal, callee clusters and conventions all describe production
        // phrasing, so judging test phrasing against them is a category error —
        // withhold every candidate but the import, whose verdict is a
        // membership test the fit *did* learn for this scope.
        if check_only {
            candidates.retain(|c| c.0 == Reason::Import);
        }

        if !candidates.is_empty() {
            let tiebreak = |r: Reason| match r {
                Reason::CallReceiver => 0,
                Reason::Import => 1,
                Reason::Convention => 2,
                _ => 3,
            };
            candidates.sort_by(|a, b| {
                b.3.partial_cmp(&a.3)
                    .unwrap_or(std::cmp::Ordering::Equal)
                    .then_with(|| tiebreak(a.0).cmp(&tiebreak(b.0)))
            });
            // Among the reasons that fired, report the strongest one that can
            // actually name what it saw. They describe the same hunk, so this
            // never changes whether it is flagged — only which rule speaks for
            // it, and a rule with nothing to name leaves the reader a "common
            // here" line and no finding. Falls back to the strongest reason
            // when none of them can name anything.
            let (mut chosen, mut strongest) = (None, None);
            for (i, c) in candidates.iter().enumerate() {
                let evidence = self.collect_evidence(
                    c.0,
                    hunk_content,
                    masked_input,
                    file_path,
                    file_source,
                    &foreign,
                    &local_bindings,
                    cr_host_context,
                );
                if evidence.as_ref().is_some_and(Evidence::names_something) {
                    chosen = Some((i, evidence));
                    break;
                }
                strongest.get_or_insert((i, evidence));
            }
            let (idx, evidence) = chosen.or(strongest).expect("candidates is non-empty");
            let winner = candidates[idx];
            return ScoredHunk {
                score: winner.1,
                threshold: winner.2,
                flagged: true,
                reason: winner.0,
                stages,
                evidence,
                foreign_import_modules: foreign_import_modules.clone(),
            };
        }

        ScoredHunk {
            score: bpe_side_score,
            threshold: self.bpe_threshold,
            flagged: false,
            reason: Reason::None,
            stages,
            evidence: None,
            foreign_import_modules,
        }
    }

    /// Dispatch to the per-reason evidence collector after a hunk fires
    /// (`_collect_evidence`). Returns `None` when the scorer wasn't built with
    /// an [`EvidenceCorpus`] — the renderer then skips the evidence block,
    /// matching the unflagged path.
    #[allow(clippy::too_many_arguments)]
    fn collect_evidence(
        &self,
        winning_reason: Reason,
        hunk_content: &str,
        bpe_input: &str,
        file_path: Option<&Path>,
        file_source: Option<&str>,
        foreign: &HashSet<String>,
        local_bindings: &crate::scoring::call_receiver::LocalBindings,
        host_context: Option<(&str, usize, usize)>,
    ) -> Option<Evidence> {
        let corpus = self.evidence_corpus.as_ref()?;
        match winning_reason {
            Reason::Import => {
                // Preserve the order the imports appear in the hunk, and capture
                // each foreign specifier's first-occurrence span so the formatter
                // can annotate (`msgspec (L7)`), the truncator can keep the line
                // visible, and the renderer can draw carets.
                // Read the SAME text the import stage scored (prose-blanked,
                // line count preserved, so spans still address the displayed
                // hunk): scoring one parse and naming specifiers from another
                // renders a finding with nothing actionable in it.
                let imports_with_spans = self.adapter.extract_imports_with_spans(bpe_input);
                let mut ordered_foreign: Vec<String> = Vec::new();
                let mut seen_foreign: HashSet<String> = HashSet::new();
                let mut foreign_spans: Vec<(String, SourceSpan)> = Vec::new();
                for (spec, line, col_start, col_end) in imports_with_spans {
                    if !foreign.contains(&spec) {
                        continue;
                    }
                    if seen_foreign.insert(spec.clone()) {
                        ordered_foreign.push(spec.clone());
                        foreign_spans.push((
                            spec,
                            SourceSpan {
                                line,
                                col_start,
                                col_end,
                            },
                        ));
                    }
                }
                Some(Evidence::Import(collect_import_evidence(
                    ordered_foreign,
                    foreign_spans,
                    corpus,
                )))
            }
            Reason::CallReceiver => {
                let cr = self.call_receiver.as_ref()?;
                let cluster_id = cr.cluster_id_for_hunk_file(file_path, file_source);
                Some(Evidence::CallReceiver(collect_call_receiver_evidence(
                    cr.distinct_unattested_excluding(hunk_content, host_context, local_bindings),
                    cluster_id,
                    corpus,
                )))
            }
            Reason::Bpe => {
                let score_fn = |id: u32| self.bpe.token_surprise(id);
                let is_meaningful = |id: u32| self.bpe.is_meaningful_token_id(id);
                Some(Evidence::Bpe(collect_bpe_evidence(
                    bpe_input,
                    self.bpe.tokenizer(),
                    &score_fn,
                    Some(&is_meaningful),
                    corpus,
                    self.adapter.as_ref(),
                )))
            }
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests;
